// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusConfirmed OrderStatus = "confirmed"
	OrderStatusShipped   OrderStatus = "shipped"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusRefunded  OrderStatus = "refunded"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Cart struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CartItem struct {
	ID        uuid.UUID      `json:"id"`
	CartID    uuid.UUID      `json:"cart_id"`
	VariantID uuid.UUID      `json:"variant_id"`
	ProductID uuid.UUID      `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
	AddedAt   time.Time      `json:"added_at"`
}

type Coupon struct {
	ID           uuid.UUID  `json:"id"`
	Code         string     `json:"code"`
	PromotionID  *uuid.UUID `json:"promotion_id"`
	MaxUses      *int32     `json:"max_uses"`
	UsedCount    int32      `json:"used_count"`
	PerUserLimit int32      `json:"per_user_limit"`
	ExpiresAt    *time.Time `json:"expires_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type Order struct {
	ID              uuid.UUID      `json:"id"`
	OrderNumber     string         `json:"order_number"`
	UserID          uuid.UUID      `json:"user_id"`
	Status          string         `json:"status"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
	ShippingFee     pgtype.Numeric `json:"shipping_fee"`
	DiscountAmount  pgtype.Numeric `json:"discount_amount"`
	Total           pgtype.Numeric `json:"total"`
	ShippingAddress []byte         `json:"shipping_address"`
	CouponCode      *string        `json:"coupon_code"`
	Notes           *string        `json:"notes"`
	Currency        string         `json:"currency"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type OrderItem struct {
	ID        uuid.UUID      `json:"id"`
	OrderID   uuid.UUID      `json:"order_id"`
	VariantID uuid.UUID      `json:"variant_id"`
	ProductID uuid.UUID      `json:"product_id"`
	SellerID  uuid.UUID      `json:"seller_id"`
	Quantity  int32          `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
	Snapshot  []byte         `json:"snapshot"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
}

type Promotion struct {
	ID            uuid.UUID      `json:"id"`
	SellerID      *uuid.UUID     `json:"seller_id"`
	Name          string         `json:"name"`
	Type          string         `json:"type"`
	Value         pgtype.Numeric `json:"value"`
	MinOrderValue pgtype.Numeric `json:"min_order_value"`
	MaxDiscount   pgtype.Numeric `json:"max_discount"`
	StartsAt      time.Time      `json:"starts_at"`
	EndsAt        time.Time      `json:"ends_at"`
	IsActive      bool           `json:"is_active"`
	CreatedAt     time.Time      `json:"created_at"`
}
