// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToCartItem = `-- name: AddToCartItem :exec
INSERT INTO cart_items (cart_id, variant_id, product_id, quantity, unit_price)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (cart_id, variant_id) DO UPDATE SET
    quantity   = cart_items.quantity + EXCLUDED.quantity,
    unit_price = EXCLUDED.unit_price,
    added_at   = NOW()
`

type AddToCartItemParams struct {
	CartID    uuid.UUID      `json:"cart_id"`
	VariantID uuid.UUID      `json:"variant_id"`
	ProductID uuid.UUID      `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
}

// AddToCartItem
//
//	INSERT INTO cart_items (cart_id, variant_id, product_id, quantity, unit_price)
//	VALUES ($1, $2, $3, $4, $5)
//	ON CONFLICT (cart_id, variant_id) DO UPDATE SET
//	    quantity   = cart_items.quantity + EXCLUDED.quantity,
//	    unit_price = EXCLUDED.unit_price,
//	    added_at   = NOW()
func (q *Queries) AddToCartItem(ctx context.Context, arg AddToCartItemParams) error {
	_, err := q.db.Exec(ctx, addToCartItem,
		arg.CartID,
		arg.VariantID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
	)
	return err
}

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'pending'
RETURNING id, order_number, user_id, status, subtotal, shipping_fee, discount_amount, total,
          shipping_address, coupon_code, notes, currency, created_at, updated_at
`

type CancelOrderParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// CancelOrder
//
//	UPDATE orders
//	SET status = 'cancelled', updated_at = NOW()
//	WHERE id = $1 AND user_id = $2 AND status = 'pending'
//	RETURNING id, order_number, user_id, status, subtotal, shipping_fee, discount_amount, total,
//	          shipping_address, coupon_code, notes, currency, created_at, updated_at
func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.Subtotal,
		&i.ShippingFee,
		&i.DiscountAmount,
		&i.Total,
		&i.ShippingAddress,
		&i.CouponCode,
		&i.Notes,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelOrderItems = `-- name: CancelOrderItems :exec
UPDATE order_items SET status = 'cancelled'
WHERE order_id = $1
`

// CancelOrderItems
//
//	UPDATE order_items SET status = 'cancelled'
//	WHERE order_id = $1
func (q *Queries) CancelOrderItems(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelOrderItems, orderID)
	return err
}

const clearCartItems = `-- name: ClearCartItems :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

// ClearCartItems
//
//	DELETE FROM cart_items
//	WHERE cart_id = $1
func (q *Queries) ClearCartItems(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCartItems, cartID)
	return err
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*) FROM orders WHERE user_id = $1
`

// CountOrdersByUser
//
//	SELECT COUNT(*) FROM orders WHERE user_id = $1
func (q *Queries) CountOrdersByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (order_number, user_id, status, subtotal, shipping_fee, discount_amount, total, shipping_address, coupon_code, notes, currency)
VALUES ($1, $2, 'pending', $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type CreateOrderParams struct {
	OrderNumber     string         `json:"order_number"`
	UserID          uuid.UUID      `json:"user_id"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
	ShippingFee     pgtype.Numeric `json:"shipping_fee"`
	DiscountAmount  pgtype.Numeric `json:"discount_amount"`
	Total           pgtype.Numeric `json:"total"`
	ShippingAddress []byte         `json:"shipping_address"`
	CouponCode      *string        `json:"coupon_code"`
	Notes           *string        `json:"notes"`
	Currency        string         `json:"currency"`
}

// CreateOrder
//
//	INSERT INTO orders (order_number, user_id, status, subtotal, shipping_fee, discount_amount, total, shipping_address, coupon_code, notes, currency)
//	VALUES ($1, $2, 'pending', $3, $4, $5, $6, $7, $8, $9, $10)
//	RETURNING id
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.UserID,
		arg.Subtotal,
		arg.ShippingFee,
		arg.DiscountAmount,
		arg.Total,
		arg.ShippingAddress,
		arg.CouponCode,
		arg.Notes,
		arg.Currency,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, variant_id, product_id, seller_id, quantity, unit_price, snapshot, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
`

type CreateOrderItemParams struct {
	OrderID   uuid.UUID      `json:"order_id"`
	VariantID uuid.UUID      `json:"variant_id"`
	ProductID uuid.UUID      `json:"product_id"`
	SellerID  uuid.UUID      `json:"seller_id"`
	Quantity  int32          `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
	Snapshot  []byte         `json:"snapshot"`
}

// CreateOrderItem
//
//	INSERT INTO order_items (order_id, variant_id, product_id, seller_id, quantity, unit_price, snapshot, status)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.ProductID,
		arg.SellerID,
		arg.Quantity,
		arg.UnitPrice,
		arg.Snapshot,
	)
	return err
}

const getCartItems = `-- name: GetCartItems :many
SELECT id, cart_id, variant_id, product_id, quantity, unit_price, added_at
FROM cart_items
WHERE cart_id = $1
ORDER BY added_at ASC
`

// GetCartItems
//
//	SELECT id, cart_id, variant_id, product_id, quantity, unit_price, added_at
//	FROM cart_items
//	WHERE cart_id = $1
//	ORDER BY added_at ASC
func (q *Queries) GetCartItems(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.VariantID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCouponWithPromotion = `-- name: GetCouponWithPromotion :one
SELECT
    c.id, c.code, c.promotion_id, c.max_uses, c.used_count, c.per_user_limit, c.expires_at, c.created_at,
    p.id, p.seller_id, p.name, p.type, p.value, p.min_order_value, p.max_discount,
    p.starts_at, p.ends_at, p.is_active, p.created_at
FROM coupons c
JOIN promotions p ON p.id = c.promotion_id
WHERE c.code = $1
  AND p.is_active = TRUE
  AND p.starts_at <= NOW()
  AND p.ends_at   >= NOW()
  AND (c.expires_at IS NULL OR c.expires_at >= NOW())
`

type GetCouponWithPromotionRow struct {
	ID            uuid.UUID      `json:"id"`
	Code          string         `json:"code"`
	PromotionID   *uuid.UUID     `json:"promotion_id"`
	MaxUses       *int32         `json:"max_uses"`
	UsedCount     int32          `json:"used_count"`
	PerUserLimit  int32          `json:"per_user_limit"`
	ExpiresAt     *time.Time     `json:"expires_at"`
	CreatedAt     time.Time      `json:"created_at"`
	ID_2          uuid.UUID      `json:"id_2"`
	SellerID      *uuid.UUID     `json:"seller_id"`
	Name          string         `json:"name"`
	Type          string         `json:"type"`
	Value         pgtype.Numeric `json:"value"`
	MinOrderValue pgtype.Numeric `json:"min_order_value"`
	MaxDiscount   pgtype.Numeric `json:"max_discount"`
	StartsAt      time.Time      `json:"starts_at"`
	EndsAt        time.Time      `json:"ends_at"`
	IsActive      bool           `json:"is_active"`
	CreatedAt_2   time.Time      `json:"created_at_2"`
}

// GetCouponWithPromotion
//
//	SELECT
//	    c.id, c.code, c.promotion_id, c.max_uses, c.used_count, c.per_user_limit, c.expires_at, c.created_at,
//	    p.id, p.seller_id, p.name, p.type, p.value, p.min_order_value, p.max_discount,
//	    p.starts_at, p.ends_at, p.is_active, p.created_at
//	FROM coupons c
//	JOIN promotions p ON p.id = c.promotion_id
//	WHERE c.code = $1
//	  AND p.is_active = TRUE
//	  AND p.starts_at <= NOW()
//	  AND p.ends_at   >= NOW()
//	  AND (c.expires_at IS NULL OR c.expires_at >= NOW())
func (q *Queries) GetCouponWithPromotion(ctx context.Context, code string) (GetCouponWithPromotionRow, error) {
	row := q.db.QueryRow(ctx, getCouponWithPromotion, code)
	var i GetCouponWithPromotionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PromotionID,
		&i.MaxUses,
		&i.UsedCount,
		&i.PerUserLimit,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ID_2,
		&i.SellerID,
		&i.Name,
		&i.Type,
		&i.Value,
		&i.MinOrderValue,
		&i.MaxDiscount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt_2,
	)
	return i, err
}

const getOrCreateCart = `-- name: GetOrCreateCart :one
INSERT INTO carts (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET updated_at = NOW()
RETURNING id, user_id, created_at, updated_at
`

// GetOrCreateCart
//
//	INSERT INTO carts (user_id)
//	VALUES ($1)
//	ON CONFLICT (user_id) DO UPDATE SET updated_at = NOW()
//	RETURNING id, user_id, created_at, updated_at
func (q *Queries) GetOrCreateCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getOrCreateCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, order_number, user_id, status, subtotal, shipping_fee, discount_amount, total,
       shipping_address, coupon_code, notes, currency, created_at, updated_at
FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// GetOrder
//
//	SELECT id, order_number, user_id, status, subtotal, shipping_fee, discount_amount, total,
//	       shipping_address, coupon_code, notes, currency, created_at, updated_at
//	FROM orders
//	WHERE id = $1 AND user_id = $2
func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.Subtotal,
		&i.ShippingFee,
		&i.DiscountAmount,
		&i.Total,
		&i.ShippingAddress,
		&i.CouponCode,
		&i.Notes,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, order_id, variant_id, product_id, seller_id, quantity, unit_price, snapshot, status, created_at
FROM order_items
WHERE order_id = $1
`

// GetOrderItems
//
//	SELECT id, order_id, variant_id, product_id, seller_id, quantity, unit_price, snapshot, status, created_at
//	FROM order_items
//	WHERE order_id = $1
func (q *Queries) GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.ProductID,
			&i.SellerID,
			&i.Quantity,
			&i.UnitPrice,
			&i.Snapshot,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCouponUses = `-- name: IncrementCouponUses :exec
UPDATE coupons SET used_count = used_count + 1
WHERE code = $1
`

// IncrementCouponUses
//
//	UPDATE coupons SET used_count = used_count + 1
//	WHERE code = $1
func (q *Queries) IncrementCouponUses(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, incrementCouponUses, code)
	return err
}

const listOrders = `-- name: ListOrders :many
SELECT id, order_number, user_id, status, subtotal, shipping_fee, discount_amount, total,
       shipping_address, coupon_code, notes, currency, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

// ListOrders
//
//	SELECT id, order_number, user_id, status, subtotal, shipping_fee, discount_amount, total,
//	       shipping_address, coupon_code, notes, currency, created_at, updated_at
//	FROM orders
//	WHERE user_id = $1
//	ORDER BY created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.Subtotal,
			&i.ShippingFee,
			&i.DiscountAmount,
			&i.Total,
			&i.ShippingAddress,
			&i.CouponCode,
			&i.Notes,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE cart_id = $1 AND id = $2
`

type RemoveCartItemParams struct {
	CartID uuid.UUID `json:"cart_id"`
	ID     uuid.UUID `json:"id"`
}

// RemoveCartItem
//
//	DELETE FROM cart_items
//	WHERE cart_id = $1 AND id = $2
func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.Exec(ctx, removeCartItem, arg.CartID, arg.ID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :exec
UPDATE cart_items
SET quantity = $3, added_at = NOW()
WHERE cart_id = $1 AND id = $2
`

type UpdateCartItemQuantityParams struct {
	CartID   uuid.UUID `json:"cart_id"`
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

// UpdateCartItemQuantity
//
//	UPDATE cart_items
//	SET quantity = $3, added_at = NOW()
//	WHERE cart_id = $1 AND id = $2
func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error {
	_, err := q.db.Exec(ctx, updateCartItemQuantity, arg.CartID, arg.ID, arg.Quantity)
	return err
}

const updateOrderItemsStatus = `-- name: UpdateOrderItemsStatus :exec
UPDATE order_items SET status = $2::order_status
WHERE order_id = $1
`

type UpdateOrderItemsStatusParams struct {
	OrderID uuid.UUID `json:"order_id"`
	Column2 string    `json:"column_2"`
}

// UpdateOrderItemsStatus
//
//	UPDATE order_items SET status = $2::order_status
//	WHERE order_id = $1
func (q *Queries) UpdateOrderItemsStatus(ctx context.Context, arg UpdateOrderItemsStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderItemsStatus, arg.OrderID, arg.Column2)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $2::order_status, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

// UpdateOrderStatus
//
//	UPDATE orders SET status = $2::order_status, updated_at = NOW()
//	WHERE id = $1
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Column2)
	return err
}
