// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (user_id, label, full_name, phone, address_line1, address_line2, city, state, postal_code, country, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, label, full_name, phone, address_line1, address_line2, city, state, postal_code, country, is_default, created_at
`

type CreateAddressParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Label        *string   `json:"label"`
	FullName     string    `json:"full_name"`
	Phone        string    `json:"phone"`
	AddressLine1 string    `json:"address_line1"`
	AddressLine2 *string   `json:"address_line2"`
	City         string    `json:"city"`
	State        *string   `json:"state"`
	PostalCode   *string   `json:"postal_code"`
	Country      string    `json:"country"`
	IsDefault    bool      `json:"is_default"`
}

// CreateAddress
//
//	INSERT INTO addresses (user_id, label, full_name, phone, address_line1, address_line2, city, state, postal_code, country, is_default)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
//	RETURNING id, user_id, label, full_name, phone, address_line1, address_line2, city, state, postal_code, country, is_default, created_at
func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Label,
		arg.FullName,
		arg.Phone,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.FullName,
		&i.Phone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO phone_otps (phone, otp_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, phone, otp_hash, expires_at, used, attempts, created_at
`

type CreateOTPParams struct {
	Phone     string    `json:"phone"`
	OtpHash   string    `json:"otp_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// CreateOTP
//
//	INSERT INTO phone_otps (phone, otp_hash, expires_at)
//	VALUES ($1, $2, $3)
//	RETURNING id, phone, otp_hash, expires_at, used, attempts, created_at
func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (PhoneOtp, error) {
	row := q.db.QueryRow(ctx, createOTP, arg.Phone, arg.OtpHash, arg.ExpiresAt)
	var i PhoneOtp
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.Used,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// CreateRefreshToken
//
//	INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
//	VALUES ($1, $2, $3)
//	RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        *string `json:"email"`
	Phone        *string `json:"phone"`
	PasswordHash *string `json:"password_hash"`
	FullName     string  `json:"full_name"`
	AvatarUrl    *string `json:"avatar_url"`
	Role         string  `json:"role"`
	AuthProvider string  `json:"auth_provider"`
	IsVerified   bool    `json:"is_verified"`
	GoogleID     *string `json:"google_id"`
}

// CreateUser
//
//	INSERT INTO users (email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
//	RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.FullName,
		arg.AvatarUrl,
		arg.Role,
		arg.AuthProvider,
		arg.IsVerified,
		arg.GoogleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.AuthProvider,
		&i.IsVerified,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses WHERE id = $1 AND user_id = $2
`

type DeleteAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// DeleteAddress
//
//	DELETE FROM addresses WHERE id = $1 AND user_id = $2
func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.UserID)
	return err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, phone, otp_hash, expires_at, used, attempts, created_at FROM phone_otps
WHERE phone = $1 AND used = FALSE AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

// GetLatestOTP
//
//	SELECT id, phone, otp_hash, expires_at, used, attempts, created_at FROM phone_otps
//	WHERE phone = $1 AND used = FALSE AND expires_at > NOW()
//	ORDER BY created_at DESC
//	LIMIT 1
func (q *Queries) GetLatestOTP(ctx context.Context, phone string) (PhoneOtp, error) {
	row := q.db.QueryRow(ctx, getLatestOTP, phone)
	var i PhoneOtp
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.Used,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

// GetRefreshToken
//
//	SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens
//	WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

// GetUserByEmail
//
//	SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.AuthProvider,
		&i.IsVerified,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE google_id = $1 AND deleted_at IS NULL
`

// GetUserByGoogleID
//
//	SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE google_id = $1 AND deleted_at IS NULL
func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.AuthProvider,
		&i.IsVerified,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

// GetUserByID
//
//	SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.AuthProvider,
		&i.IsVerified,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE phone = $1 AND deleted_at IS NULL
`

// GetUserByPhone
//
//	SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE phone = $1 AND deleted_at IS NULL
func (q *Queries) GetUserByPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.AuthProvider,
		&i.IsVerified,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

// GetUsersByIDs
//
//	SELECT id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at FROM users WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.Role,
			&i.AuthProvider,
			&i.IsVerified,
			&i.GoogleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE phone_otps SET attempts = attempts + 1 WHERE id = $1
`

// IncrementOTPAttempts
//
//	UPDATE phone_otps SET attempts = attempts + 1 WHERE id = $1
func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT id, user_id, label, full_name, phone, address_line1, address_line2, city, state, postal_code, country, is_default, created_at FROM addresses WHERE user_id = $1 ORDER BY is_default DESC, created_at DESC
`

// ListAddressesByUser
//
//	SELECT id, user_id, label, full_name, phone, address_line1, address_line2, city, state, postal_code, country, is_default, created_at FROM addresses WHERE user_id = $1 ORDER BY is_default DESC, created_at DESC
func (q *Queries) ListAddressesByUser(ctx context.Context, userID uuid.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.FullName,
			&i.Phone,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE phone_otps SET used = TRUE WHERE id = $1
`

// MarkOTPUsed
//
//	UPDATE phone_otps SET used = TRUE WHERE id = $1
func (q *Queries) MarkOTPUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

// RevokeAllUserTokens
//
//	UPDATE refresh_tokens SET revoked_at = NOW()
//	WHERE user_id = $1 AND revoked_at IS NULL
func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW()
WHERE token_hash = $1
`

// RevokeRefreshToken
//
//	UPDATE refresh_tokens SET revoked_at = NOW()
//	WHERE token_hash = $1
func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const unsetDefaultAddresses = `-- name: UnsetDefaultAddresses :exec
UPDATE addresses SET is_default = FALSE WHERE user_id = $1
`

// UnsetDefaultAddresses
//
//	UPDATE addresses SET is_default = FALSE WHERE user_id = $1
func (q *Queries) UnsetDefaultAddresses(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsetDefaultAddresses, userID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    full_name  = COALESCE(NULLIF($1::text, ''), full_name),
    avatar_url = COALESCE(NULLIF($2::text, ''), avatar_url),
    updated_at = NOW()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	FullName  string    `json:"full_name"`
	AvatarUrl string    `json:"avatar_url"`
	ID        uuid.UUID `json:"id"`
}

// UpdateUser
//
//	UPDATE users SET
//	    full_name  = COALESCE(NULLIF($1::text, ''), full_name),
//	    avatar_url = COALESCE(NULLIF($2::text, ''), avatar_url),
//	    updated_at = NOW()
//	WHERE id = $3 AND deleted_at IS NULL
//	RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.FullName, arg.AvatarUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.AuthProvider,
		&i.IsVerified,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertGoogleUser = `-- name: UpsertGoogleUser :one
INSERT INTO users (email, full_name, avatar_url, role, auth_provider, is_verified, google_id)
VALUES ($1, $2, $3, 'buyer', 'google', TRUE, $4)
ON CONFLICT (google_id) DO UPDATE SET
    full_name  = EXCLUDED.full_name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
`

type UpsertGoogleUserParams struct {
	Email     *string `json:"email"`
	FullName  string  `json:"full_name"`
	AvatarUrl *string `json:"avatar_url"`
	GoogleID  *string `json:"google_id"`
}

// UpsertGoogleUser
//
//	INSERT INTO users (email, full_name, avatar_url, role, auth_provider, is_verified, google_id)
//	VALUES ($1, $2, $3, 'buyer', 'google', TRUE, $4)
//	ON CONFLICT (google_id) DO UPDATE SET
//	    full_name  = EXCLUDED.full_name,
//	    avatar_url = EXCLUDED.avatar_url,
//	    updated_at = NOW()
//	RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
func (q *Queries) UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertGoogleUser,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
		arg.GoogleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.AuthProvider,
		&i.IsVerified,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertPhoneUser = `-- name: UpsertPhoneUser :one
INSERT INTO users (phone, full_name, role, auth_provider, is_verified)
VALUES ($1, $2, 'buyer', 'phone', TRUE)
ON CONFLICT (phone) DO UPDATE SET updated_at = NOW()
RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
`

type UpsertPhoneUserParams struct {
	Phone    *string `json:"phone"`
	FullName string  `json:"full_name"`
}

// UpsertPhoneUser
//
//	INSERT INTO users (phone, full_name, role, auth_provider, is_verified)
//	VALUES ($1, $2, 'buyer', 'phone', TRUE)
//	ON CONFLICT (phone) DO UPDATE SET updated_at = NOW()
//	RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
func (q *Queries) UpsertPhoneUser(ctx context.Context, arg UpsertPhoneUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertPhoneUser, arg.Phone, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.AuthProvider,
		&i.IsVerified,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users SET is_verified = TRUE, updated_at = NOW()
WHERE id = $1
RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
`

// VerifyUser
//
//	UPDATE users SET is_verified = TRUE, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, email, phone, password_hash, full_name, avatar_url, role, auth_provider, is_verified, google_id, created_at, updated_at, deleted_at
func (q *Queries) VerifyUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.AuthProvider,
		&i.IsVerified,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
