// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppointmentStatus string

const (
	AppointmentStatusScheduled AppointmentStatus = "scheduled"
	AppointmentStatusConfirmed AppointmentStatus = "confirmed"
	AppointmentStatusCompleted AppointmentStatus = "completed"
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
	AppointmentStatusNoShow    AppointmentStatus = "no_show"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus `json:"appointment_status"`
	Valid             bool              `json:"valid"` // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type BookingStatus string

const (
	BookingStatusPendingPayment BookingStatus = "pending_payment"
	BookingStatusRequested      BookingStatus = "requested"
	BookingStatusConfirmed      BookingStatus = "confirmed"
	BookingStatusCancelled      BookingStatus = "cancelled"
	BookingStatusActive         BookingStatus = "active"
	BookingStatusCompleted      BookingStatus = "completed"
	BookingStatusDisputed       BookingStatus = "disputed"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type ListingStatus string

const (
	ListingStatusDraft           ListingStatus = "draft"
	ListingStatusPendingApproval ListingStatus = "pending_approval"
	ListingStatusActive          ListingStatus = "active"
	ListingStatusSuspended       ListingStatus = "suspended"
	ListingStatusSold            ListingStatus = "sold"
	ListingStatusRented          ListingStatus = "rented"
	ListingStatusInactive        ListingStatus = "inactive"
)

func (e *ListingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListingStatus(s)
	case string:
		*e = ListingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListingStatus: %T", src)
	}
	return nil
}

type NullListingStatus struct {
	ListingStatus ListingStatus `json:"listing_status"`
	Valid         bool          `json:"valid"` // Valid is true if ListingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListingStatus), nil
}

type ListingType string

const (
	ListingTypeRental ListingType = "rental"
	ListingTypeSale   ListingType = "sale"
)

func (e *ListingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListingType(s)
	case string:
		*e = ListingType(s)
	default:
		return fmt.Errorf("unsupported scan type for ListingType: %T", src)
	}
	return nil
}

type NullListingType struct {
	ListingType ListingType `json:"listing_type"`
	Valid       bool        `json:"valid"` // Valid is true if ListingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListingType) Scan(value interface{}) error {
	if value == nil {
		ns.ListingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListingType), nil
}

type OfferStatus string

const (
	OfferStatusSubmitted     OfferStatus = "submitted"
	OfferStatusAccepted      OfferStatus = "accepted"
	OfferStatusRejected      OfferStatus = "rejected"
	OfferStatusUnderEscrow   OfferStatus = "under_escrow"
	OfferStatusFundsReleased OfferStatus = "funds_released"
	OfferStatusCancelled     OfferStatus = "cancelled"
	OfferStatusDisputed      OfferStatus = "disputed"
)

func (e *OfferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OfferStatus(s)
	case string:
		*e = OfferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OfferStatus: %T", src)
	}
	return nil
}

type NullOfferStatus struct {
	OfferStatus OfferStatus `json:"offer_status"`
	Valid       bool        `json:"valid"` // Valid is true if OfferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOfferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OfferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OfferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOfferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OfferStatus), nil
}

type PropertyType string

const (
	PropertyTypeApartment PropertyType = "apartment"
	PropertyTypeHouse     PropertyType = "house"
	PropertyTypeVilla     PropertyType = "villa"
	PropertyTypeCondo     PropertyType = "condo"
	PropertyTypeTownhouse PropertyType = "townhouse"
	PropertyTypeCabin     PropertyType = "cabin"
	PropertyTypeStudio    PropertyType = "studio"
	PropertyTypeLand      PropertyType = "land"
)

func (e *PropertyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PropertyType(s)
	case string:
		*e = PropertyType(s)
	default:
		return fmt.Errorf("unsupported scan type for PropertyType: %T", src)
	}
	return nil
}

type NullPropertyType struct {
	PropertyType PropertyType `json:"property_type"`
	Valid        bool         `json:"valid"` // Valid is true if PropertyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPropertyType) Scan(value interface{}) error {
	if value == nil {
		ns.PropertyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PropertyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPropertyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PropertyType), nil
}

type Listing struct {
	ID            uuid.UUID      `json:"id"`
	PropertyID    uuid.UUID      `json:"property_id"`
	Type          string         `json:"type"`
	Status        string         `json:"status"`
	BasePrice     pgtype.Numeric `json:"base_price"`
	Currency      string         `json:"currency"`
	IsInstantBook bool           `json:"is_instant_book"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Property struct {
	ID            uuid.UUID      `json:"id"`
	OwnerID       uuid.UUID      `json:"owner_id"`
	Type          string         `json:"type"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	AddressLine1  string         `json:"address_line1"`
	AddressLine2  *string        `json:"address_line2"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	Country       string         `json:"country"`
	PostalCode    *string        `json:"postal_code"`
	Location      string         `json:"location"`
	BedroomCount  int32          `json:"bedroom_count"`
	BathroomCount pgtype.Numeric `json:"bathroom_count"`
	MaxGuests     int32          `json:"max_guests"`
	SquareMeters  pgtype.Numeric `json:"square_meters"`
	IsVerified    bool           `json:"is_verified"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type PropertyAmenity struct {
	ID         uuid.UUID `json:"id"`
	PropertyID uuid.UUID `json:"property_id"`
	Name       string    `json:"name"`
	Category   string    `json:"category"`
	CreatedAt  time.Time `json:"created_at"`
}

type PropertyImage struct {
	ID           uuid.UUID `json:"id"`
	PropertyID   uuid.UUID `json:"property_id"`
	Url          string    `json:"url"`
	DisplayOrder int32     `json:"display_order"`
	IsCover      bool      `json:"is_cover"`
	CreatedAt    time.Time `json:"created_at"`
}

type RentalBooking struct {
	ID              uuid.UUID      `json:"id"`
	ListingID       uuid.UUID      `json:"listing_id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	StartDate       pgtype.Date    `json:"start_date"`
	EndDate         pgtype.Date    `json:"end_date"`
	NightlyPrice    pgtype.Numeric `json:"nightly_price"`
	CleaningFee     pgtype.Numeric `json:"cleaning_fee"`
	SecurityDeposit pgtype.Numeric `json:"security_deposit"`
	TotalPrice      pgtype.Numeric `json:"total_price"`
	Status          string         `json:"status"`
	PaymentIntentID *string        `json:"payment_intent_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type RentalListingsMetum struct {
	ListingID       uuid.UUID      `json:"listing_id"`
	CleaningFee     pgtype.Numeric `json:"cleaning_fee"`
	SecurityDeposit pgtype.Numeric `json:"security_deposit"`
	MinNights       int32          `json:"min_nights"`
	MaxNights       int32          `json:"max_nights"`
	CheckInTime     pgtype.Time    `json:"check_in_time"`
	CheckOutTime    pgtype.Time    `json:"check_out_time"`
}

type SalesListingsMetum struct {
	ListingID            uuid.UUID      `json:"listing_id"`
	EscrowDepositPercent pgtype.Numeric `json:"escrow_deposit_percent"`
	AgentCommissionRate  pgtype.Numeric `json:"agent_commission_rate"`
	IncludesFurniture    bool           `json:"includes_furniture"`
	YearBuilt            *int32         `json:"year_built"`
	PropertyTaxAnnual    pgtype.Numeric `json:"property_tax_annual"`
}

type SalesOffer struct {
	ID                uuid.UUID      `json:"id"`
	ListingID         uuid.UUID      `json:"listing_id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	OfferPrice        pgtype.Numeric `json:"offer_price"`
	EscrowDepositPaid pgtype.Numeric `json:"escrow_deposit_paid"`
	Status            string         `json:"status"`
	ConditionsText    *string        `json:"conditions_text"`
	ExpirationDate    time.Time      `json:"expiration_date"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type ViewingAppointment struct {
	ID            uuid.UUID `json:"id"`
	ListingID     uuid.UUID `json:"listing_id"`
	ClientID      uuid.UUID `json:"client_id"`
	HostID        uuid.UUID `json:"host_id"`
	ScheduledTime time.Time `json:"scheduled_time"`
	Status        string    `json:"status"`
	Notes         *string   `json:"notes"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
