// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptOffer = `-- name: AcceptOffer :one
UPDATE sales_offers
SET status = 'accepted', updated_at = NOW()
WHERE id = $1 AND status = 'submitted'
RETURNING id, listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date, created_at, updated_at
`

// AcceptOffer
//
//	UPDATE sales_offers
//	SET status = 'accepted', updated_at = NOW()
//	WHERE id = $1 AND status = 'submitted'
//	RETURNING id, listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date, created_at, updated_at
func (q *Queries) AcceptOffer(ctx context.Context, id uuid.UUID) (SalesOffer, error) {
	row := q.db.QueryRow(ctx, acceptOffer, id)
	var i SalesOffer
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.OfferPrice,
		&i.EscrowDepositPaid,
		&i.Status,
		&i.ConditionsText,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO rental_bookings (
    listing_id, tenant_id, start_date, end_date, nightly_price, cleaning_fee, security_deposit, total_price, status, payment_intent_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, listing_id, tenant_id, start_date, end_date, nightly_price, cleaning_fee, security_deposit, total_price, status, payment_intent_id, created_at, updated_at
`

type CreateBookingParams struct {
	ListingID       uuid.UUID      `json:"listing_id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	StartDate       pgtype.Date    `json:"start_date"`
	EndDate         pgtype.Date    `json:"end_date"`
	NightlyPrice    pgtype.Numeric `json:"nightly_price"`
	CleaningFee     pgtype.Numeric `json:"cleaning_fee"`
	SecurityDeposit pgtype.Numeric `json:"security_deposit"`
	TotalPrice      pgtype.Numeric `json:"total_price"`
	Status          string         `json:"status"`
	PaymentIntentID *string        `json:"payment_intent_id"`
}

// CreateBooking
//
//	INSERT INTO rental_bookings (
//	    listing_id, tenant_id, start_date, end_date, nightly_price, cleaning_fee, security_deposit, total_price, status, payment_intent_id
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
//	) RETURNING id, listing_id, tenant_id, start_date, end_date, nightly_price, cleaning_fee, security_deposit, total_price, status, payment_intent_id, created_at, updated_at
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (RentalBooking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ListingID,
		arg.TenantID,
		arg.StartDate,
		arg.EndDate,
		arg.NightlyPrice,
		arg.CleaningFee,
		arg.SecurityDeposit,
		arg.TotalPrice,
		arg.Status,
		arg.PaymentIntentID,
	)
	var i RentalBooking
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.TenantID,
		&i.StartDate,
		&i.EndDate,
		&i.NightlyPrice,
		&i.CleaningFee,
		&i.SecurityDeposit,
		&i.TotalPrice,
		&i.Status,
		&i.PaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createListing = `-- name: CreateListing :one
INSERT INTO listings (
    property_id, type, status, base_price, currency, is_instant_book
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, property_id, type, status, base_price, currency, is_instant_book, created_at, updated_at
`

type CreateListingParams struct {
	PropertyID    uuid.UUID      `json:"property_id"`
	Type          string         `json:"type"`
	Status        string         `json:"status"`
	BasePrice     pgtype.Numeric `json:"base_price"`
	Currency      string         `json:"currency"`
	IsInstantBook bool           `json:"is_instant_book"`
}

// CreateListing
//
//	INSERT INTO listings (
//	    property_id, type, status, base_price, currency, is_instant_book
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6
//	) RETURNING id, property_id, type, status, base_price, currency, is_instant_book, created_at, updated_at
func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.PropertyID,
		arg.Type,
		arg.Status,
		arg.BasePrice,
		arg.Currency,
		arg.IsInstantBook,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Type,
		&i.Status,
		&i.BasePrice,
		&i.Currency,
		&i.IsInstantBook,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOffer = `-- name: CreateOffer :one
INSERT INTO sales_offers (
    listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date, created_at, updated_at
`

type CreateOfferParams struct {
	ListingID         uuid.UUID      `json:"listing_id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	OfferPrice        pgtype.Numeric `json:"offer_price"`
	EscrowDepositPaid pgtype.Numeric `json:"escrow_deposit_paid"`
	Status            string         `json:"status"`
	ConditionsText    *string        `json:"conditions_text"`
	ExpirationDate    time.Time      `json:"expiration_date"`
}

// CreateOffer
//
//	INSERT INTO sales_offers (
//	    listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6, $7
//	) RETURNING id, listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date, created_at, updated_at
func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (SalesOffer, error) {
	row := q.db.QueryRow(ctx, createOffer,
		arg.ListingID,
		arg.BuyerID,
		arg.OfferPrice,
		arg.EscrowDepositPaid,
		arg.Status,
		arg.ConditionsText,
		arg.ExpirationDate,
	)
	var i SalesOffer
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.OfferPrice,
		&i.EscrowDepositPaid,
		&i.Status,
		&i.ConditionsText,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (
    owner_id, type, title, description, address_line1, address_line2, city, state_province, country, postal_code, location, bedroom_count, bathroom_count, max_guests, square_meters
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, ST_SetSRID(ST_MakePoint($11::double precision, $12::double precision), 4326), $13, $14, $15, $16
) RETURNING id, owner_id, type, title, description, address_line1, address_line2, city, state_province, country, postal_code, location, bedroom_count, bathroom_count, max_guests, square_meters, is_verified, created_at, updated_at
`

type CreatePropertyParams struct {
	OwnerID       uuid.UUID      `json:"owner_id"`
	Type          string         `json:"type"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	AddressLine1  string         `json:"address_line1"`
	AddressLine2  *string        `json:"address_line2"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	Country       string         `json:"country"`
	PostalCode    *string        `json:"postal_code"`
	Column11      float64        `json:"column_11"`
	Column12      float64        `json:"column_12"`
	BedroomCount  int32          `json:"bedroom_count"`
	BathroomCount pgtype.Numeric `json:"bathroom_count"`
	MaxGuests     int32          `json:"max_guests"`
	SquareMeters  pgtype.Numeric `json:"square_meters"`
}

// CreateProperty
//
//	INSERT INTO properties (
//	    owner_id, type, title, description, address_line1, address_line2, city, state_province, country, postal_code, location, bedroom_count, bathroom_count, max_guests, square_meters
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, ST_SetSRID(ST_MakePoint($11::double precision, $12::double precision), 4326), $13, $14, $15, $16
//	) RETURNING id, owner_id, type, title, description, address_line1, address_line2, city, state_province, country, postal_code, location, bedroom_count, bathroom_count, max_guests, square_meters, is_verified, created_at, updated_at
func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, createProperty,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.StateProvince,
		arg.Country,
		arg.PostalCode,
		arg.Column11,
		arg.Column12,
		arg.BedroomCount,
		arg.BathroomCount,
		arg.MaxGuests,
		arg.SquareMeters,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateProvince,
		&i.Country,
		&i.PostalCode,
		&i.Location,
		&i.BedroomCount,
		&i.BathroomCount,
		&i.MaxGuests,
		&i.SquareMeters,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPropertyAmenity = `-- name: CreatePropertyAmenity :one
INSERT INTO property_amenities (
    property_id, name, category
) VALUES (
    $1, $2, $3
) RETURNING id, property_id, name, category, created_at
`

type CreatePropertyAmenityParams struct {
	PropertyID uuid.UUID `json:"property_id"`
	Name       string    `json:"name"`
	Category   string    `json:"category"`
}

// CreatePropertyAmenity
//
//	INSERT INTO property_amenities (
//	    property_id, name, category
//	) VALUES (
//	    $1, $2, $3
//	) RETURNING id, property_id, name, category, created_at
func (q *Queries) CreatePropertyAmenity(ctx context.Context, arg CreatePropertyAmenityParams) (PropertyAmenity, error) {
	row := q.db.QueryRow(ctx, createPropertyAmenity, arg.PropertyID, arg.Name, arg.Category)
	var i PropertyAmenity
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const createPropertyImage = `-- name: CreatePropertyImage :one
INSERT INTO property_images (
    property_id, url, display_order, is_cover
) VALUES (
    $1, $2, $3, $4
) RETURNING id, property_id, url, display_order, is_cover, created_at
`

type CreatePropertyImageParams struct {
	PropertyID   uuid.UUID `json:"property_id"`
	Url          string    `json:"url"`
	DisplayOrder int32     `json:"display_order"`
	IsCover      bool      `json:"is_cover"`
}

// CreatePropertyImage
//
//	INSERT INTO property_images (
//	    property_id, url, display_order, is_cover
//	) VALUES (
//	    $1, $2, $3, $4
//	) RETURNING id, property_id, url, display_order, is_cover, created_at
func (q *Queries) CreatePropertyImage(ctx context.Context, arg CreatePropertyImageParams) (PropertyImage, error) {
	row := q.db.QueryRow(ctx, createPropertyImage,
		arg.PropertyID,
		arg.Url,
		arg.DisplayOrder,
		arg.IsCover,
	)
	var i PropertyImage
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Url,
		&i.DisplayOrder,
		&i.IsCover,
		&i.CreatedAt,
	)
	return i, err
}

const createRentalListingMeta = `-- name: CreateRentalListingMeta :one
INSERT INTO rental_listings_meta (
    listing_id, cleaning_fee, security_deposit, min_nights, max_nights, check_in_time, check_out_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING listing_id, cleaning_fee, security_deposit, min_nights, max_nights, check_in_time, check_out_time
`

type CreateRentalListingMetaParams struct {
	ListingID       uuid.UUID      `json:"listing_id"`
	CleaningFee     pgtype.Numeric `json:"cleaning_fee"`
	SecurityDeposit pgtype.Numeric `json:"security_deposit"`
	MinNights       int32          `json:"min_nights"`
	MaxNights       int32          `json:"max_nights"`
	CheckInTime     pgtype.Time    `json:"check_in_time"`
	CheckOutTime    pgtype.Time    `json:"check_out_time"`
}

// CreateRentalListingMeta
//
//	INSERT INTO rental_listings_meta (
//	    listing_id, cleaning_fee, security_deposit, min_nights, max_nights, check_in_time, check_out_time
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6, $7
//	) RETURNING listing_id, cleaning_fee, security_deposit, min_nights, max_nights, check_in_time, check_out_time
func (q *Queries) CreateRentalListingMeta(ctx context.Context, arg CreateRentalListingMetaParams) (RentalListingsMetum, error) {
	row := q.db.QueryRow(ctx, createRentalListingMeta,
		arg.ListingID,
		arg.CleaningFee,
		arg.SecurityDeposit,
		arg.MinNights,
		arg.MaxNights,
		arg.CheckInTime,
		arg.CheckOutTime,
	)
	var i RentalListingsMetum
	err := row.Scan(
		&i.ListingID,
		&i.CleaningFee,
		&i.SecurityDeposit,
		&i.MinNights,
		&i.MaxNights,
		&i.CheckInTime,
		&i.CheckOutTime,
	)
	return i, err
}

const createSalesListingMeta = `-- name: CreateSalesListingMeta :one
INSERT INTO sales_listings_meta (
    listing_id, escrow_deposit_percent, agent_commission_rate, includes_furniture, year_built, property_tax_annual
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING listing_id, escrow_deposit_percent, agent_commission_rate, includes_furniture, year_built, property_tax_annual
`

type CreateSalesListingMetaParams struct {
	ListingID            uuid.UUID      `json:"listing_id"`
	EscrowDepositPercent pgtype.Numeric `json:"escrow_deposit_percent"`
	AgentCommissionRate  pgtype.Numeric `json:"agent_commission_rate"`
	IncludesFurniture    bool           `json:"includes_furniture"`
	YearBuilt            *int32         `json:"year_built"`
	PropertyTaxAnnual    pgtype.Numeric `json:"property_tax_annual"`
}

// CreateSalesListingMeta
//
//	INSERT INTO sales_listings_meta (
//	    listing_id, escrow_deposit_percent, agent_commission_rate, includes_furniture, year_built, property_tax_annual
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6
//	) RETURNING listing_id, escrow_deposit_percent, agent_commission_rate, includes_furniture, year_built, property_tax_annual
func (q *Queries) CreateSalesListingMeta(ctx context.Context, arg CreateSalesListingMetaParams) (SalesListingsMetum, error) {
	row := q.db.QueryRow(ctx, createSalesListingMeta,
		arg.ListingID,
		arg.EscrowDepositPercent,
		arg.AgentCommissionRate,
		arg.IncludesFurniture,
		arg.YearBuilt,
		arg.PropertyTaxAnnual,
	)
	var i SalesListingsMetum
	err := row.Scan(
		&i.ListingID,
		&i.EscrowDepositPercent,
		&i.AgentCommissionRate,
		&i.IncludesFurniture,
		&i.YearBuilt,
		&i.PropertyTaxAnnual,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, listing_id, tenant_id, start_date, end_date, nightly_price, cleaning_fee, security_deposit, total_price, status, payment_intent_id, created_at, updated_at FROM rental_bookings WHERE id = $1
`

// GetBooking
//
//	SELECT id, listing_id, tenant_id, start_date, end_date, nightly_price, cleaning_fee, security_deposit, total_price, status, payment_intent_id, created_at, updated_at FROM rental_bookings WHERE id = $1
func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (RentalBooking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i RentalBooking
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.TenantID,
		&i.StartDate,
		&i.EndDate,
		&i.NightlyPrice,
		&i.CleaningFee,
		&i.SecurityDeposit,
		&i.TotalPrice,
		&i.Status,
		&i.PaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListing = `-- name: GetListing :one
SELECT l.id, l.property_id, l.type, l.status, l.base_price, l.currency, l.is_instant_book, l.created_at, l.updated_at, 
       p.owner_id, p.type AS property_type, p.title, p.description, p.address_line1, p.address_line2, p.city, p.state_province, p.country, p.postal_code,
       (ST_Y(p.location::geometry))::double precision AS latitude, (ST_X(p.location::geometry))::double precision AS longitude,
       p.bedroom_count, p.bathroom_count, p.max_guests, p.square_meters, p.is_verified
FROM listings l
JOIN properties p ON l.property_id = p.id
WHERE l.id = $1
`

type GetListingRow struct {
	ID            uuid.UUID      `json:"id"`
	PropertyID    uuid.UUID      `json:"property_id"`
	Type          string         `json:"type"`
	Status        string         `json:"status"`
	BasePrice     pgtype.Numeric `json:"base_price"`
	Currency      string         `json:"currency"`
	IsInstantBook bool           `json:"is_instant_book"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	OwnerID       uuid.UUID      `json:"owner_id"`
	PropertyType  string         `json:"property_type"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	AddressLine1  string         `json:"address_line1"`
	AddressLine2  *string        `json:"address_line2"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	Country       string         `json:"country"`
	PostalCode    *string        `json:"postal_code"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	BedroomCount  int32          `json:"bedroom_count"`
	BathroomCount pgtype.Numeric `json:"bathroom_count"`
	MaxGuests     int32          `json:"max_guests"`
	SquareMeters  pgtype.Numeric `json:"square_meters"`
	IsVerified    bool           `json:"is_verified"`
}

// GetListing
//
//	SELECT l.id, l.property_id, l.type, l.status, l.base_price, l.currency, l.is_instant_book, l.created_at, l.updated_at,
//	       p.owner_id, p.type AS property_type, p.title, p.description, p.address_line1, p.address_line2, p.city, p.state_province, p.country, p.postal_code,
//	       (ST_Y(p.location::geometry))::double precision AS latitude, (ST_X(p.location::geometry))::double precision AS longitude,
//	       p.bedroom_count, p.bathroom_count, p.max_guests, p.square_meters, p.is_verified
//	FROM listings l
//	JOIN properties p ON l.property_id = p.id
//	WHERE l.id = $1
func (q *Queries) GetListing(ctx context.Context, id uuid.UUID) (GetListingRow, error) {
	row := q.db.QueryRow(ctx, getListing, id)
	var i GetListingRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Type,
		&i.Status,
		&i.BasePrice,
		&i.Currency,
		&i.IsInstantBook,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.PropertyType,
		&i.Title,
		&i.Description,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateProvince,
		&i.Country,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.BedroomCount,
		&i.BathroomCount,
		&i.MaxGuests,
		&i.SquareMeters,
		&i.IsVerified,
	)
	return i, err
}

const getListingsInViewport = `-- name: GetListingsInViewport :many
SELECT l.id AS listing_id, l.property_id, l.type AS listing_type, l.status AS listing_status, l.base_price, l.currency, l.is_instant_book, l.created_at, l.updated_at,
       p.owner_id, p.type AS property_type, p.title, p.description, p.address_line1, p.address_line2, p.city, p.state_province, p.country, p.postal_code,
       (ST_Y(p.location::geometry))::double precision AS latitude, (ST_X(p.location::geometry))::double precision AS longitude,
       p.bedroom_count, p.bathroom_count, p.max_guests, p.square_meters, p.is_verified
FROM properties p
JOIN listings l ON p.id = l.property_id
WHERE l.status = 'active'
  AND p.location && ST_MakeEnvelope(
      $1::double precision, -- Min Longitude (West)
      $2::double precision, -- Min Latitude (South)
      $3::double precision, -- Max Longitude (East)
      $4::double precision, -- Max Latitude (North)
      4326
  )
`

type GetListingsInViewportParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
	Column3 float64 `json:"column_3"`
	Column4 float64 `json:"column_4"`
}

type GetListingsInViewportRow struct {
	ListingID     uuid.UUID      `json:"listing_id"`
	PropertyID    uuid.UUID      `json:"property_id"`
	ListingType   string         `json:"listing_type"`
	ListingStatus string         `json:"listing_status"`
	BasePrice     pgtype.Numeric `json:"base_price"`
	Currency      string         `json:"currency"`
	IsInstantBook bool           `json:"is_instant_book"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	OwnerID       uuid.UUID      `json:"owner_id"`
	PropertyType  string         `json:"property_type"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	AddressLine1  string         `json:"address_line1"`
	AddressLine2  *string        `json:"address_line2"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	Country       string         `json:"country"`
	PostalCode    *string        `json:"postal_code"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	BedroomCount  int32          `json:"bedroom_count"`
	BathroomCount pgtype.Numeric `json:"bathroom_count"`
	MaxGuests     int32          `json:"max_guests"`
	SquareMeters  pgtype.Numeric `json:"square_meters"`
	IsVerified    bool           `json:"is_verified"`
}

// GetListingsInViewport
//
//	SELECT l.id AS listing_id, l.property_id, l.type AS listing_type, l.status AS listing_status, l.base_price, l.currency, l.is_instant_book, l.created_at, l.updated_at,
//	       p.owner_id, p.type AS property_type, p.title, p.description, p.address_line1, p.address_line2, p.city, p.state_province, p.country, p.postal_code,
//	       (ST_Y(p.location::geometry))::double precision AS latitude, (ST_X(p.location::geometry))::double precision AS longitude,
//	       p.bedroom_count, p.bathroom_count, p.max_guests, p.square_meters, p.is_verified
//	FROM properties p
//	JOIN listings l ON p.id = l.property_id
//	WHERE l.status = 'active'
//	  AND p.location && ST_MakeEnvelope(
//	      $1::double precision, -- Min Longitude (West)
//	      $2::double precision, -- Min Latitude (South)
//	      $3::double precision, -- Max Longitude (East)
//	      $4::double precision, -- Max Latitude (North)
//	      4326
//	  )
func (q *Queries) GetListingsInViewport(ctx context.Context, arg GetListingsInViewportParams) ([]GetListingsInViewportRow, error) {
	rows, err := q.db.Query(ctx, getListingsInViewport,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListingsInViewportRow
	for rows.Next() {
		var i GetListingsInViewportRow
		if err := rows.Scan(
			&i.ListingID,
			&i.PropertyID,
			&i.ListingType,
			&i.ListingStatus,
			&i.BasePrice,
			&i.Currency,
			&i.IsInstantBook,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.PropertyType,
			&i.Title,
			&i.Description,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.StateProvince,
			&i.Country,
			&i.PostalCode,
			&i.Latitude,
			&i.Longitude,
			&i.BedroomCount,
			&i.BathroomCount,
			&i.MaxGuests,
			&i.SquareMeters,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOffer = `-- name: GetOffer :one
SELECT id, listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date, created_at, updated_at FROM sales_offers WHERE id = $1
`

// GetOffer
//
//	SELECT id, listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date, created_at, updated_at FROM sales_offers WHERE id = $1
func (q *Queries) GetOffer(ctx context.Context, id uuid.UUID) (SalesOffer, error) {
	row := q.db.QueryRow(ctx, getOffer, id)
	var i SalesOffer
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.OfferPrice,
		&i.EscrowDepositPaid,
		&i.Status,
		&i.ConditionsText,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProperty = `-- name: GetProperty :one
SELECT id, owner_id, type, title, description, address_line1, address_line2, city, state_province, country, postal_code, 
       (ST_Y(location::geometry))::double precision AS latitude, (ST_X(location::geometry))::double precision AS longitude, 
       bedroom_count, bathroom_count, max_guests, square_meters, is_verified, created_at, updated_at
FROM properties
WHERE id = $1
`

type GetPropertyRow struct {
	ID            uuid.UUID      `json:"id"`
	OwnerID       uuid.UUID      `json:"owner_id"`
	Type          string         `json:"type"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	AddressLine1  string         `json:"address_line1"`
	AddressLine2  *string        `json:"address_line2"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	Country       string         `json:"country"`
	PostalCode    *string        `json:"postal_code"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	BedroomCount  int32          `json:"bedroom_count"`
	BathroomCount pgtype.Numeric `json:"bathroom_count"`
	MaxGuests     int32          `json:"max_guests"`
	SquareMeters  pgtype.Numeric `json:"square_meters"`
	IsVerified    bool           `json:"is_verified"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// GetProperty
//
//	SELECT id, owner_id, type, title, description, address_line1, address_line2, city, state_province, country, postal_code,
//	       (ST_Y(location::geometry))::double precision AS latitude, (ST_X(location::geometry))::double precision AS longitude,
//	       bedroom_count, bathroom_count, max_guests, square_meters, is_verified, created_at, updated_at
//	FROM properties
//	WHERE id = $1
func (q *Queries) GetProperty(ctx context.Context, id uuid.UUID) (GetPropertyRow, error) {
	row := q.db.QueryRow(ctx, getProperty, id)
	var i GetPropertyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateProvince,
		&i.Country,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.BedroomCount,
		&i.BathroomCount,
		&i.MaxGuests,
		&i.SquareMeters,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPropertyAmenities = `-- name: GetPropertyAmenities :many
SELECT id, property_id, name, category, created_at FROM property_amenities WHERE property_id = $1
`

// GetPropertyAmenities
//
//	SELECT id, property_id, name, category, created_at FROM property_amenities WHERE property_id = $1
func (q *Queries) GetPropertyAmenities(ctx context.Context, propertyID uuid.UUID) ([]PropertyAmenity, error) {
	rows, err := q.db.Query(ctx, getPropertyAmenities, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PropertyAmenity
	for rows.Next() {
		var i PropertyAmenity
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Name,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPropertyImages = `-- name: GetPropertyImages :many
SELECT id, property_id, url, display_order, is_cover, created_at FROM property_images WHERE property_id = $1 ORDER BY display_order ASC
`

// GetPropertyImages
//
//	SELECT id, property_id, url, display_order, is_cover, created_at FROM property_images WHERE property_id = $1 ORDER BY display_order ASC
func (q *Queries) GetPropertyImages(ctx context.Context, propertyID uuid.UUID) ([]PropertyImage, error) {
	rows, err := q.db.Query(ctx, getPropertyImages, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PropertyImage
	for rows.Next() {
		var i PropertyImage
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Url,
			&i.DisplayOrder,
			&i.IsCover,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRentalListingMeta = `-- name: GetRentalListingMeta :one
SELECT listing_id, cleaning_fee, security_deposit, min_nights, max_nights, check_in_time, check_out_time FROM rental_listings_meta WHERE listing_id = $1
`

// GetRentalListingMeta
//
//	SELECT listing_id, cleaning_fee, security_deposit, min_nights, max_nights, check_in_time, check_out_time FROM rental_listings_meta WHERE listing_id = $1
func (q *Queries) GetRentalListingMeta(ctx context.Context, listingID uuid.UUID) (RentalListingsMetum, error) {
	row := q.db.QueryRow(ctx, getRentalListingMeta, listingID)
	var i RentalListingsMetum
	err := row.Scan(
		&i.ListingID,
		&i.CleaningFee,
		&i.SecurityDeposit,
		&i.MinNights,
		&i.MaxNights,
		&i.CheckInTime,
		&i.CheckOutTime,
	)
	return i, err
}

const getSalesListingMeta = `-- name: GetSalesListingMeta :one
SELECT listing_id, escrow_deposit_percent, agent_commission_rate, includes_furniture, year_built, property_tax_annual FROM sales_listings_meta WHERE listing_id = $1
`

// GetSalesListingMeta
//
//	SELECT listing_id, escrow_deposit_percent, agent_commission_rate, includes_furniture, year_built, property_tax_annual FROM sales_listings_meta WHERE listing_id = $1
func (q *Queries) GetSalesListingMeta(ctx context.Context, listingID uuid.UUID) (SalesListingsMetum, error) {
	row := q.db.QueryRow(ctx, getSalesListingMeta, listingID)
	var i SalesListingsMetum
	err := row.Scan(
		&i.ListingID,
		&i.EscrowDepositPercent,
		&i.AgentCommissionRate,
		&i.IncludesFurniture,
		&i.YearBuilt,
		&i.PropertyTaxAnnual,
	)
	return i, err
}

const getViewingAppointment = `-- name: GetViewingAppointment :one
SELECT id, listing_id, client_id, host_id, scheduled_time, status, notes, created_at, updated_at FROM viewing_appointments WHERE id = $1
`

// GetViewingAppointment
//
//	SELECT id, listing_id, client_id, host_id, scheduled_time, status, notes, created_at, updated_at FROM viewing_appointments WHERE id = $1
func (q *Queries) GetViewingAppointment(ctx context.Context, id uuid.UUID) (ViewingAppointment, error) {
	row := q.db.QueryRow(ctx, getViewingAppointment, id)
	var i ViewingAppointment
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ClientID,
		&i.HostID,
		&i.ScheduledTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const scheduleViewing = `-- name: ScheduleViewing :one
INSERT INTO viewing_appointments (
    listing_id, client_id, host_id, scheduled_time, notes, status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, listing_id, client_id, host_id, scheduled_time, status, notes, created_at, updated_at
`

type ScheduleViewingParams struct {
	ListingID     uuid.UUID `json:"listing_id"`
	ClientID      uuid.UUID `json:"client_id"`
	HostID        uuid.UUID `json:"host_id"`
	ScheduledTime time.Time `json:"scheduled_time"`
	Notes         *string   `json:"notes"`
	Status        string    `json:"status"`
}

// ScheduleViewing
//
//	INSERT INTO viewing_appointments (
//	    listing_id, client_id, host_id, scheduled_time, notes, status
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6
//	) RETURNING id, listing_id, client_id, host_id, scheduled_time, status, notes, created_at, updated_at
func (q *Queries) ScheduleViewing(ctx context.Context, arg ScheduleViewingParams) (ViewingAppointment, error) {
	row := q.db.QueryRow(ctx, scheduleViewing,
		arg.ListingID,
		arg.ClientID,
		arg.HostID,
		arg.ScheduledTime,
		arg.Notes,
		arg.Status,
	)
	var i ViewingAppointment
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ClientID,
		&i.HostID,
		&i.ScheduledTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchNearbyListings = `-- name: SearchNearbyListings :many
SELECT l.id AS listing_id, l.property_id, l.type AS listing_type, l.status AS listing_status, l.base_price, l.currency, l.is_instant_book, l.created_at, l.updated_at,
       p.owner_id, p.type AS property_type, p.title, p.description, p.address_line1, p.address_line2, p.city, p.state_province, p.country, p.postal_code,
       (ST_Y(p.location::geometry))::double precision AS latitude, (ST_X(p.location::geometry))::double precision AS longitude,
       p.bedroom_count, p.bathroom_count, p.max_guests, p.square_meters, p.is_verified,
       ST_Distance(
           p.location, 
           ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography
       ) AS distance_meters
FROM properties p
JOIN listings l ON p.id = l.property_id
WHERE l.status = 'active'
  AND ST_DWithin(
      p.location, 
      ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography, 
      $3::double precision
  )
ORDER BY distance_meters ASC
LIMIT $4 OFFSET $5
`

type SearchNearbyListingsParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
	Column3 float64 `json:"column_3"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type SearchNearbyListingsRow struct {
	ListingID      uuid.UUID      `json:"listing_id"`
	PropertyID     uuid.UUID      `json:"property_id"`
	ListingType    string         `json:"listing_type"`
	ListingStatus  string         `json:"listing_status"`
	BasePrice      pgtype.Numeric `json:"base_price"`
	Currency       string         `json:"currency"`
	IsInstantBook  bool           `json:"is_instant_book"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	OwnerID        uuid.UUID      `json:"owner_id"`
	PropertyType   string         `json:"property_type"`
	Title          string         `json:"title"`
	Description    string         `json:"description"`
	AddressLine1   string         `json:"address_line1"`
	AddressLine2   *string        `json:"address_line2"`
	City           string         `json:"city"`
	StateProvince  string         `json:"state_province"`
	Country        string         `json:"country"`
	PostalCode     *string        `json:"postal_code"`
	Latitude       float64        `json:"latitude"`
	Longitude      float64        `json:"longitude"`
	BedroomCount   int32          `json:"bedroom_count"`
	BathroomCount  pgtype.Numeric `json:"bathroom_count"`
	MaxGuests      int32          `json:"max_guests"`
	SquareMeters   pgtype.Numeric `json:"square_meters"`
	IsVerified     bool           `json:"is_verified"`
	DistanceMeters interface{}    `json:"distance_meters"`
}

// SearchNearbyListings
//
//	SELECT l.id AS listing_id, l.property_id, l.type AS listing_type, l.status AS listing_status, l.base_price, l.currency, l.is_instant_book, l.created_at, l.updated_at,
//	       p.owner_id, p.type AS property_type, p.title, p.description, p.address_line1, p.address_line2, p.city, p.state_province, p.country, p.postal_code,
//	       (ST_Y(p.location::geometry))::double precision AS latitude, (ST_X(p.location::geometry))::double precision AS longitude,
//	       p.bedroom_count, p.bathroom_count, p.max_guests, p.square_meters, p.is_verified,
//	       ST_Distance(
//	           p.location,
//	           ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography
//	       ) AS distance_meters
//	FROM properties p
//	JOIN listings l ON p.id = l.property_id
//	WHERE l.status = 'active'
//	  AND ST_DWithin(
//	      p.location,
//	      ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography,
//	      $3::double precision
//	  )
//	ORDER BY distance_meters ASC
//	LIMIT $4 OFFSET $5
func (q *Queries) SearchNearbyListings(ctx context.Context, arg SearchNearbyListingsParams) ([]SearchNearbyListingsRow, error) {
	rows, err := q.db.Query(ctx, searchNearbyListings,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNearbyListingsRow
	for rows.Next() {
		var i SearchNearbyListingsRow
		if err := rows.Scan(
			&i.ListingID,
			&i.PropertyID,
			&i.ListingType,
			&i.ListingStatus,
			&i.BasePrice,
			&i.Currency,
			&i.IsInstantBook,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.PropertyType,
			&i.Title,
			&i.Description,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.StateProvince,
			&i.Country,
			&i.PostalCode,
			&i.Latitude,
			&i.Longitude,
			&i.BedroomCount,
			&i.BathroomCount,
			&i.MaxGuests,
			&i.SquareMeters,
			&i.IsVerified,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOfferStatus = `-- name: UpdateOfferStatus :one
UPDATE sales_offers
SET status = $2, escrow_deposit_paid = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date, created_at, updated_at
`

type UpdateOfferStatusParams struct {
	ID                uuid.UUID      `json:"id"`
	Status            string         `json:"status"`
	EscrowDepositPaid pgtype.Numeric `json:"escrow_deposit_paid"`
}

// UpdateOfferStatus
//
//	UPDATE sales_offers
//	SET status = $2, escrow_deposit_paid = $3, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, listing_id, buyer_id, offer_price, escrow_deposit_paid, status, conditions_text, expiration_date, created_at, updated_at
func (q *Queries) UpdateOfferStatus(ctx context.Context, arg UpdateOfferStatusParams) (SalesOffer, error) {
	row := q.db.QueryRow(ctx, updateOfferStatus, arg.ID, arg.Status, arg.EscrowDepositPaid)
	var i SalesOffer
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.OfferPrice,
		&i.EscrowDepositPaid,
		&i.Status,
		&i.ConditionsText,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
