// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CarrierType string

const (
	CarrierTypeCrowdsourced CarrierType = "crowdsourced"
	CarrierType3pl          CarrierType = "3pl"
)

func (e *CarrierType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CarrierType(s)
	case string:
		*e = CarrierType(s)
	default:
		return fmt.Errorf("unsupported scan type for CarrierType: %T", src)
	}
	return nil
}

type NullCarrierType struct {
	CarrierType CarrierType `json:"carrier_type"`
	Valid       bool        `json:"valid"` // Valid is true if CarrierType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCarrierType) Scan(value interface{}) error {
	if value == nil {
		ns.CarrierType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CarrierType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCarrierType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CarrierType), nil
}

type CourierStatus string

const (
	CourierStatusPending   CourierStatus = "pending"
	CourierStatusApproved  CourierStatus = "approved"
	CourierStatusRejected  CourierStatus = "rejected"
	CourierStatusSuspended CourierStatus = "suspended"
)

func (e *CourierStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourierStatus(s)
	case string:
		*e = CourierStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CourierStatus: %T", src)
	}
	return nil
}

type NullCourierStatus struct {
	CourierStatus CourierStatus `json:"courier_status"`
	Valid         bool          `json:"valid"` // Valid is true if CourierStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourierStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CourierStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourierStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourierStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourierStatus), nil
}

type DeliveryStatus string

const (
	DeliveryStatusCreated          DeliveryStatus = "created"
	DeliveryStatusAssigned         DeliveryStatus = "assigned"
	DeliveryStatusAwaitingPickup   DeliveryStatus = "awaiting_pickup"
	DeliveryStatusPickedUp         DeliveryStatus = "picked_up"
	DeliveryStatusInTransit        DeliveryStatus = "in_transit"
	DeliveryStatusArrivedAtStation DeliveryStatus = "arrived_at_station"
	DeliveryStatusOutForDelivery   DeliveryStatus = "out_for_delivery"
	DeliveryStatusDelivered        DeliveryStatus = "delivered"
	DeliveryStatusFailed           DeliveryStatus = "failed"
	DeliveryStatusReturned         DeliveryStatus = "returned"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type DeliveryType string

const (
	DeliveryTypeDoorToDoor       DeliveryType = "door_to_door"
	DeliveryTypeStationToDoor    DeliveryType = "station_to_door"
	DeliveryTypeDoorToStation    DeliveryType = "door_to_station"
	DeliveryTypeStationToStation DeliveryType = "station_to_station"
)

func (e *DeliveryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryType(s)
	case string:
		*e = DeliveryType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryType: %T", src)
	}
	return nil
}

type NullDeliveryType struct {
	DeliveryType DeliveryType `json:"delivery_type"`
	Valid        bool         `json:"valid"` // Valid is true if DeliveryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryType) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryType), nil
}

type StationPackageDirection string

const (
	StationPackageDirectionInboundForBuyer    StationPackageDirection = "inbound_for_buyer"
	StationPackageDirectionOutboundForCourier StationPackageDirection = "outbound_for_courier"
)

func (e *StationPackageDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StationPackageDirection(s)
	case string:
		*e = StationPackageDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for StationPackageDirection: %T", src)
	}
	return nil
}

type NullStationPackageDirection struct {
	StationPackageDirection StationPackageDirection `json:"station_package_direction"`
	Valid                   bool                    `json:"valid"` // Valid is true if StationPackageDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStationPackageDirection) Scan(value interface{}) error {
	if value == nil {
		ns.StationPackageDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StationPackageDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStationPackageDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StationPackageDirection), nil
}

type StationStatus string

const (
	StationStatusPending   StationStatus = "pending"
	StationStatusActive    StationStatus = "active"
	StationStatusSuspended StationStatus = "suspended"
)

func (e *StationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StationStatus(s)
	case string:
		*e = StationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StationStatus: %T", src)
	}
	return nil
}

type NullStationStatus struct {
	StationStatus StationStatus `json:"station_status"`
	Valid         bool          `json:"valid"` // Valid is true if StationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StationStatus), nil
}

type Courier struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	VehicleType        string         `json:"vehicle_type"`
	PlateNumber        *string        `json:"plate_number"`
	IsOnline           bool           `json:"is_online"`
	VerificationStatus string         `json:"verification_status"`
	Rating             pgtype.Numeric `json:"rating"`
	CurrentLocation    interface{}    `json:"current_location"`
	WalletBalance      pgtype.Numeric `json:"wallet_balance"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type CourierTask struct {
	ID              uuid.UUID  `json:"id"`
	DeliveryOrderID uuid.UUID  `json:"delivery_order_id"`
	CourierID       uuid.UUID  `json:"courier_id"`
	Status          string     `json:"status"`
	OfferedAt       time.Time  `json:"offered_at"`
	RespondedAt     *time.Time `json:"responded_at"`
}

type DeliveryOrder struct {
	ID                    uuid.UUID      `json:"id"`
	TrackingNumber        string         `json:"tracking_number"`
	OrderID               *uuid.UUID     `json:"order_id"`
	SenderType            string         `json:"sender_type"`
	SenderID              uuid.UUID      `json:"sender_id"`
	SenderName            string         `json:"sender_name"`
	SenderPhone           string         `json:"sender_phone"`
	SenderAddressLine1    string         `json:"sender_address_line1"`
	SenderCity            string         `json:"sender_city"`
	SenderCountry         string         `json:"sender_country"`
	SenderLocation        string         `json:"sender_location"`
	RecipientName         string         `json:"recipient_name"`
	RecipientPhone        string         `json:"recipient_phone"`
	RecipientAddressLine1 string         `json:"recipient_address_line1"`
	RecipientCity         string         `json:"recipient_city"`
	RecipientCountry      string         `json:"recipient_country"`
	RecipientLocation     string         `json:"recipient_location"`
	DeliveryType          string         `json:"delivery_type"`
	OriginStationID       *uuid.UUID     `json:"origin_station_id"`
	DestinationStationID  *uuid.UUID     `json:"destination_station_id"`
	CarrierType           *CarrierType   `json:"carrier_type"`
	CarrierPartnerID      *uuid.UUID     `json:"carrier_partner_id"`
	CarrierCourierID      *uuid.UUID     `json:"carrier_courier_id"`
	ExternalTrackingNo    *string        `json:"external_tracking_no"`
	WeightKg              pgtype.Numeric `json:"weight_kg"`
	DimensionsCm          []byte         `json:"dimensions_cm"`
	ShippingFee           pgtype.Numeric `json:"shipping_fee"`
	PaymentStatus         string         `json:"payment_status"`
	Status                string         `json:"status"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	PickedUpAt            *time.Time     `json:"picked_up_at"`
	DeliveredAt           *time.Time     `json:"delivered_at"`
}

type LogisticsPartner struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Code          string    `json:"code"`
	ApiEndpoint   string    `json:"api_endpoint"`
	ApiKey        string    `json:"api_key"`
	IsActive      bool      `json:"is_active"`
	PricingSchema []byte    `json:"pricing_schema"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Station struct {
	ID                  uuid.UUID `json:"id"`
	KeeperUserID        uuid.UUID `json:"keeper_user_id"`
	Name                string    `json:"name"`
	StoreType           string    `json:"store_type"`
	Phone               string    `json:"phone"`
	AddressLine1        string    `json:"address_line1"`
	City                string    `json:"city"`
	Country             string    `json:"country"`
	Location            string    `json:"location"`
	Status              string    `json:"status"`
	CapacityPackages    int32     `json:"capacity_packages"`
	CurrentPackageCount int32     `json:"current_package_count"`
	OperatingHours      []byte    `json:"operating_hours"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type StationPackage struct {
	ID               uuid.UUID  `json:"id"`
	StationID        uuid.UUID  `json:"station_id"`
	DeliveryOrderID  uuid.UUID  `json:"delivery_order_id"`
	Direction        string     `json:"direction"`
	ShelfCode        string     `json:"shelf_code"`
	VerificationCode string     `json:"verification_code"`
	CheckInAt        time.Time  `json:"check_in_at"`
	CheckInBy        uuid.UUID  `json:"check_in_by"`
	CheckOutAt       *time.Time `json:"check_out_at"`
	CheckOutBy       *uuid.UUID `json:"check_out_by"`
	CreatedAt        time.Time  `json:"created_at"`
}

type TrackingLog struct {
	ID              uuid.UUID   `json:"id"`
	DeliveryOrderID uuid.UUID   `json:"delivery_order_id"`
	Status          string      `json:"status"`
	LocationDesc    string      `json:"location_desc"`
	Coordinate      interface{} `json:"coordinate"`
	Details         *string     `json:"details"`
	OperatorID      *uuid.UUID  `json:"operator_id"`
	CreatedAt       time.Time   `json:"created_at"`
}
