// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignCarrierToDeliveryOrder = `-- name: AssignCarrierToDeliveryOrder :one
UPDATE delivery_orders
SET carrier_type = $2, carrier_partner_id = $3, carrier_courier_id = $4, external_tracking_no = $5, status = 'assigned', updated_at = NOW()
WHERE id = $1
RETURNING id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at
`

type AssignCarrierToDeliveryOrderParams struct {
	ID                 uuid.UUID    `json:"id"`
	CarrierType        *CarrierType `json:"carrier_type"`
	CarrierPartnerID   *uuid.UUID   `json:"carrier_partner_id"`
	CarrierCourierID   *uuid.UUID   `json:"carrier_courier_id"`
	ExternalTrackingNo *string      `json:"external_tracking_no"`
}

// AssignCarrierToDeliveryOrder
//
//	UPDATE delivery_orders
//	SET carrier_type = $2, carrier_partner_id = $3, carrier_courier_id = $4, external_tracking_no = $5, status = 'assigned', updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at
func (q *Queries) AssignCarrierToDeliveryOrder(ctx context.Context, arg AssignCarrierToDeliveryOrderParams) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, assignCarrierToDeliveryOrder,
		arg.ID,
		arg.CarrierType,
		arg.CarrierPartnerID,
		arg.CarrierCourierID,
		arg.ExternalTrackingNo,
	)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.OrderID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.SenderPhone,
		&i.SenderAddressLine1,
		&i.SenderCity,
		&i.SenderCountry,
		&i.SenderLocation,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientAddressLine1,
		&i.RecipientCity,
		&i.RecipientCountry,
		&i.RecipientLocation,
		&i.DeliveryType,
		&i.OriginStationID,
		&i.DestinationStationID,
		&i.CarrierType,
		&i.CarrierPartnerID,
		&i.CarrierCourierID,
		&i.ExternalTrackingNo,
		&i.WeightKg,
		&i.DimensionsCm,
		&i.ShippingFee,
		&i.PaymentStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
	)
	return i, err
}

const checkInStationPackage = `-- name: CheckInStationPackage :one
INSERT INTO station_packages (station_id, delivery_order_id, direction, shelf_code, verification_code, check_in_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, station_id, delivery_order_id, direction, shelf_code, verification_code, check_in_at, check_in_by, check_out_at, check_out_by, created_at
`

type CheckInStationPackageParams struct {
	StationID        uuid.UUID `json:"station_id"`
	DeliveryOrderID  uuid.UUID `json:"delivery_order_id"`
	Direction        string    `json:"direction"`
	ShelfCode        string    `json:"shelf_code"`
	VerificationCode string    `json:"verification_code"`
	CheckInBy        uuid.UUID `json:"check_in_by"`
}

// CheckInStationPackage
//
//	INSERT INTO station_packages (station_id, delivery_order_id, direction, shelf_code, verification_code, check_in_by)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	RETURNING id, station_id, delivery_order_id, direction, shelf_code, verification_code, check_in_at, check_in_by, check_out_at, check_out_by, created_at
func (q *Queries) CheckInStationPackage(ctx context.Context, arg CheckInStationPackageParams) (StationPackage, error) {
	row := q.db.QueryRow(ctx, checkInStationPackage,
		arg.StationID,
		arg.DeliveryOrderID,
		arg.Direction,
		arg.ShelfCode,
		arg.VerificationCode,
		arg.CheckInBy,
	)
	var i StationPackage
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.DeliveryOrderID,
		&i.Direction,
		&i.ShelfCode,
		&i.VerificationCode,
		&i.CheckInAt,
		&i.CheckInBy,
		&i.CheckOutAt,
		&i.CheckOutBy,
		&i.CreatedAt,
	)
	return i, err
}

const checkOutStationPackage = `-- name: CheckOutStationPackage :one
UPDATE station_packages
SET check_out_at = NOW(), check_out_by = $2
WHERE delivery_order_id = $1 AND check_out_at IS NULL
RETURNING id, station_id, delivery_order_id, direction, shelf_code, verification_code, check_in_at, check_in_by, check_out_at, check_out_by, created_at
`

type CheckOutStationPackageParams struct {
	DeliveryOrderID uuid.UUID  `json:"delivery_order_id"`
	CheckOutBy      *uuid.UUID `json:"check_out_by"`
}

// CheckOutStationPackage
//
//	UPDATE station_packages
//	SET check_out_at = NOW(), check_out_by = $2
//	WHERE delivery_order_id = $1 AND check_out_at IS NULL
//	RETURNING id, station_id, delivery_order_id, direction, shelf_code, verification_code, check_in_at, check_in_by, check_out_at, check_out_by, created_at
func (q *Queries) CheckOutStationPackage(ctx context.Context, arg CheckOutStationPackageParams) (StationPackage, error) {
	row := q.db.QueryRow(ctx, checkOutStationPackage, arg.DeliveryOrderID, arg.CheckOutBy)
	var i StationPackage
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.DeliveryOrderID,
		&i.Direction,
		&i.ShelfCode,
		&i.VerificationCode,
		&i.CheckInAt,
		&i.CheckInBy,
		&i.CheckOutAt,
		&i.CheckOutBy,
		&i.CreatedAt,
	)
	return i, err
}

const createCourier = `-- name: CreateCourier :one
INSERT INTO couriers (user_id, vehicle_type, plate_number, is_online, verification_status, rating)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at
`

type CreateCourierParams struct {
	UserID             uuid.UUID      `json:"user_id"`
	VehicleType        string         `json:"vehicle_type"`
	PlateNumber        *string        `json:"plate_number"`
	IsOnline           bool           `json:"is_online"`
	VerificationStatus string         `json:"verification_status"`
	Rating             pgtype.Numeric `json:"rating"`
}

// CreateCourier
//
//	INSERT INTO couriers (user_id, vehicle_type, plate_number, is_online, verification_status, rating)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	RETURNING id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at
func (q *Queries) CreateCourier(ctx context.Context, arg CreateCourierParams) (Courier, error) {
	row := q.db.QueryRow(ctx, createCourier,
		arg.UserID,
		arg.VehicleType,
		arg.PlateNumber,
		arg.IsOnline,
		arg.VerificationStatus,
		arg.Rating,
	)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleType,
		&i.PlateNumber,
		&i.IsOnline,
		&i.VerificationStatus,
		&i.Rating,
		&i.CurrentLocation,
		&i.WalletBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCourierTask = `-- name: CreateCourierTask :one
INSERT INTO courier_tasks (delivery_order_id, courier_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (delivery_order_id, courier_id) DO UPDATE
SET status = EXCLUDED.status, responded_at = CASE WHEN EXCLUDED.status != 'offered' THEN NOW() ELSE responded_at END
RETURNING id, delivery_order_id, courier_id, status, offered_at, responded_at
`

type CreateCourierTaskParams struct {
	DeliveryOrderID uuid.UUID `json:"delivery_order_id"`
	CourierID       uuid.UUID `json:"courier_id"`
	Status          string    `json:"status"`
}

// CreateCourierTask
//
//	INSERT INTO courier_tasks (delivery_order_id, courier_id, status)
//	VALUES ($1, $2, $3)
//	ON CONFLICT (delivery_order_id, courier_id) DO UPDATE
//	SET status = EXCLUDED.status, responded_at = CASE WHEN EXCLUDED.status != 'offered' THEN NOW() ELSE responded_at END
//	RETURNING id, delivery_order_id, courier_id, status, offered_at, responded_at
func (q *Queries) CreateCourierTask(ctx context.Context, arg CreateCourierTaskParams) (CourierTask, error) {
	row := q.db.QueryRow(ctx, createCourierTask, arg.DeliveryOrderID, arg.CourierID, arg.Status)
	var i CourierTask
	err := row.Scan(
		&i.ID,
		&i.DeliveryOrderID,
		&i.CourierID,
		&i.Status,
		&i.OfferedAt,
		&i.RespondedAt,
	)
	return i, err
}

const createDeliveryOrder = `-- name: CreateDeliveryOrder :one
INSERT INTO delivery_orders (
    tracking_number, order_id, sender_type, sender_id,
    sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location,
    recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location,
    delivery_type, origin_station_id, destination_station_id, weight_kg, dimensions_cm, shipping_fee, payment_status, status
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, ST_SetSRID(ST_MakePoint($10, $11), 4326),
    $12, $13, $14, $15, $16, ST_SetSRID(ST_MakePoint($17, $18), 4326),
    $19, $20, $21, $22, $23, $24, $25, $26
)
RETURNING id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at
`

type CreateDeliveryOrderParams struct {
	TrackingNumber        string         `json:"tracking_number"`
	OrderID               *uuid.UUID     `json:"order_id"`
	SenderType            string         `json:"sender_type"`
	SenderID              uuid.UUID      `json:"sender_id"`
	SenderName            string         `json:"sender_name"`
	SenderPhone           string         `json:"sender_phone"`
	SenderAddressLine1    string         `json:"sender_address_line1"`
	SenderCity            string         `json:"sender_city"`
	SenderCountry         string         `json:"sender_country"`
	StMakepoint           interface{}    `json:"st_makepoint"`
	StMakepoint_2         interface{}    `json:"st_makepoint_2"`
	RecipientName         string         `json:"recipient_name"`
	RecipientPhone        string         `json:"recipient_phone"`
	RecipientAddressLine1 string         `json:"recipient_address_line1"`
	RecipientCity         string         `json:"recipient_city"`
	RecipientCountry      string         `json:"recipient_country"`
	StMakepoint_3         interface{}    `json:"st_makepoint_3"`
	StMakepoint_4         interface{}    `json:"st_makepoint_4"`
	DeliveryType          string         `json:"delivery_type"`
	OriginStationID       *uuid.UUID     `json:"origin_station_id"`
	DestinationStationID  *uuid.UUID     `json:"destination_station_id"`
	WeightKg              pgtype.Numeric `json:"weight_kg"`
	DimensionsCm          []byte         `json:"dimensions_cm"`
	ShippingFee           pgtype.Numeric `json:"shipping_fee"`
	PaymentStatus         string         `json:"payment_status"`
	Status                string         `json:"status"`
}

// CreateDeliveryOrder
//
//	INSERT INTO delivery_orders (
//	    tracking_number, order_id, sender_type, sender_id,
//	    sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location,
//	    recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location,
//	    delivery_type, origin_station_id, destination_station_id, weight_kg, dimensions_cm, shipping_fee, payment_status, status
//	)
//	VALUES (
//	    $1, $2, $3, $4,
//	    $5, $6, $7, $8, $9, ST_SetSRID(ST_MakePoint($10, $11), 4326),
//	    $12, $13, $14, $15, $16, ST_SetSRID(ST_MakePoint($17, $18), 4326),
//	    $19, $20, $21, $22, $23, $24, $25, $26
//	)
//	RETURNING id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at
func (q *Queries) CreateDeliveryOrder(ctx context.Context, arg CreateDeliveryOrderParams) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, createDeliveryOrder,
		arg.TrackingNumber,
		arg.OrderID,
		arg.SenderType,
		arg.SenderID,
		arg.SenderName,
		arg.SenderPhone,
		arg.SenderAddressLine1,
		arg.SenderCity,
		arg.SenderCountry,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.RecipientAddressLine1,
		arg.RecipientCity,
		arg.RecipientCountry,
		arg.StMakepoint_3,
		arg.StMakepoint_4,
		arg.DeliveryType,
		arg.OriginStationID,
		arg.DestinationStationID,
		arg.WeightKg,
		arg.DimensionsCm,
		arg.ShippingFee,
		arg.PaymentStatus,
		arg.Status,
	)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.OrderID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.SenderPhone,
		&i.SenderAddressLine1,
		&i.SenderCity,
		&i.SenderCountry,
		&i.SenderLocation,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientAddressLine1,
		&i.RecipientCity,
		&i.RecipientCountry,
		&i.RecipientLocation,
		&i.DeliveryType,
		&i.OriginStationID,
		&i.DestinationStationID,
		&i.CarrierType,
		&i.CarrierPartnerID,
		&i.CarrierCourierID,
		&i.ExternalTrackingNo,
		&i.WeightKg,
		&i.DimensionsCm,
		&i.ShippingFee,
		&i.PaymentStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
	)
	return i, err
}

const createStation = `-- name: CreateStation :one
INSERT INTO stations (keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, operating_hours)
VALUES ($1, $2, $3, $4, $5, $6, $7, ST_SetSRID(ST_MakePoint($8, $9), 4326), $10, $11, $12)
RETURNING id, keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, current_package_count, operating_hours, created_at, updated_at
`

type CreateStationParams struct {
	KeeperUserID     uuid.UUID   `json:"keeper_user_id"`
	Name             string      `json:"name"`
	StoreType        string      `json:"store_type"`
	Phone            string      `json:"phone"`
	AddressLine1     string      `json:"address_line1"`
	City             string      `json:"city"`
	Country          string      `json:"country"`
	StMakepoint      interface{} `json:"st_makepoint"`
	StMakepoint_2    interface{} `json:"st_makepoint_2"`
	Status           string      `json:"status"`
	CapacityPackages int32       `json:"capacity_packages"`
	OperatingHours   []byte      `json:"operating_hours"`
}

// CreateStation
//
//	INSERT INTO stations (keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, operating_hours)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, ST_SetSRID(ST_MakePoint($8, $9), 4326), $10, $11, $12)
//	RETURNING id, keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, current_package_count, operating_hours, created_at, updated_at
func (q *Queries) CreateStation(ctx context.Context, arg CreateStationParams) (Station, error) {
	row := q.db.QueryRow(ctx, createStation,
		arg.KeeperUserID,
		arg.Name,
		arg.StoreType,
		arg.Phone,
		arg.AddressLine1,
		arg.City,
		arg.Country,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.Status,
		arg.CapacityPackages,
		arg.OperatingHours,
	)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.KeeperUserID,
		&i.Name,
		&i.StoreType,
		&i.Phone,
		&i.AddressLine1,
		&i.City,
		&i.Country,
		&i.Location,
		&i.Status,
		&i.CapacityPackages,
		&i.CurrentPackageCount,
		&i.OperatingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrackingLog = `-- name: CreateTrackingLog :one
INSERT INTO tracking_logs (delivery_order_id, status, location_desc, coordinate, details, operator_id)
VALUES ($1, $2, $3, CASE WHEN $4::double precision IS NOT NULL AND $5::double precision IS NOT NULL THEN ST_SetSRID(ST_MakePoint($4, $5), 4326) ELSE NULL END, $6, $7)
RETURNING id, delivery_order_id, status, location_desc, coordinate, details, operator_id, created_at
`

type CreateTrackingLogParams struct {
	DeliveryOrderID uuid.UUID  `json:"delivery_order_id"`
	Status          string     `json:"status"`
	LocationDesc    string     `json:"location_desc"`
	Column4         float64    `json:"column_4"`
	Column5         float64    `json:"column_5"`
	Details         *string    `json:"details"`
	OperatorID      *uuid.UUID `json:"operator_id"`
}

// CreateTrackingLog
//
//	INSERT INTO tracking_logs (delivery_order_id, status, location_desc, coordinate, details, operator_id)
//	VALUES ($1, $2, $3, CASE WHEN $4::double precision IS NOT NULL AND $5::double precision IS NOT NULL THEN ST_SetSRID(ST_MakePoint($4, $5), 4326) ELSE NULL END, $6, $7)
//	RETURNING id, delivery_order_id, status, location_desc, coordinate, details, operator_id, created_at
func (q *Queries) CreateTrackingLog(ctx context.Context, arg CreateTrackingLogParams) (TrackingLog, error) {
	row := q.db.QueryRow(ctx, createTrackingLog,
		arg.DeliveryOrderID,
		arg.Status,
		arg.LocationDesc,
		arg.Column4,
		arg.Column5,
		arg.Details,
		arg.OperatorID,
	)
	var i TrackingLog
	err := row.Scan(
		&i.ID,
		&i.DeliveryOrderID,
		&i.Status,
		&i.LocationDesc,
		&i.Coordinate,
		&i.Details,
		&i.OperatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveCouriersNearLocation = `-- name: GetActiveCouriersNearLocation :many
SELECT id, user_id, vehicle_type, plate_number, rating, ST_Distance(current_location, ST_SetSRID(ST_MakePoint($1, $2), 4326)) AS distance
FROM couriers
WHERE is_online = TRUE AND verification_status = 'approved' AND current_location IS NOT NULL
ORDER BY current_location <-> ST_SetSRID(ST_MakePoint($1, $2), 4326)
LIMIT $3
`

type GetActiveCouriersNearLocationParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	Limit         int32       `json:"limit"`
}

type GetActiveCouriersNearLocationRow struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	VehicleType string         `json:"vehicle_type"`
	PlateNumber *string        `json:"plate_number"`
	Rating      pgtype.Numeric `json:"rating"`
	Distance    interface{}    `json:"distance"`
}

// GetActiveCouriersNearLocation
//
//	SELECT id, user_id, vehicle_type, plate_number, rating, ST_Distance(current_location, ST_SetSRID(ST_MakePoint($1, $2), 4326)) AS distance
//	FROM couriers
//	WHERE is_online = TRUE AND verification_status = 'approved' AND current_location IS NOT NULL
//	ORDER BY current_location <-> ST_SetSRID(ST_MakePoint($1, $2), 4326)
//	LIMIT $3
func (q *Queries) GetActiveCouriersNearLocation(ctx context.Context, arg GetActiveCouriersNearLocationParams) ([]GetActiveCouriersNearLocationRow, error) {
	rows, err := q.db.Query(ctx, getActiveCouriersNearLocation, arg.StMakepoint, arg.StMakepoint_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveCouriersNearLocationRow
	for rows.Next() {
		var i GetActiveCouriersNearLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleType,
			&i.PlateNumber,
			&i.Rating,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableCourierTasks = `-- name: GetAvailableCourierTasks :many
SELECT dor.id, dor.tracking_number, dor.order_id, dor.sender_type, dor.sender_id, dor.sender_name, dor.sender_phone, dor.sender_address_line1, dor.sender_city, dor.sender_country, dor.sender_location, dor.recipient_name, dor.recipient_phone, dor.recipient_address_line1, dor.recipient_city, dor.recipient_country, dor.recipient_location, dor.delivery_type, dor.origin_station_id, dor.destination_station_id, dor.carrier_type, dor.carrier_partner_id, dor.carrier_courier_id, dor.external_tracking_no, dor.weight_kg, dor.dimensions_cm, dor.shipping_fee, dor.payment_status, dor.status, dor.created_at, dor.updated_at, dor.picked_up_at, dor.delivered_at
FROM delivery_orders dor
JOIN courier_tasks ct ON dor.id = ct.delivery_order_id
WHERE ct.courier_id = $1 AND ct.status = 'offered' AND dor.status = 'assigned'
`

// GetAvailableCourierTasks
//
//	SELECT dor.id, dor.tracking_number, dor.order_id, dor.sender_type, dor.sender_id, dor.sender_name, dor.sender_phone, dor.sender_address_line1, dor.sender_city, dor.sender_country, dor.sender_location, dor.recipient_name, dor.recipient_phone, dor.recipient_address_line1, dor.recipient_city, dor.recipient_country, dor.recipient_location, dor.delivery_type, dor.origin_station_id, dor.destination_station_id, dor.carrier_type, dor.carrier_partner_id, dor.carrier_courier_id, dor.external_tracking_no, dor.weight_kg, dor.dimensions_cm, dor.shipping_fee, dor.payment_status, dor.status, dor.created_at, dor.updated_at, dor.picked_up_at, dor.delivered_at
//	FROM delivery_orders dor
//	JOIN courier_tasks ct ON dor.id = ct.delivery_order_id
//	WHERE ct.courier_id = $1 AND ct.status = 'offered' AND dor.status = 'assigned'
func (q *Queries) GetAvailableCourierTasks(ctx context.Context, courierID uuid.UUID) ([]DeliveryOrder, error) {
	rows, err := q.db.Query(ctx, getAvailableCourierTasks, courierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryOrder
	for rows.Next() {
		var i DeliveryOrder
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.OrderID,
			&i.SenderType,
			&i.SenderID,
			&i.SenderName,
			&i.SenderPhone,
			&i.SenderAddressLine1,
			&i.SenderCity,
			&i.SenderCountry,
			&i.SenderLocation,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.RecipientAddressLine1,
			&i.RecipientCity,
			&i.RecipientCountry,
			&i.RecipientLocation,
			&i.DeliveryType,
			&i.OriginStationID,
			&i.DestinationStationID,
			&i.CarrierType,
			&i.CarrierPartnerID,
			&i.CarrierCourierID,
			&i.ExternalTrackingNo,
			&i.WeightKg,
			&i.DimensionsCm,
			&i.ShippingFee,
			&i.PaymentStatus,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourierByUserID = `-- name: GetCourierByUserID :one
SELECT id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at FROM couriers
WHERE user_id = $1
`

// GetCourierByUserID
//
//	SELECT id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at FROM couriers
//	WHERE user_id = $1
func (q *Queries) GetCourierByUserID(ctx context.Context, userID uuid.UUID) (Courier, error) {
	row := q.db.QueryRow(ctx, getCourierByUserID, userID)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleType,
		&i.PlateNumber,
		&i.IsOnline,
		&i.VerificationStatus,
		&i.Rating,
		&i.CurrentLocation,
		&i.WalletBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourierTask = `-- name: GetCourierTask :one
SELECT id, delivery_order_id, courier_id, status, offered_at, responded_at FROM courier_tasks
WHERE delivery_order_id = $1 AND courier_id = $2
`

type GetCourierTaskParams struct {
	DeliveryOrderID uuid.UUID `json:"delivery_order_id"`
	CourierID       uuid.UUID `json:"courier_id"`
}

// GetCourierTask
//
//	SELECT id, delivery_order_id, courier_id, status, offered_at, responded_at FROM courier_tasks
//	WHERE delivery_order_id = $1 AND courier_id = $2
func (q *Queries) GetCourierTask(ctx context.Context, arg GetCourierTaskParams) (CourierTask, error) {
	row := q.db.QueryRow(ctx, getCourierTask, arg.DeliveryOrderID, arg.CourierID)
	var i CourierTask
	err := row.Scan(
		&i.ID,
		&i.DeliveryOrderID,
		&i.CourierID,
		&i.Status,
		&i.OfferedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getDeliveryOrder = `-- name: GetDeliveryOrder :one
SELECT id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at FROM delivery_orders
WHERE id = $1
`

// GetDeliveryOrder
//
//	SELECT id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at FROM delivery_orders
//	WHERE id = $1
func (q *Queries) GetDeliveryOrder(ctx context.Context, id uuid.UUID) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, getDeliveryOrder, id)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.OrderID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.SenderPhone,
		&i.SenderAddressLine1,
		&i.SenderCity,
		&i.SenderCountry,
		&i.SenderLocation,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientAddressLine1,
		&i.RecipientCity,
		&i.RecipientCountry,
		&i.RecipientLocation,
		&i.DeliveryType,
		&i.OriginStationID,
		&i.DestinationStationID,
		&i.CarrierType,
		&i.CarrierPartnerID,
		&i.CarrierCourierID,
		&i.ExternalTrackingNo,
		&i.WeightKg,
		&i.DimensionsCm,
		&i.ShippingFee,
		&i.PaymentStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getDeliveryOrderByOrderID = `-- name: GetDeliveryOrderByOrderID :one
SELECT id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at FROM delivery_orders
WHERE order_id = $1
`

// GetDeliveryOrderByOrderID
//
//	SELECT id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at FROM delivery_orders
//	WHERE order_id = $1
func (q *Queries) GetDeliveryOrderByOrderID(ctx context.Context, orderID *uuid.UUID) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, getDeliveryOrderByOrderID, orderID)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.OrderID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.SenderPhone,
		&i.SenderAddressLine1,
		&i.SenderCity,
		&i.SenderCountry,
		&i.SenderLocation,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientAddressLine1,
		&i.RecipientCity,
		&i.RecipientCountry,
		&i.RecipientLocation,
		&i.DeliveryType,
		&i.OriginStationID,
		&i.DestinationStationID,
		&i.CarrierType,
		&i.CarrierPartnerID,
		&i.CarrierCourierID,
		&i.ExternalTrackingNo,
		&i.WeightKg,
		&i.DimensionsCm,
		&i.ShippingFee,
		&i.PaymentStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getDeliveryOrderByTrackingNumber = `-- name: GetDeliveryOrderByTrackingNumber :one
SELECT id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at FROM delivery_orders
WHERE tracking_number = $1
`

// GetDeliveryOrderByTrackingNumber
//
//	SELECT id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at FROM delivery_orders
//	WHERE tracking_number = $1
func (q *Queries) GetDeliveryOrderByTrackingNumber(ctx context.Context, trackingNumber string) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, getDeliveryOrderByTrackingNumber, trackingNumber)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.OrderID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.SenderPhone,
		&i.SenderAddressLine1,
		&i.SenderCity,
		&i.SenderCountry,
		&i.SenderLocation,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientAddressLine1,
		&i.RecipientCity,
		&i.RecipientCountry,
		&i.RecipientLocation,
		&i.DeliveryType,
		&i.OriginStationID,
		&i.DestinationStationID,
		&i.CarrierType,
		&i.CarrierPartnerID,
		&i.CarrierCourierID,
		&i.ExternalTrackingNo,
		&i.WeightKg,
		&i.DimensionsCm,
		&i.ShippingFee,
		&i.PaymentStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getStation = `-- name: GetStation :one
SELECT id, keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, current_package_count, operating_hours, created_at, updated_at FROM stations
WHERE id = $1
`

// GetStation
//
//	SELECT id, keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, current_package_count, operating_hours, created_at, updated_at FROM stations
//	WHERE id = $1
func (q *Queries) GetStation(ctx context.Context, id uuid.UUID) (Station, error) {
	row := q.db.QueryRow(ctx, getStation, id)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.KeeperUserID,
		&i.Name,
		&i.StoreType,
		&i.Phone,
		&i.AddressLine1,
		&i.City,
		&i.Country,
		&i.Location,
		&i.Status,
		&i.CapacityPackages,
		&i.CurrentPackageCount,
		&i.OperatingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStationInventory = `-- name: GetStationInventory :many
SELECT sp.id, sp.station_id, sp.delivery_order_id, sp.direction, sp.shelf_code, sp.verification_code, sp.check_in_at, sp.check_in_by, sp.check_out_at, sp.check_out_by, sp.created_at, dor.tracking_number, dor.recipient_name, dor.recipient_phone
FROM station_packages sp
JOIN delivery_orders dor ON sp.delivery_order_id = dor.id
WHERE sp.station_id = $1 AND (($2::boolean = TRUE AND sp.check_out_at IS NULL) OR $2::boolean = FALSE)
`

type GetStationInventoryParams struct {
	StationID uuid.UUID `json:"station_id"`
	Column2   bool      `json:"column_2"`
}

type GetStationInventoryRow struct {
	ID               uuid.UUID  `json:"id"`
	StationID        uuid.UUID  `json:"station_id"`
	DeliveryOrderID  uuid.UUID  `json:"delivery_order_id"`
	Direction        string     `json:"direction"`
	ShelfCode        string     `json:"shelf_code"`
	VerificationCode string     `json:"verification_code"`
	CheckInAt        time.Time  `json:"check_in_at"`
	CheckInBy        uuid.UUID  `json:"check_in_by"`
	CheckOutAt       *time.Time `json:"check_out_at"`
	CheckOutBy       *uuid.UUID `json:"check_out_by"`
	CreatedAt        time.Time  `json:"created_at"`
	TrackingNumber   string     `json:"tracking_number"`
	RecipientName    string     `json:"recipient_name"`
	RecipientPhone   string     `json:"recipient_phone"`
}

// GetStationInventory
//
//	SELECT sp.id, sp.station_id, sp.delivery_order_id, sp.direction, sp.shelf_code, sp.verification_code, sp.check_in_at, sp.check_in_by, sp.check_out_at, sp.check_out_by, sp.created_at, dor.tracking_number, dor.recipient_name, dor.recipient_phone
//	FROM station_packages sp
//	JOIN delivery_orders dor ON sp.delivery_order_id = dor.id
//	WHERE sp.station_id = $1 AND (($2::boolean = TRUE AND sp.check_out_at IS NULL) OR $2::boolean = FALSE)
func (q *Queries) GetStationInventory(ctx context.Context, arg GetStationInventoryParams) ([]GetStationInventoryRow, error) {
	rows, err := q.db.Query(ctx, getStationInventory, arg.StationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStationInventoryRow
	for rows.Next() {
		var i GetStationInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.DeliveryOrderID,
			&i.Direction,
			&i.ShelfCode,
			&i.VerificationCode,
			&i.CheckInAt,
			&i.CheckInBy,
			&i.CheckOutAt,
			&i.CheckOutBy,
			&i.CreatedAt,
			&i.TrackingNumber,
			&i.RecipientName,
			&i.RecipientPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStationPackageByTrackingNumber = `-- name: GetStationPackageByTrackingNumber :one
SELECT sp.id, sp.station_id, sp.delivery_order_id, sp.direction, sp.shelf_code, sp.verification_code, sp.check_in_at, sp.check_in_by, sp.check_out_at, sp.check_out_by, sp.created_at
FROM station_packages sp
JOIN delivery_orders dor ON sp.delivery_order_id = dor.id
WHERE dor.tracking_number = $1
`

// GetStationPackageByTrackingNumber
//
//	SELECT sp.id, sp.station_id, sp.delivery_order_id, sp.direction, sp.shelf_code, sp.verification_code, sp.check_in_at, sp.check_in_by, sp.check_out_at, sp.check_out_by, sp.created_at
//	FROM station_packages sp
//	JOIN delivery_orders dor ON sp.delivery_order_id = dor.id
//	WHERE dor.tracking_number = $1
func (q *Queries) GetStationPackageByTrackingNumber(ctx context.Context, trackingNumber string) (StationPackage, error) {
	row := q.db.QueryRow(ctx, getStationPackageByTrackingNumber, trackingNumber)
	var i StationPackage
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.DeliveryOrderID,
		&i.Direction,
		&i.ShelfCode,
		&i.VerificationCode,
		&i.CheckInAt,
		&i.CheckInBy,
		&i.CheckOutAt,
		&i.CheckOutBy,
		&i.CreatedAt,
	)
	return i, err
}

const getStationsNearLocation = `-- name: GetStationsNearLocation :many
SELECT id, keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, current_package_count, operating_hours, created_at, updated_at, ST_Distance(location, ST_SetSRID(ST_MakePoint($1, $2), 4326)) AS distance
FROM stations
WHERE status = 'active'
ORDER BY location <-> ST_SetSRID(ST_MakePoint($1, $2), 4326)
LIMIT $3
`

type GetStationsNearLocationParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	Limit         int32       `json:"limit"`
}

type GetStationsNearLocationRow struct {
	ID                  uuid.UUID   `json:"id"`
	KeeperUserID        uuid.UUID   `json:"keeper_user_id"`
	Name                string      `json:"name"`
	StoreType           string      `json:"store_type"`
	Phone               string      `json:"phone"`
	AddressLine1        string      `json:"address_line1"`
	City                string      `json:"city"`
	Country             string      `json:"country"`
	Location            string      `json:"location"`
	Status              string      `json:"status"`
	CapacityPackages    int32       `json:"capacity_packages"`
	CurrentPackageCount int32       `json:"current_package_count"`
	OperatingHours      []byte      `json:"operating_hours"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	Distance            interface{} `json:"distance"`
}

// GetStationsNearLocation
//
//	SELECT id, keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, current_package_count, operating_hours, created_at, updated_at, ST_Distance(location, ST_SetSRID(ST_MakePoint($1, $2), 4326)) AS distance
//	FROM stations
//	WHERE status = 'active'
//	ORDER BY location <-> ST_SetSRID(ST_MakePoint($1, $2), 4326)
//	LIMIT $3
func (q *Queries) GetStationsNearLocation(ctx context.Context, arg GetStationsNearLocationParams) ([]GetStationsNearLocationRow, error) {
	rows, err := q.db.Query(ctx, getStationsNearLocation, arg.StMakepoint, arg.StMakepoint_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStationsNearLocationRow
	for rows.Next() {
		var i GetStationsNearLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.KeeperUserID,
			&i.Name,
			&i.StoreType,
			&i.Phone,
			&i.AddressLine1,
			&i.City,
			&i.Country,
			&i.Location,
			&i.Status,
			&i.CapacityPackages,
			&i.CurrentPackageCount,
			&i.OperatingHours,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackingLogsByDeliveryOrderID = `-- name: GetTrackingLogsByDeliveryOrderID :many
SELECT id, delivery_order_id, status, location_desc, coordinate, details, operator_id, created_at FROM tracking_logs
WHERE delivery_order_id = $1
ORDER BY created_at DESC
`

// GetTrackingLogsByDeliveryOrderID
//
//	SELECT id, delivery_order_id, status, location_desc, coordinate, details, operator_id, created_at FROM tracking_logs
//	WHERE delivery_order_id = $1
//	ORDER BY created_at DESC
func (q *Queries) GetTrackingLogsByDeliveryOrderID(ctx context.Context, deliveryOrderID uuid.UUID) ([]TrackingLog, error) {
	rows, err := q.db.Query(ctx, getTrackingLogsByDeliveryOrderID, deliveryOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingLog
	for rows.Next() {
		var i TrackingLog
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryOrderID,
			&i.Status,
			&i.LocationDesc,
			&i.Coordinate,
			&i.Details,
			&i.OperatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLogisticsPartners = `-- name: ListActiveLogisticsPartners :many
SELECT id, name, code, api_endpoint, api_key, is_active, pricing_schema, created_at, updated_at FROM logistics_partners
WHERE is_active = TRUE
`

// ListActiveLogisticsPartners
//
//	SELECT id, name, code, api_endpoint, api_key, is_active, pricing_schema, created_at, updated_at FROM logistics_partners
//	WHERE is_active = TRUE
func (q *Queries) ListActiveLogisticsPartners(ctx context.Context) ([]LogisticsPartner, error) {
	rows, err := q.db.Query(ctx, listActiveLogisticsPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogisticsPartner
	for rows.Next() {
		var i LogisticsPartner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ApiEndpoint,
			&i.ApiKey,
			&i.IsActive,
			&i.PricingSchema,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourierBalance = `-- name: UpdateCourierBalance :one
UPDATE couriers
SET wallet_balance = wallet_balance + $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at
`

type UpdateCourierBalanceParams struct {
	ID            uuid.UUID      `json:"id"`
	WalletBalance pgtype.Numeric `json:"wallet_balance"`
}

// UpdateCourierBalance
//
//	UPDATE couriers
//	SET wallet_balance = wallet_balance + $2, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at
func (q *Queries) UpdateCourierBalance(ctx context.Context, arg UpdateCourierBalanceParams) (Courier, error) {
	row := q.db.QueryRow(ctx, updateCourierBalance, arg.ID, arg.WalletBalance)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleType,
		&i.PlateNumber,
		&i.IsOnline,
		&i.VerificationStatus,
		&i.Rating,
		&i.CurrentLocation,
		&i.WalletBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourierLocation = `-- name: UpdateCourierLocation :one
UPDATE couriers
SET current_location = ST_SetSRID(ST_MakePoint($2, $3), 4326), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at
`

type UpdateCourierLocationParams struct {
	ID            uuid.UUID   `json:"id"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

// UpdateCourierLocation
//
//	UPDATE couriers
//	SET current_location = ST_SetSRID(ST_MakePoint($2, $3), 4326), updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at
func (q *Queries) UpdateCourierLocation(ctx context.Context, arg UpdateCourierLocationParams) (Courier, error) {
	row := q.db.QueryRow(ctx, updateCourierLocation, arg.ID, arg.StMakepoint, arg.StMakepoint_2)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleType,
		&i.PlateNumber,
		&i.IsOnline,
		&i.VerificationStatus,
		&i.Rating,
		&i.CurrentLocation,
		&i.WalletBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourierStatus = `-- name: UpdateCourierStatus :one
UPDATE couriers
SET is_online = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at
`

type UpdateCourierStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsOnline bool      `json:"is_online"`
}

// UpdateCourierStatus
//
//	UPDATE couriers
//	SET is_online = $2, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, user_id, vehicle_type, plate_number, is_online, verification_status, rating, current_location, wallet_balance, created_at, updated_at
func (q *Queries) UpdateCourierStatus(ctx context.Context, arg UpdateCourierStatusParams) (Courier, error) {
	row := q.db.QueryRow(ctx, updateCourierStatus, arg.ID, arg.IsOnline)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleType,
		&i.PlateNumber,
		&i.IsOnline,
		&i.VerificationStatus,
		&i.Rating,
		&i.CurrentLocation,
		&i.WalletBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourierTaskStatus = `-- name: UpdateCourierTaskStatus :one
UPDATE courier_tasks
SET status = $3, responded_at = NOW()
WHERE delivery_order_id = $1 AND courier_id = $2
RETURNING id, delivery_order_id, courier_id, status, offered_at, responded_at
`

type UpdateCourierTaskStatusParams struct {
	DeliveryOrderID uuid.UUID `json:"delivery_order_id"`
	CourierID       uuid.UUID `json:"courier_id"`
	Status          string    `json:"status"`
}

// UpdateCourierTaskStatus
//
//	UPDATE courier_tasks
//	SET status = $3, responded_at = NOW()
//	WHERE delivery_order_id = $1 AND courier_id = $2
//	RETURNING id, delivery_order_id, courier_id, status, offered_at, responded_at
func (q *Queries) UpdateCourierTaskStatus(ctx context.Context, arg UpdateCourierTaskStatusParams) (CourierTask, error) {
	row := q.db.QueryRow(ctx, updateCourierTaskStatus, arg.DeliveryOrderID, arg.CourierID, arg.Status)
	var i CourierTask
	err := row.Scan(
		&i.ID,
		&i.DeliveryOrderID,
		&i.CourierID,
		&i.Status,
		&i.OfferedAt,
		&i.RespondedAt,
	)
	return i, err
}

const updateDeliveryOrderPaymentStatus = `-- name: UpdateDeliveryOrderPaymentStatus :one
UPDATE delivery_orders
SET payment_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at
`

type UpdateDeliveryOrderPaymentStatusParams struct {
	ID            uuid.UUID `json:"id"`
	PaymentStatus string    `json:"payment_status"`
}

// UpdateDeliveryOrderPaymentStatus
//
//	UPDATE delivery_orders
//	SET payment_status = $2, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at
func (q *Queries) UpdateDeliveryOrderPaymentStatus(ctx context.Context, arg UpdateDeliveryOrderPaymentStatusParams) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, updateDeliveryOrderPaymentStatus, arg.ID, arg.PaymentStatus)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.OrderID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.SenderPhone,
		&i.SenderAddressLine1,
		&i.SenderCity,
		&i.SenderCountry,
		&i.SenderLocation,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientAddressLine1,
		&i.RecipientCity,
		&i.RecipientCountry,
		&i.RecipientLocation,
		&i.DeliveryType,
		&i.OriginStationID,
		&i.DestinationStationID,
		&i.CarrierType,
		&i.CarrierPartnerID,
		&i.CarrierCourierID,
		&i.ExternalTrackingNo,
		&i.WeightKg,
		&i.DimensionsCm,
		&i.ShippingFee,
		&i.PaymentStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
	)
	return i, err
}

const updateDeliveryOrderStatus = `-- name: UpdateDeliveryOrderStatus :one
UPDATE delivery_orders
SET status = $2, updated_at = NOW(),
    picked_up_at = CASE WHEN $2 = 'picked_up'::delivery_status THEN NOW() ELSE picked_up_at END,
    delivered_at = CASE WHEN $2 = 'delivered'::delivery_status THEN NOW() ELSE delivered_at END
WHERE id = $1
RETURNING id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at
`

type UpdateDeliveryOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// UpdateDeliveryOrderStatus
//
//	UPDATE delivery_orders
//	SET status = $2, updated_at = NOW(),
//	    picked_up_at = CASE WHEN $2 = 'picked_up'::delivery_status THEN NOW() ELSE picked_up_at END,
//	    delivered_at = CASE WHEN $2 = 'delivered'::delivery_status THEN NOW() ELSE delivered_at END
//	WHERE id = $1
//	RETURNING id, tracking_number, order_id, sender_type, sender_id, sender_name, sender_phone, sender_address_line1, sender_city, sender_country, sender_location, recipient_name, recipient_phone, recipient_address_line1, recipient_city, recipient_country, recipient_location, delivery_type, origin_station_id, destination_station_id, carrier_type, carrier_partner_id, carrier_courier_id, external_tracking_no, weight_kg, dimensions_cm, shipping_fee, payment_status, status, created_at, updated_at, picked_up_at, delivered_at
func (q *Queries) UpdateDeliveryOrderStatus(ctx context.Context, arg UpdateDeliveryOrderStatusParams) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, updateDeliveryOrderStatus, arg.ID, arg.Status)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.OrderID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.SenderPhone,
		&i.SenderAddressLine1,
		&i.SenderCity,
		&i.SenderCountry,
		&i.SenderLocation,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientAddressLine1,
		&i.RecipientCity,
		&i.RecipientCountry,
		&i.RecipientLocation,
		&i.DeliveryType,
		&i.OriginStationID,
		&i.DestinationStationID,
		&i.CarrierType,
		&i.CarrierPartnerID,
		&i.CarrierCourierID,
		&i.ExternalTrackingNo,
		&i.WeightKg,
		&i.DimensionsCm,
		&i.ShippingFee,
		&i.PaymentStatus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
	)
	return i, err
}

const updateStationPackageCount = `-- name: UpdateStationPackageCount :one
UPDATE stations
SET current_package_count = current_package_count + $2, updated_at = NOW()
WHERE id = $1
RETURNING id, keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, current_package_count, operating_hours, created_at, updated_at
`

type UpdateStationPackageCountParams struct {
	ID                  uuid.UUID `json:"id"`
	CurrentPackageCount int32     `json:"current_package_count"`
}

// UpdateStationPackageCount
//
//	UPDATE stations
//	SET current_package_count = current_package_count + $2, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, keeper_user_id, name, store_type, phone, address_line1, city, country, location, status, capacity_packages, current_package_count, operating_hours, created_at, updated_at
func (q *Queries) UpdateStationPackageCount(ctx context.Context, arg UpdateStationPackageCountParams) (Station, error) {
	row := q.db.QueryRow(ctx, updateStationPackageCount, arg.ID, arg.CurrentPackageCount)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.KeeperUserID,
		&i.Name,
		&i.StoreType,
		&i.Phone,
		&i.AddressLine1,
		&i.City,
		&i.Country,
		&i.Location,
		&i.Status,
		&i.CapacityPackages,
		&i.CurrentPackageCount,
		&i.OperatingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
