// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddAdCreditResponse struct {
	NewAdCreditBalance float64 `json:"newAdCreditBalance"`
}

type AddFlashSaleItemInput struct {
	FlashSaleID   string  `json:"flashSaleId"`
	ProductID     string  `json:"productId"`
	DiscountPrice float64 `json:"discountPrice"`
	StockLimit    int     `json:"stockLimit"`
}

type AppendReview struct {
	ID        string         `json:"id"`
	Content   string         `json:"content"`
	HasMedia  bool           `json:"hasMedia"`
	Media     []*ReviewMedia `json:"media"`
	CreatedAt time.Time      `json:"createdAt"`
}

type AppendReviewInput struct {
	ReviewID  string   `json:"reviewId"`
	Content   string   `json:"content"`
	MediaUrls []string `json:"mediaUrls,omitempty"`
}

type ChatMessage struct {
	ID        string    `json:"id"`
	ThreadID  string    `json:"threadId"`
	SenderID  string    `json:"senderId"`
	Content   string    `json:"content"`
	IsRead    bool      `json:"isRead"`
	Timestamp string    `json:"timestamp"`
	CreatedAt time.Time `json:"createdAt"`
}

type ChatMessageList struct {
	Messages      []*ChatMessage `json:"messages"`
	NextPageToken *string        `json:"nextPageToken,omitempty"`
}

type ChatThread struct {
	ID          string    `json:"id"`
	BuyerID     string    `json:"buyerId"`
	SellerID    string    `json:"sellerId"`
	OrderID     *string   `json:"orderId,omitempty"`
	BuyerName   string    `json:"buyerName"`
	LastMessage string    `json:"lastMessage"`
	Timestamp   string    `json:"timestamp"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ChatThreadList struct {
	Threads []*ChatThread `json:"threads"`
}

type Coupon struct {
	ID            string       `json:"id"`
	Code          string       `json:"code"`
	SellerID      *string      `json:"sellerId,omitempty"`
	DiscountType  DiscountType `json:"discountType"`
	DiscountValue float64      `json:"discountValue"`
	MinOrderValue float64      `json:"minOrderValue"`
	MaxDiscount   float64      `json:"maxDiscount"`
	StartDate     time.Time    `json:"startDate"`
	EndDate       time.Time    `json:"endDate"`
	UsageLimit    int          `json:"usageLimit"`
	UsageCount    int          `json:"usageCount"`
}

type Courier struct {
	ID          string  `json:"id"`
	VehicleType string  `json:"vehicleType"`
	PlateNumber *string `json:"plateNumber,omitempty"`
	IsOnline    bool    `json:"isOnline"`
	Rating      float64 `json:"rating"`
}

type CreateCouponInput struct {
	Code          string       `json:"code"`
	DiscountType  DiscountType `json:"discountType"`
	DiscountValue float64      `json:"discountValue"`
	MinOrderValue float64      `json:"minOrderValue"`
	MaxDiscount   float64      `json:"maxDiscount"`
	StartDate     time.Time    `json:"startDate"`
	EndDate       time.Time    `json:"endDate"`
	UsageLimit    int          `json:"usageLimit"`
}

type CreateFlashSaleInput struct {
	Name      string    `json:"name"`
	StartTime time.Time `json:"startTime"`
	EndTime   time.Time `json:"endTime"`
}

type CreateReviewInput struct {
	OrderID           string   `json:"orderId"`
	ProductID         string   `json:"productId"`
	VariantID         string   `json:"variantId"`
	RatingDescription int      `json:"ratingDescription"`
	RatingService     int      `json:"ratingService"`
	RatingDelivery    int      `json:"ratingDelivery"`
	Content           *string  `json:"content,omitempty"`
	IsAnonymous       *bool    `json:"isAnonymous,omitempty"`
	MediaUrls         []string `json:"mediaUrls,omitempty"`
}

type DeliveryInvoice struct {
	DeliveryOrder *DeliveryOrder `json:"deliveryOrder"`
	PaymentSecret string         `json:"paymentSecret"`
	PaymentURL    string         `json:"paymentUrl"`
}

type DeliveryOrder struct {
	ID                 string         `json:"id"`
	TrackingNumber     string         `json:"trackingNumber"`
	OrderID            *string        `json:"orderId,omitempty"`
	SenderName         string         `json:"senderName"`
	SenderPhone        string         `json:"senderPhone"`
	RecipientName      string         `json:"recipientName"`
	RecipientPhone     string         `json:"recipientPhone"`
	DeliveryType       DeliveryType   `json:"deliveryType"`
	OriginStation      *Station       `json:"originStation,omitempty"`
	DestinationStation *Station       `json:"destinationStation,omitempty"`
	WeightKg           float64        `json:"weightKg"`
	ShippingFee        float64        `json:"shippingFee"`
	Status             string         `json:"status"`
	TrackingLogs       []*TrackingLog `json:"trackingLogs"`
	CreatedAt          string         `json:"createdAt"`
}

type Dispute struct {
	ID        string        `json:"id"`
	OrderID   string        `json:"orderId"`
	BuyerID   string        `json:"buyerId"`
	SellerID  string        `json:"sellerId"`
	Reason    string        `json:"reason"`
	Status    DisputeStatus `json:"status"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

type DisputeList struct {
	Disputes []*Dispute `json:"disputes"`
}

type DisputeMessage struct {
	ID           string    `json:"id"`
	DisputeID    string    `json:"disputeId"`
	SenderID     string    `json:"senderId"`
	Content      string    `json:"content"`
	EvidenceUrls []string  `json:"evidenceUrls,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
}

type DisputeMessageList struct {
	Messages []*DisputeMessage `json:"messages"`
}

type EarningsLedgerEntry struct {
	ID            string     `json:"id"`
	OrderID       string     `json:"orderId"`
	OrderItemID   string     `json:"orderItemId"`
	GrossAmount   float64    `json:"grossAmount"`
	CommissionFee float64    `json:"commissionFee"`
	NetAmount     float64    `json:"netAmount"`
	Status        string     `json:"status"`
	CreatedAt     time.Time  `json:"createdAt"`
	SettledAt     *time.Time `json:"settledAt,omitempty"`
}

type FlashSale struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	StartTime time.Time        `json:"startTime"`
	EndTime   time.Time        `json:"endTime"`
	Status    FlashSaleStatus  `json:"status"`
	Items     []*FlashSaleItem `json:"items"`
}

type FlashSaleItem struct {
	ID            string   `json:"id"`
	ProductID     string   `json:"productId"`
	DiscountPrice float64  `json:"discountPrice"`
	StockLimit    int      `json:"stockLimit"`
	Thumbnail     *string  `json:"thumbnail,omitempty"`
	ProductTitle  *string  `json:"productTitle,omitempty"`
	Rating        *float64 `json:"rating,omitempty"`
}

type InitiatePaymentResponse struct {
	Payment      *Payment `json:"payment"`
	ClientSecret *string  `json:"clientSecret,omitempty"`
}

type Location struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type LocationInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type Mutation struct {
}

type NotificationLog struct {
	ID        string    `json:"id"`
	Category  string    `json:"category"`
	Channel   string    `json:"channel"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
}

type NotificationPreference struct {
	Category     NotificationCategory `json:"category"`
	EmailEnabled bool                 `json:"emailEnabled"`
	PushEnabled  bool                 `json:"pushEnabled"`
}

type Payment struct {
	ID            string          `json:"id"`
	OrderID       string          `json:"orderId"`
	UserID        string          `json:"userId"`
	Amount        float64         `json:"amount"`
	Currency      string          `json:"currency"`
	Provider      PaymentProvider `json:"provider"`
	Status        PaymentStatus   `json:"status"`
	TransactionID *string         `json:"transactionId,omitempty"`
	CreatedAt     time.Time       `json:"createdAt"`
	UpdatedAt     time.Time       `json:"updatedAt"`
}

type Payout struct {
	ID          string       `json:"id"`
	SellerID    string       `json:"sellerId"`
	Amount      float64      `json:"amount"`
	Currency    string       `json:"currency"`
	Status      PayoutStatus `json:"status"`
	ProviderRef *string      `json:"providerRef,omitempty"`
	PaidAt      *time.Time   `json:"paidAt,omitempty"`
	CreatedAt   time.Time    `json:"createdAt"`
	GrossAmount float64      `json:"grossAmount"`
	PlatformFee float64      `json:"platformFee"`
	NetAmount   float64      `json:"netAmount"`
}

type PayoutList struct {
	Payouts       []*Payout `json:"payouts"`
	NextPageToken *string   `json:"nextPageToken,omitempty"`
	Total         int       `json:"total"`
}

type PersonalDeliveryInput struct {
	SenderName           string         `json:"senderName"`
	SenderPhone          string         `json:"senderPhone"`
	SenderAddress        string         `json:"senderAddress"`
	SenderCity           string         `json:"senderCity"`
	SenderCountry        string         `json:"senderCountry"`
	SenderLocation       *LocationInput `json:"senderLocation"`
	RecipientName        string         `json:"recipientName"`
	RecipientPhone       string         `json:"recipientPhone"`
	RecipientAddress     string         `json:"recipientAddress"`
	RecipientCity        string         `json:"recipientCity"`
	RecipientCountry     string         `json:"recipientCountry"`
	RecipientLocation    *LocationInput `json:"recipientLocation"`
	DeliveryType         DeliveryType   `json:"deliveryType"`
	DestinationStationID *string        `json:"destinationStationId,omitempty"`
	WeightKg             float64        `json:"weightKg"`
	LengthCm             int            `json:"lengthCm"`
	WidthCm              int            `json:"widthCm"`
	HeightCm             int            `json:"heightCm"`
}

type PlatformMetrics struct {
	TotalUsers     int `json:"totalUsers"`
	TotalSellers   int `json:"totalSellers"`
	ActiveDisputes int `json:"activeDisputes"`
	TotalOrders    int `json:"totalOrders"`
}

type ProductReviewConnection struct {
	Edges      []*Review `json:"edges"`
	TotalCount int       `json:"totalCount"`
}

type ProductReviewStats struct {
	AverageRating float64  `json:"averageRating"`
	TotalReviews  int      `json:"totalReviews"`
	GoodCount     int      `json:"goodCount"`
	NeutralCount  int      `json:"neutralCount"`
	BadCount      int      `json:"badCount"`
	HasMediaCount int      `json:"hasMediaCount"`
	AppendCount   int      `json:"appendCount"`
	TopTags       []string `json:"topTags"`
}

type ProductWithDistance struct {
	Product  *Product `json:"product"`
	Distance float64  `json:"distance"`
}

type Query struct {
}

type Review struct {
	ID                string         `json:"id"`
	OrderID           string         `json:"orderId"`
	BuyerID           string         `json:"buyerId"`
	BuyerName         string         `json:"buyerName"`
	BuyerAvatar       *string        `json:"buyerAvatar,omitempty"`
	RatingDescription int            `json:"ratingDescription"`
	RatingService     int            `json:"ratingService"`
	RatingDelivery    int            `json:"ratingDelivery"`
	ReviewType        string         `json:"reviewType"`
	Content           *string        `json:"content,omitempty"`
	IsAnonymous       bool           `json:"isAnonymous"`
	HasMedia          bool           `json:"hasMedia"`
	Media             []*ReviewMedia `json:"media"`
	NlpTags           []string       `json:"nlpTags"`
	IsSystemGenerated bool           `json:"isSystemGenerated"`
	CreatedAt         time.Time      `json:"createdAt"`
	UpdatedAt         time.Time      `json:"updatedAt"`
	AppendReview      *AppendReview  `json:"appendReview,omitempty"`
	Replies           []*SellerReply `json:"replies"`
}

type ReviewMedia struct {
	ID        string `json:"id"`
	MediaURL  string `json:"mediaUrl"`
	MediaType string `json:"mediaType"`
}

type SellerBalance struct {
	EscrowedBalance     float64 `json:"escrowedBalance"`
	WithdrawableBalance float64 `json:"withdrawableBalance"`
	TotalSales          float64 `json:"totalSales"`
}

type SellerDsr struct {
	AvgDescription  float64 `json:"avgDescription"`
	AvgService      float64 `json:"avgService"`
	AvgDelivery     float64 `json:"avgDelivery"`
	ReputationScore int     `json:"reputationScore"`
}

type SellerDashboard struct {
	Store               *Seller   `json:"store"`
	ProductsCount       int       `json:"productsCount"`
	ActiveProductsCount int       `json:"activeProductsCount"`
	PendingOrdersCount  int       `json:"pendingOrdersCount"`
	TotalOrdersCount    int       `json:"totalOrdersCount"`
	RecentOrders        []*Order  `json:"recentOrders"`
	WeeklyRevenue       []float64 `json:"weeklyRevenue"`
}

type SellerEarningsLedgerConnection struct {
	Entries       []*EarningsLedgerEntry `json:"entries"`
	NextPageToken *string                `json:"nextPageToken,omitempty"`
}

type SellerMonetizationConfig struct {
	CommissionRate  float64 `json:"commissionRate"`
	AdCreditBalance float64 `json:"adCreditBalance"`
}

type SellerOrderList struct {
	Orders        []*Order `json:"orders"`
	NextPageToken *string  `json:"nextPageToken,omitempty"`
	Total         int      `json:"total"`
}

type SellerReply struct {
	ID        string    `json:"id"`
	ReplyType string    `json:"replyType"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}

type SellerReplyInput struct {
	ReviewID  string `json:"reviewId"`
	ReplyType string `json:"replyType"`
	Content   string `json:"content"`
}

type Station struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	StoreType      string    `json:"storeType"`
	Phone          string    `json:"phone"`
	AddressLine1   string    `json:"addressLine1"`
	City           string    `json:"city"`
	Country        string    `json:"country"`
	Location       *Location `json:"location"`
	OperatingHours string    `json:"operatingHours"`
}

type StationPackage struct {
	ID            string         `json:"id"`
	Station       *Station       `json:"station"`
	DeliveryOrder *DeliveryOrder `json:"deliveryOrder"`
	ShelfCode     string         `json:"shelfCode"`
	CheckInAt     string         `json:"checkInAt"`
	CheckOutAt    *string        `json:"checkOutAt,omitempty"`
}

type TrackingLog struct {
	ID           string  `json:"id"`
	Status       string  `json:"status"`
	LocationDesc string  `json:"locationDesc"`
	Details      *string `json:"details,omitempty"`
	CreatedAt    string  `json:"createdAt"`
}

type UpdateReviewInput struct {
	ReviewID          string  `json:"reviewId"`
	RatingDescription int     `json:"ratingDescription"`
	RatingService     int     `json:"ratingService"`
	RatingDelivery    int     `json:"ratingDelivery"`
	Content           *string `json:"content,omitempty"`
}

type DeliveryType string

const (
	DeliveryTypeDoorToDoor       DeliveryType = "DOOR_TO_DOOR"
	DeliveryTypeStationToDoor    DeliveryType = "STATION_TO_DOOR"
	DeliveryTypeDoorToStation    DeliveryType = "DOOR_TO_STATION"
	DeliveryTypeStationToStation DeliveryType = "STATION_TO_STATION"
)

var AllDeliveryType = []DeliveryType{
	DeliveryTypeDoorToDoor,
	DeliveryTypeStationToDoor,
	DeliveryTypeDoorToStation,
	DeliveryTypeStationToStation,
}

func (e DeliveryType) IsValid() bool {
	switch e {
	case DeliveryTypeDoorToDoor, DeliveryTypeStationToDoor, DeliveryTypeDoorToStation, DeliveryTypeStationToStation:
		return true
	}
	return false
}

func (e DeliveryType) String() string {
	return string(e)
}

func (e *DeliveryType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeliveryType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeliveryType", str)
	}
	return nil
}

func (e DeliveryType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DiscountType string

const (
	DiscountTypePercentage  DiscountType = "PERCENTAGE"
	DiscountTypeFixedAmount DiscountType = "FIXED_AMOUNT"
)

var AllDiscountType = []DiscountType{
	DiscountTypePercentage,
	DiscountTypeFixedAmount,
}

func (e DiscountType) IsValid() bool {
	switch e {
	case DiscountTypePercentage, DiscountTypeFixedAmount:
		return true
	}
	return false
}

func (e DiscountType) String() string {
	return string(e)
}

func (e *DiscountType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiscountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiscountType", str)
	}
	return nil
}

func (e DiscountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DisputeStatus string

const (
	DisputeStatusOpen             DisputeStatus = "OPEN"
	DisputeStatusSellerReview     DisputeStatus = "SELLER_REVIEW"
	DisputeStatusEscalated        DisputeStatus = "ESCALATED"
	DisputeStatusResolvedRefunded DisputeStatus = "RESOLVED_REFUNDED"
	DisputeStatusResolvedRejected DisputeStatus = "RESOLVED_REJECTED"
)

var AllDisputeStatus = []DisputeStatus{
	DisputeStatusOpen,
	DisputeStatusSellerReview,
	DisputeStatusEscalated,
	DisputeStatusResolvedRefunded,
	DisputeStatusResolvedRejected,
}

func (e DisputeStatus) IsValid() bool {
	switch e {
	case DisputeStatusOpen, DisputeStatusSellerReview, DisputeStatusEscalated, DisputeStatusResolvedRefunded, DisputeStatusResolvedRejected:
		return true
	}
	return false
}

func (e DisputeStatus) String() string {
	return string(e)
}

func (e *DisputeStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DisputeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DisputeStatus", str)
	}
	return nil
}

func (e DisputeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FlashSaleStatus string

const (
	FlashSaleStatusScheduled FlashSaleStatus = "SCHEDULED"
	FlashSaleStatusActive    FlashSaleStatus = "ACTIVE"
	FlashSaleStatusEnded     FlashSaleStatus = "ENDED"
)

var AllFlashSaleStatus = []FlashSaleStatus{
	FlashSaleStatusScheduled,
	FlashSaleStatusActive,
	FlashSaleStatusEnded,
}

func (e FlashSaleStatus) IsValid() bool {
	switch e {
	case FlashSaleStatusScheduled, FlashSaleStatusActive, FlashSaleStatusEnded:
		return true
	}
	return false
}

func (e FlashSaleStatus) String() string {
	return string(e)
}

func (e *FlashSaleStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FlashSaleStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FlashSaleStatus", str)
	}
	return nil
}

func (e FlashSaleStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type NotificationCategory string

const (
	NotificationCategoryTransactional NotificationCategory = "TRANSACTIONAL"
	NotificationCategorySecurity      NotificationCategory = "SECURITY"
	NotificationCategoryLowStock      NotificationCategory = "LOW_STOCK"
	NotificationCategoryFollows       NotificationCategory = "FOLLOWS"
	NotificationCategoryMarketing     NotificationCategory = "MARKETING"
)

var AllNotificationCategory = []NotificationCategory{
	NotificationCategoryTransactional,
	NotificationCategorySecurity,
	NotificationCategoryLowStock,
	NotificationCategoryFollows,
	NotificationCategoryMarketing,
}

func (e NotificationCategory) IsValid() bool {
	switch e {
	case NotificationCategoryTransactional, NotificationCategorySecurity, NotificationCategoryLowStock, NotificationCategoryFollows, NotificationCategoryMarketing:
		return true
	}
	return false
}

func (e NotificationCategory) String() string {
	return string(e)
}

func (e *NotificationCategory) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationCategory", str)
	}
	return nil
}

func (e NotificationCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PaymentProvider string

const (
	PaymentProviderGooglePay PaymentProvider = "GOOGLE_PAY"
	PaymentProviderStripe    PaymentProvider = "STRIPE"
)

var AllPaymentProvider = []PaymentProvider{
	PaymentProviderGooglePay,
	PaymentProviderStripe,
}

func (e PaymentProvider) IsValid() bool {
	switch e {
	case PaymentProviderGooglePay, PaymentProviderStripe:
		return true
	}
	return false
}

func (e PaymentProvider) String() string {
	return string(e)
}

func (e *PaymentProvider) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentProvider", str)
	}
	return nil
}

func (e PaymentProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "PENDING"
	PaymentStatusCompleted PaymentStatus = "COMPLETED"
	PaymentStatusFailed    PaymentStatus = "FAILED"
	PaymentStatusRefunded  PaymentStatus = "REFUNDED"
)

var AllPaymentStatus = []PaymentStatus{
	PaymentStatusPending,
	PaymentStatusCompleted,
	PaymentStatusFailed,
	PaymentStatusRefunded,
}

func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusPending, PaymentStatusCompleted, PaymentStatusFailed, PaymentStatusRefunded:
		return true
	}
	return false
}

func (e PaymentStatus) String() string {
	return string(e)
}

func (e *PaymentStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}

func (e PaymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PayoutStatus string

const (
	PayoutStatusPending    PayoutStatus = "PENDING"
	PayoutStatusProcessing PayoutStatus = "PROCESSING"
	PayoutStatusPaid       PayoutStatus = "PAID"
	PayoutStatusFailed     PayoutStatus = "FAILED"
)

var AllPayoutStatus = []PayoutStatus{
	PayoutStatusPending,
	PayoutStatusProcessing,
	PayoutStatusPaid,
	PayoutStatusFailed,
}

func (e PayoutStatus) IsValid() bool {
	switch e {
	case PayoutStatusPending, PayoutStatusProcessing, PayoutStatusPaid, PayoutStatusFailed:
		return true
	}
	return false
}

func (e PayoutStatus) String() string {
	return string(e)
}

func (e *PayoutStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PayoutStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PayoutStatus", str)
	}
	return nil
}

func (e PayoutStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ReviewFilterType string

const (
	ReviewFilterTypeAll      ReviewFilterType = "ALL"
	ReviewFilterTypeGood     ReviewFilterType = "GOOD"
	ReviewFilterTypeNeutral  ReviewFilterType = "NEUTRAL"
	ReviewFilterTypeBad      ReviewFilterType = "BAD"
	ReviewFilterTypeHasMedia ReviewFilterType = "HAS_MEDIA"
	ReviewFilterTypeAppend   ReviewFilterType = "APPEND"
)

var AllReviewFilterType = []ReviewFilterType{
	ReviewFilterTypeAll,
	ReviewFilterTypeGood,
	ReviewFilterTypeNeutral,
	ReviewFilterTypeBad,
	ReviewFilterTypeHasMedia,
	ReviewFilterTypeAppend,
}

func (e ReviewFilterType) IsValid() bool {
	switch e {
	case ReviewFilterTypeAll, ReviewFilterTypeGood, ReviewFilterTypeNeutral, ReviewFilterTypeBad, ReviewFilterTypeHasMedia, ReviewFilterTypeAppend:
		return true
	}
	return false
}

func (e ReviewFilterType) String() string {
	return string(e)
}

func (e *ReviewFilterType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReviewFilterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReviewFilterType", str)
	}
	return nil
}

func (e ReviewFilterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
