// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Mutation struct {
}

type NotificationLog struct {
	ID        string    `json:"id"`
	Category  string    `json:"category"`
	Channel   string    `json:"channel"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
}

type NotificationPreference struct {
	Category     NotificationCategory `json:"category"`
	EmailEnabled bool                 `json:"emailEnabled"`
	PushEnabled  bool                 `json:"pushEnabled"`
}

type ProductWithDistance struct {
	Product  *Product `json:"product"`
	Distance float64  `json:"distance"`
}

type Query struct {
}

type NotificationCategory string

const (
	NotificationCategoryTransactional NotificationCategory = "TRANSACTIONAL"
	NotificationCategorySecurity      NotificationCategory = "SECURITY"
	NotificationCategoryLowStock      NotificationCategory = "LOW_STOCK"
	NotificationCategoryFollows       NotificationCategory = "FOLLOWS"
	NotificationCategoryMarketing     NotificationCategory = "MARKETING"
)

var AllNotificationCategory = []NotificationCategory{
	NotificationCategoryTransactional,
	NotificationCategorySecurity,
	NotificationCategoryLowStock,
	NotificationCategoryFollows,
	NotificationCategoryMarketing,
}

func (e NotificationCategory) IsValid() bool {
	switch e {
	case NotificationCategoryTransactional, NotificationCategorySecurity, NotificationCategoryLowStock, NotificationCategoryFollows, NotificationCategoryMarketing:
		return true
	}
	return false
}

func (e NotificationCategory) String() string {
	return string(e)
}

func (e *NotificationCategory) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationCategory", str)
	}
	return nil
}

func (e NotificationCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
