// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, user_id, amount, currency, provider, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID  uuid.UUID `json:"order_id"`
	UserID   uuid.UUID `json:"user_id"`
	Amount   float64   `json:"amount"`
	Currency string    `json:"currency"`
	Provider string    `json:"provider"`
}

// CreatePayment
//
//	INSERT INTO payments (order_id, user_id, amount, currency, provider, status)
//	VALUES ($1, $2, $3, $4, $5, 'pending')
//	RETURNING id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Provider,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at FROM payments WHERE id = $1
`

// GetPayment
//
//	SELECT id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at FROM payments WHERE id = $1
func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at FROM payments WHERE order_id = $1
`

// GetPaymentByOrderID
//
//	SELECT id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at FROM payments WHERE order_id = $1
func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// UpdatePaymentStatus
//
//	UPDATE payments
//	SET status = $2, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at
func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentTransaction = `-- name: UpdatePaymentTransaction :one
UPDATE payments
SET status = $2, transaction_id = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at
`

type UpdatePaymentTransactionParams struct {
	ID            uuid.UUID `json:"id"`
	Status        string    `json:"status"`
	TransactionID *string   `json:"transaction_id"`
}

// UpdatePaymentTransaction
//
//	UPDATE payments
//	SET status = $2, transaction_id = $3, updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, order_id, user_id, amount, currency, provider, status, transaction_id, created_at, updated_at
func (q *Queries) UpdatePaymentTransaction(ctx context.Context, arg UpdatePaymentTransactionParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentTransaction, arg.ID, arg.Status, arg.TransactionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
