// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ProductCoPurchase struct {
	ProductAID      string             `json:"product_a_id"`
	ProductBID      string             `json:"product_b_id"`
	CoPurchaseCount pgtype.Int4        `json:"co_purchase_count"`
	LastPurchasedAt pgtype.Timestamptz `json:"last_purchased_at"`
}

type ProductView struct {
	ID           uuid.UUID          `json:"id"`
	BuyerID      string             `json:"buyer_id"`
	ProductID    string             `json:"product_id"`
	ViewCount    pgtype.Int4        `json:"view_count"`
	LastViewedAt pgtype.Timestamptz `json:"last_viewed_at"`
}
