// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

const getFrequentlyBoughtTogether = `-- name: GetFrequentlyBoughtTogether :many
SELECT product_b_id AS product_id, co_purchase_count AS score
FROM product_co_purchases
WHERE product_a_id = $1
ORDER BY co_purchase_count DESC
LIMIT $2
`

type GetFrequentlyBoughtTogetherParams struct {
	ProductAID string `json:"product_a_id"`
	Limit      int32  `json:"limit"`
}

type GetFrequentlyBoughtTogetherRow struct {
	ProductID string `json:"product_id"`
	Score     int32  `json:"score"`
}

func (q *Queries) GetFrequentlyBoughtTogether(ctx context.Context, arg GetFrequentlyBoughtTogetherParams) ([]GetFrequentlyBoughtTogetherRow, error) {
	rows, err := q.db.Query(ctx, getFrequentlyBoughtTogether, arg.ProductAID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFrequentlyBoughtTogetherRow
	for rows.Next() {
		var i GetFrequentlyBoughtTogetherRow
		if err := rows.Scan(&i.ProductID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentProductViews = `-- name: GetRecentProductViews :many
SELECT product_id
FROM product_views
WHERE buyer_id = $1
ORDER BY last_viewed_at DESC
LIMIT $2
`

type GetRecentProductViewsParams struct {
	BuyerID string `json:"buyer_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) GetRecentProductViews(ctx context.Context, arg GetRecentProductViewsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getRecentProductViews, arg.BuyerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var product_id string
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopProductsGlobally = `-- name: GetTopProductsGlobally :many
SELECT product_id, SUM(view_count) as score
FROM product_views
GROUP BY product_id
ORDER BY score DESC
LIMIT $1
`

type GetTopProductsGloballyRow struct {
	ProductID string `json:"product_id"`
	Score     int64  `json:"score"`
}

func (q *Queries) GetTopProductsGlobally(ctx context.Context, limit int32) ([]GetTopProductsGloballyRow, error) {
	rows, err := q.db.Query(ctx, getTopProductsGlobally, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopProductsGloballyRow
	for rows.Next() {
		var i GetTopProductsGloballyRow
		if err := rows.Scan(&i.ProductID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCoPurchase = `-- name: UpsertCoPurchase :exec
INSERT INTO product_co_purchases (product_a_id, product_b_id, co_purchase_count, last_purchased_at)
VALUES ($1, $2, 1, NOW())
ON CONFLICT (product_a_id, product_b_id)
DO UPDATE SET 
    co_purchase_count = product_co_purchases.co_purchase_count + 1,
    last_purchased_at = NOW()
`

type UpsertCoPurchaseParams struct {
	ProductAID string `json:"product_a_id"`
	ProductBID string `json:"product_b_id"`
}

func (q *Queries) UpsertCoPurchase(ctx context.Context, arg UpsertCoPurchaseParams) error {
	_, err := q.db.Exec(ctx, upsertCoPurchase, arg.ProductAID, arg.ProductBID)
	return err
}

const upsertProductView = `-- name: UpsertProductView :exec
INSERT INTO product_views (buyer_id, product_id, view_count, last_viewed_at)
VALUES ($1, $2, 1, NOW())
ON CONFLICT (buyer_id, product_id)
DO UPDATE SET 
    view_count = product_views.view_count + 1,
    last_viewed_at = NOW()
`

type UpsertProductViewParams struct {
	BuyerID   string `json:"buyer_id"`
	ProductID string `json:"product_id"`
}

func (q *Queries) UpsertProductView(ctx context.Context, arg UpsertProductViewParams) error {
	_, err := q.db.Exec(ctx, upsertProductView, arg.BuyerID, arg.ProductID)
	return err
}
