// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const batchGetMediaAssets = `-- name: BatchGetMediaAssets :many
SELECT id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at FROM media_assets
WHERE id = ANY($1::uuid[])
`

// BatchGetMediaAssets
//
//	SELECT id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at FROM media_assets
//	WHERE id = ANY($1::uuid[])
func (q *Queries) BatchGetMediaAssets(ctx context.Context, dollar_1 []uuid.UUID) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, batchGetMediaAssets, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ServiceScope,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.RawS3Key,
			&i.IsPrivate,
			&i.Status,
			&i.Variants,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMediaAssets = `-- name: CountMediaAssets :one
SELECT COUNT(*) FROM media_assets
WHERE owner_id = $1
  AND (CAST($2 AS varchar) IS NULL OR service_scope = $2)
  AND (CAST($3 AS varchar) IS NULL OR mime_type LIKE $3)
  AND (CAST($4 AS media_status) IS NULL OR status = $4)
`

type CountMediaAssetsParams struct {
	OwnerID      uuid.UUID    `json:"owner_id"`
	ServiceScope *string      `json:"service_scope"`
	MimeType     *string      `json:"mime_type"`
	Status       *MediaStatus `json:"status"`
}

// CountMediaAssets
//
//	SELECT COUNT(*) FROM media_assets
//	WHERE owner_id = $1
//	  AND (CAST($2 AS varchar) IS NULL OR service_scope = $2)
//	  AND (CAST($3 AS varchar) IS NULL OR mime_type LIKE $3)
//	  AND (CAST($4 AS media_status) IS NULL OR status = $4)
func (q *Queries) CountMediaAssets(ctx context.Context, arg CountMediaAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaAssets,
		arg.OwnerID,
		arg.ServiceScope,
		arg.MimeType,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (
    owner_id,
    service_scope,
    original_name,
    mime_type,
    size_bytes,
    raw_s3_key,
    is_private,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at
`

type CreateMediaAssetParams struct {
	OwnerID      uuid.UUID `json:"owner_id"`
	ServiceScope string    `json:"service_scope"`
	OriginalName string    `json:"original_name"`
	MimeType     string    `json:"mime_type"`
	SizeBytes    int64     `json:"size_bytes"`
	RawS3Key     string    `json:"raw_s3_key"`
	IsPrivate    bool      `json:"is_private"`
	Status       string    `json:"status"`
}

// CreateMediaAsset
//
//	INSERT INTO media_assets (
//	    owner_id,
//	    service_scope,
//	    original_name,
//	    mime_type,
//	    size_bytes,
//	    raw_s3_key,
//	    is_private,
//	    status
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6, $7, $8
//	) RETURNING id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at
func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.OwnerID,
		arg.ServiceScope,
		arg.OriginalName,
		arg.MimeType,
		arg.SizeBytes,
		arg.RawS3Key,
		arg.IsPrivate,
		arg.Status,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ServiceScope,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.RawS3Key,
		&i.IsPrivate,
		&i.Status,
		&i.Variants,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at FROM media_assets
WHERE id = $1
`

// GetMediaAsset
//
//	SELECT id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at FROM media_assets
//	WHERE id = $1
func (q *Queries) GetMediaAsset(ctx context.Context, id uuid.UUID) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAsset, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ServiceScope,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.RawS3Key,
		&i.IsPrivate,
		&i.Status,
		&i.Variants,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaAssets = `-- name: ListMediaAssets :many
SELECT id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at FROM media_assets
WHERE owner_id = $1
  AND (CAST($4 AS varchar) IS NULL OR service_scope = $4)
  AND (CAST($5 AS varchar) IS NULL OR mime_type LIKE $5)
  AND (CAST($6 AS media_status) IS NULL OR status = $6)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMediaAssetsParams struct {
	OwnerID      uuid.UUID    `json:"owner_id"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	ServiceScope *string      `json:"service_scope"`
	MimeType     *string      `json:"mime_type"`
	Status       *MediaStatus `json:"status"`
}

// ListMediaAssets
//
//	SELECT id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at FROM media_assets
//	WHERE owner_id = $1
//	  AND (CAST($4 AS varchar) IS NULL OR service_scope = $4)
//	  AND (CAST($5 AS varchar) IS NULL OR mime_type LIKE $5)
//	  AND (CAST($6 AS media_status) IS NULL OR status = $6)
//	ORDER BY created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListMediaAssets(ctx context.Context, arg ListMediaAssetsParams) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssets,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
		arg.ServiceScope,
		arg.MimeType,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ServiceScope,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.RawS3Key,
			&i.IsPrivate,
			&i.Status,
			&i.Variants,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaStatus = `-- name: UpdateMediaStatus :one
UPDATE media_assets
SET status = $2,
    error_message = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at
`

type UpdateMediaStatusParams struct {
	ID           uuid.UUID `json:"id"`
	Status       string    `json:"status"`
	ErrorMessage *string   `json:"error_message"`
}

// UpdateMediaStatus
//
//	UPDATE media_assets
//	SET status = $2,
//	    error_message = $3,
//	    updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at
func (q *Queries) UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, updateMediaStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ServiceScope,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.RawS3Key,
		&i.IsPrivate,
		&i.Status,
		&i.Variants,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaVariants = `-- name: UpdateMediaVariants :one
UPDATE media_assets
SET status = 'completed',
    variants = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at
`

type UpdateMediaVariantsParams struct {
	ID       uuid.UUID       `json:"id"`
	Variants json.RawMessage `json:"variants"`
}

// UpdateMediaVariants
//
//	UPDATE media_assets
//	SET status = 'completed',
//	    variants = $2,
//	    updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, owner_id, service_scope, original_name, mime_type, size_bytes, raw_s3_key, is_private, status, variants, error_message, created_at, updated_at
func (q *Queries) UpdateMediaVariants(ctx context.Context, arg UpdateMediaVariantsParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, updateMediaVariants, arg.ID, arg.Variants)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ServiceScope,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.RawS3Key,
		&i.IsPrivate,
		&i.Status,
		&i.Variants,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
