// Code generated by sqlc. DO NOT EDIT.
// Run `sqlc generate` to regenerate from db/queries/ and db/migrations/.

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// DBTX is the minimal interface shared by *pgxpool.Pool and pgx.Tx.
type DBTX interface {
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// New creates a Queries instance backed by any DBTX implementation.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// NewFromPool is a convenience constructor for *pgxpool.Pool.
func NewFromPool(pool *pgxpool.Pool) *Queries {
	return &Queries{db: pool}
}

// Queries holds a reference to the underlying database connection.
type Queries struct {
	db DBTX
}

// WithTx returns a new Queries scoped to the given transaction.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
