// Code generated by sqlc. DO NOT EDIT.
// Run `sqlc generate` to regenerate from db/queries/ and db/migrations/.

package db

import (
	"time"

	"github.com/google/uuid"
)

// PaymentTransaction represents a row in the payment_transactions table.
type PaymentTransaction struct {
	ID                    uuid.UUID  `json:"id"`
	OrderID               uuid.UUID  `json:"order_id"`
	ClientCorrelator      string     `json:"client_correlator"`
	ReferenceCode         string     `json:"reference_code"`
	TranType              string     `json:"tran_type"`
	EndUserIDMasked       string     `json:"end_user_id_masked"`
	AmountCents           int64      `json:"amount_cents"`
	Currency              string     `json:"currency"`
	Status                string     `json:"status"`
	EcocashStatusCode     *string    `json:"ecocash_status_code"`
	EcocashStatusMsg      *string    `json:"ecocash_status_msg"`
	EcocashTransactionID  *string    `json:"ecocash_transaction_id"`
	RawRequest            []byte     `json:"raw_request"`
	RawResponse           []byte     `json:"raw_response"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

// RefundTransaction represents a row in the refund_transactions table.
type RefundTransaction struct {
	ID                   uuid.UUID `json:"id"`
	OriginalTxnID        uuid.UUID `json:"original_txn_id"`
	ClientCorrelator     string    `json:"client_correlator"`
	TranType             string    `json:"tran_type"`
	AmountCents          int64     `json:"amount_cents"`
	Status               string    `json:"status"`
	EcocashStatusCode    *string   `json:"ecocash_status_code"`
	EcocashStatusMsg     *string   `json:"ecocash_status_msg"`
	RawRequest           []byte    `json:"raw_request"`
	RawResponse          []byte    `json:"raw_response"`
	CreatedAt            time.Time `json:"created_at"`
}

// Payout represents a row in the payouts table.
type Payout struct {
	ID          uuid.UUID `json:"id"`
	SellerID    uuid.UUID `json:"seller_id"`
	AmountCents int64     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	Status      string    `json:"status"`
	Method      string    `json:"method"`
	ProviderRef *string   `json:"provider_ref"`
	RawResponse []byte    `json:"raw_response"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// OutboxEvent represents a row in the outbox_events table.
type OutboxEvent struct {
	ID          uuid.UUID `json:"id"`
	AggregateID uuid.UUID `json:"aggregate_id"`
	EventType   string    `json:"event_type"`
	Payload     []byte    `json:"payload"`
	Published   bool      `json:"published"`
	CreatedAt   time.Time `json:"created_at"`
}
