// Code generated by sqlc. DO NOT EDIT.
// Run `sqlc generate` to regenerate from db/queries/ and db/migrations/.

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// ── payment_transactions ──────────────────────────────────────────────────────

type CreateTransactionParams struct {
	OrderID          uuid.UUID `json:"order_id"`
	ClientCorrelator string    `json:"client_correlator"`
	TranType         string    `json:"tran_type"`
	EndUserIDMasked  string    `json:"end_user_id_masked"`
	AmountCents      int64     `json:"amount_cents"`
	Currency         string    `json:"currency"`
	RawRequest       []byte    `json:"raw_request"`
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO payment_transactions (
    order_id, client_correlator, tran_type,
    end_user_id_masked, amount_cents, currency,
    status, raw_request
) VALUES ($1, $2, $3, $4, $5, $6, 'PENDING', $7)
RETURNING id, order_id, client_correlator, reference_code, tran_type,
          end_user_id_masked, amount_cents, currency, status,
          ecocash_status_code, ecocash_status_msg, ecocash_transaction_id,
          raw_request, raw_response, created_at, updated_at`

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.OrderID, arg.ClientCorrelator, arg.TranType,
		arg.EndUserIDMasked, arg.AmountCents, arg.Currency, arg.RawRequest,
	)
	return scanPaymentTransaction(row)
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, order_id, client_correlator, reference_code, tran_type,
       end_user_id_masked, amount_cents, currency, status,
       ecocash_status_code, ecocash_status_msg, ecocash_transaction_id,
       raw_request, raw_response, created_at, updated_at
FROM payment_transactions WHERE id = $1`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	return scanPaymentTransaction(row)
}

const getTransactionByCorrelator = `-- name: GetTransactionByCorrelator :one
SELECT id, order_id, client_correlator, reference_code, tran_type,
       end_user_id_masked, amount_cents, currency, status,
       ecocash_status_code, ecocash_status_msg, ecocash_transaction_id,
       raw_request, raw_response, created_at, updated_at
FROM payment_transactions WHERE client_correlator = $1`

func (q *Queries) GetTransactionByCorrelator(ctx context.Context, correlator string) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByCorrelator, correlator)
	return scanPaymentTransaction(row)
}

const listTransactionsByOrder = `-- name: ListTransactionsByOrder :many
SELECT id, order_id, client_correlator, reference_code, tran_type,
       end_user_id_masked, amount_cents, currency, status,
       ecocash_status_code, ecocash_status_msg, ecocash_transaction_id,
       raw_request, raw_response, created_at, updated_at
FROM payment_transactions
WHERE order_id = $1
ORDER BY created_at DESC`

func (q *Queries) ListTransactionsByOrder(ctx context.Context, orderID uuid.UUID) ([]PaymentTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentTransaction
	for rows.Next() {
		t, err := scanPaymentTransaction(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	return items, rows.Err()
}

type UpdateTransactionStatusParams struct {
	ID                   uuid.UUID `json:"id"`
	Status               string    `json:"status"`
	EcocashStatusCode    *string   `json:"ecocash_status_code"`
	EcocashStatusMsg     *string   `json:"ecocash_status_msg"`
	EcocashTransactionID *string   `json:"ecocash_transaction_id"`
	ReferenceCode        string    `json:"reference_code"`
	RawResponse          []byte    `json:"raw_response"`
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE payment_transactions
SET
    status                 = $2,
    ecocash_status_code    = $3,
    ecocash_status_msg     = $4,
    ecocash_transaction_id = $5,
    reference_code         = COALESCE(NULLIF($6, ''), reference_code),
    raw_response           = $7,
    updated_at             = NOW()
WHERE id = $1
RETURNING id, order_id, client_correlator, reference_code, tran_type,
          end_user_id_masked, amount_cents, currency, status,
          ecocash_status_code, ecocash_status_msg, ecocash_transaction_id,
          raw_request, raw_response, created_at, updated_at`

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus,
		arg.ID, arg.Status, arg.EcocashStatusCode, arg.EcocashStatusMsg,
		arg.EcocashTransactionID, arg.ReferenceCode, arg.RawResponse,
	)
	return scanPaymentTransaction(row)
}

const listStalePendingTransactions = `-- name: ListStalePendingTransactions :many
SELECT id, order_id, client_correlator, reference_code, tran_type,
       end_user_id_masked, amount_cents, currency, status,
       ecocash_status_code, ecocash_status_msg, ecocash_transaction_id,
       raw_request, raw_response, created_at, updated_at
FROM payment_transactions
WHERE status = 'PENDING' AND created_at < $1
ORDER BY created_at ASC
LIMIT 100`

func (q *Queries) ListStalePendingTransactions(ctx context.Context, threshold time.Time) ([]PaymentTransaction, error) {
	rows, err := q.db.Query(ctx, listStalePendingTransactions, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentTransaction
	for rows.Next() {
		t, err := scanPaymentTransaction(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	return items, rows.Err()
}

type GetExistingPendingChargeParams struct {
	OrderID  uuid.UUID `json:"order_id"`
	TranType string    `json:"tran_type"`
}

const getExistingPendingCharge = `-- name: GetExistingPendingCharge :one
SELECT id, order_id, client_correlator, reference_code, tran_type,
       end_user_id_masked, amount_cents, currency, status,
       ecocash_status_code, ecocash_status_msg, ecocash_transaction_id,
       raw_request, raw_response, created_at, updated_at
FROM payment_transactions
WHERE order_id = $1 AND tran_type = $2 AND status = 'PENDING'
ORDER BY created_at DESC
LIMIT 1`

func (q *Queries) GetExistingPendingCharge(ctx context.Context, arg GetExistingPendingChargeParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getExistingPendingCharge, arg.OrderID, arg.TranType)
	return scanPaymentTransaction(row)
}

// ── refund_transactions ───────────────────────────────────────────────────────

type CreateRefundTransactionParams struct {
	OriginalTxnID    uuid.UUID `json:"original_txn_id"`
	ClientCorrelator string    `json:"client_correlator"`
	TranType         string    `json:"tran_type"`
	AmountCents      int64     `json:"amount_cents"`
	RawRequest       []byte    `json:"raw_request"`
}

const createRefundTransaction = `-- name: CreateRefundTransaction :one
INSERT INTO refund_transactions (
    original_txn_id, client_correlator, tran_type,
    amount_cents, status, raw_request
) VALUES ($1, $2, $3, $4, 'PENDING', $5)
RETURNING id, original_txn_id, client_correlator, tran_type, amount_cents,
          status, ecocash_status_code, ecocash_status_msg, raw_request, raw_response, created_at`

func (q *Queries) CreateRefundTransaction(ctx context.Context, arg CreateRefundTransactionParams) (RefundTransaction, error) {
	row := q.db.QueryRow(ctx, createRefundTransaction,
		arg.OriginalTxnID, arg.ClientCorrelator, arg.TranType,
		arg.AmountCents, arg.RawRequest,
	)
	return scanRefundTransaction(row)
}

const getRefundByID = `-- name: GetRefundByID :one
SELECT id, original_txn_id, client_correlator, tran_type, amount_cents,
       status, ecocash_status_code, ecocash_status_msg, raw_request, raw_response, created_at
FROM refund_transactions WHERE id = $1`

func (q *Queries) GetRefundByID(ctx context.Context, id uuid.UUID) (RefundTransaction, error) {
	row := q.db.QueryRow(ctx, getRefundByID, id)
	return scanRefundTransaction(row)
}

const sumRefundedAmountForTxn = `-- name: SumRefundedAmountForTxn :one
SELECT COALESCE(SUM(amount_cents), 0)::BIGINT AS total_refunded
FROM refund_transactions
WHERE original_txn_id = $1 AND status = 'SUCCESS'`

func (q *Queries) SumRefundedAmountForTxn(ctx context.Context, originalTxnID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumRefundedAmountForTxn, originalTxnID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

type UpdateRefundStatusParams struct {
	ID                uuid.UUID `json:"id"`
	Status            string    `json:"status"`
	EcocashStatusCode *string   `json:"ecocash_status_code"`
	EcocashStatusMsg  *string   `json:"ecocash_status_msg"`
	RawResponse       []byte    `json:"raw_response"`
}

const updateRefundStatus = `-- name: UpdateRefundStatus :one
UPDATE refund_transactions
SET
    status              = $2,
    ecocash_status_code = $3,
    ecocash_status_msg  = $4,
    raw_response        = $5
WHERE id = $1
RETURNING id, original_txn_id, client_correlator, tran_type, amount_cents,
          status, ecocash_status_code, ecocash_status_msg, raw_request, raw_response, created_at`

func (q *Queries) UpdateRefundStatus(ctx context.Context, arg UpdateRefundStatusParams) (RefundTransaction, error) {
	row := q.db.QueryRow(ctx, updateRefundStatus,
		arg.ID, arg.Status, arg.EcocashStatusCode, arg.EcocashStatusMsg, arg.RawResponse,
	)
	return scanRefundTransaction(row)
}

// ── payouts ───────────────────────────────────────────────────────────────────

type CreatePayoutParams struct {
	SellerID    uuid.UUID `json:"seller_id"`
	AmountCents int64     `json:"amount_cents"`
	Currency    string    `json:"currency"`
}

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (seller_id, amount_cents, currency, status, method)
VALUES ($1, $2, $3, 'QUEUED', 'manual_bulk')
RETURNING id, seller_id, amount_cents, currency, status, method, provider_ref, raw_response, created_at, updated_at`

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout, arg.SellerID, arg.AmountCents, arg.Currency)
	return scanPayout(row)
}

const getPayoutByID = `-- name: GetPayoutByID :one
SELECT id, seller_id, amount_cents, currency, status, method, provider_ref, raw_response, created_at, updated_at
FROM payouts WHERE id = $1`

func (q *Queries) GetPayoutByID(ctx context.Context, id uuid.UUID) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayoutByID, id)
	return scanPayout(row)
}

type UpdatePayoutStatusParams struct {
	ID          uuid.UUID `json:"id"`
	Status      string    `json:"status"`
	ProviderRef *string   `json:"provider_ref"`
}

const updatePayoutStatus = `-- name: UpdatePayoutStatus :one
UPDATE payouts
SET
    status       = $2,
    provider_ref = $3,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, seller_id, amount_cents, currency, status, method, provider_ref, raw_response, created_at, updated_at`

func (q *Queries) UpdatePayoutStatus(ctx context.Context, arg UpdatePayoutStatusParams) (Payout, error) {
	row := q.db.QueryRow(ctx, updatePayoutStatus, arg.ID, arg.Status, arg.ProviderRef)
	return scanPayout(row)
}

// ── outbox_events ─────────────────────────────────────────────────────────────

type CreateOutboxEventParams struct {
	AggregateID uuid.UUID `json:"aggregate_id"`
	EventType   string    `json:"event_type"`
	Payload     []byte    `json:"payload"`
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (aggregate_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, aggregate_id, event_type, payload, published, created_at`

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.AggregateID, arg.EventType, arg.Payload)
	var e OutboxEvent
	err := row.Scan(&e.ID, &e.AggregateID, &e.EventType, &e.Payload, &e.Published, &e.CreatedAt)
	return e, err
}

const listUnpublishedOutboxEvents = `-- name: ListUnpublishedOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, published, created_at
FROM outbox_events
WHERE published = false
ORDER BY created_at ASC
LIMIT 50`

func (q *Queries) ListUnpublishedOutboxEvents(ctx context.Context) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var e OutboxEvent
		if err := rows.Scan(&e.ID, &e.AggregateID, &e.EventType, &e.Payload, &e.Published, &e.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, e)
	}
	return items, rows.Err()
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events SET published = true WHERE id = $1`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
// ── scanners ──────────────────────────────────────────────────────────────────

type scanner interface {
	Scan(dest ...any) error
}

func scanPaymentTransaction(row scanner) (PaymentTransaction, error) {
	var t PaymentTransaction
	err := row.Scan(
		&t.ID, &t.OrderID, &t.ClientCorrelator, &t.ReferenceCode, &t.TranType,
		&t.EndUserIDMasked, &t.AmountCents, &t.Currency, &t.Status,
		&t.EcocashStatusCode, &t.EcocashStatusMsg, &t.EcocashTransactionID,
		&t.RawRequest, &t.RawResponse, &t.CreatedAt, &t.UpdatedAt,
	)
	return t, err
}

func scanRefundTransaction(row scanner) (RefundTransaction, error) {
	var r RefundTransaction
	err := row.Scan(
		&r.ID, &r.OriginalTxnID, &r.ClientCorrelator, &r.TranType, &r.AmountCents,
		&r.Status, &r.EcocashStatusCode, &r.EcocashStatusMsg, &r.RawRequest, &r.RawResponse, &r.CreatedAt,
	)
	return r, err
}

func scanPayout(row scanner) (Payout, error) {
	var p Payout
	err := row.Scan(
		&p.ID, &p.SellerID, &p.AmountCents, &p.Currency, &p.Status,
		&p.Method, &p.ProviderRef, &p.RawResponse, &p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}
