// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/google/uuid"
)

type Thread struct {
	ID        uuid.UUID          `json:"id"`
	Type      string             `json:"type"`
	Title     pgtype.Text        `json:"title"`
	BuyerID   pgtype.Text        `json:"buyer_id"`
	SellerID  string             `json:"seller_id"`
	OrderID   pgtype.Text        `json:"order_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID          uuid.UUID          `json:"id"`
	ThreadID    uuid.UUID          `json:"thread_id"`
	SenderID    string             `json:"sender_id"`
	Type        string             `json:"type"`
	Content     string             `json:"content"`
	MediaUrl    pgtype.Text        `json:"media_url"`
	ReferenceID pgtype.Text        `json:"reference_id"`
	IsRead      bool               `json:"is_read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
