// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addThreadMember = `-- name: AddThreadMember :exec
INSERT INTO thread_members (
  thread_id, user_id, role
) VALUES (
  $1, $2, $3
)
ON CONFLICT (thread_id, user_id) DO NOTHING
`

type AddThreadMemberParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	UserID   string    `json:"user_id"`
	Role     string    `json:"role"`
}

func (q *Queries) AddThreadMember(ctx context.Context, arg AddThreadMemberParams) error {
	_, err := q.db.ExecContext(ctx, addThreadMember, arg.ThreadID, arg.UserID, arg.Role)
	return err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  thread_id, sender_id, type, content, media_url, reference_id, metadata
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, thread_id, sender_id, type, content, media_url, reference_id, is_read, created_at, metadata
`

type CreateMessageParams struct {
	ThreadID    uuid.UUID             `json:"thread_id"`
	SenderID    string                `json:"sender_id"`
	Type        string                `json:"type"`
	Content     string                `json:"content"`
	MediaUrl    sql.NullString        `json:"media_url"`
	ReferenceID sql.NullString        `json:"reference_id"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ThreadID,
		arg.SenderID,
		arg.Type,
		arg.Content,
		arg.MediaUrl,
		arg.ReferenceID,
		arg.Metadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.SenderID,
		&i.Type,
		&i.Content,
		&i.MediaUrl,
		&i.ReferenceID,
		&i.IsRead,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO threads (
  type, title, buyer_id, seller_id, order_id, delivery_boy_id, courier_station_id, support_agent_id, participant_avatar
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, type, title, buyer_id, seller_id, order_id, created_at, updated_at, delivery_boy_id, courier_station_id, support_agent_id, participant_avatar
`

type CreateThreadParams struct {
	Type              string         `json:"type"`
	Title             sql.NullString `json:"title"`
	BuyerID           sql.NullString `json:"buyer_id"`
	SellerID          sql.NullString `json:"seller_id"`
	OrderID           sql.NullString `json:"order_id"`
	DeliveryBoyID     sql.NullString `json:"delivery_boy_id"`
	CourierStationID  sql.NullString `json:"courier_station_id"`
	SupportAgentID    sql.NullString `json:"support_agent_id"`
	ParticipantAvatar sql.NullString `json:"participant_avatar"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, createThread,
		arg.Type,
		arg.Title,
		arg.BuyerID,
		arg.SellerID,
		arg.OrderID,
		arg.DeliveryBoyID,
		arg.CourierStationID,
		arg.SupportAgentID,
		arg.ParticipantAvatar,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryBoyID,
		&i.CourierStationID,
		&i.SupportAgentID,
		&i.ParticipantAvatar,
	)
	return i, err
}

const getBroadcastThreadForSeller = `-- name: GetBroadcastThreadForSeller :one
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at, delivery_boy_id, courier_station_id, support_agent_id, participant_avatar FROM threads
WHERE seller_id = $1 AND type = 'THREAD_TYPE_BROADCAST'
LIMIT 1
`

func (q *Queries) GetBroadcastThreadForSeller(ctx context.Context, sellerID sql.NullString) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getBroadcastThreadForSeller, sellerID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryBoyID,
		&i.CourierStationID,
		&i.SupportAgentID,
		&i.ParticipantAvatar,
	)
	return i, err
}

const getSystemThread = `-- name: GetSystemThread :one
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at, delivery_boy_id, courier_station_id, support_agent_id, participant_avatar FROM threads
WHERE type = 'THREAD_TYPE_SYSTEM'
LIMIT 1
`

func (q *Queries) GetSystemThread(ctx context.Context) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getSystemThread)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryBoyID,
		&i.CourierStationID,
		&i.SupportAgentID,
		&i.ParticipantAvatar,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at, delivery_boy_id, courier_station_id, support_agent_id, participant_avatar FROM threads
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetThread(ctx context.Context, id uuid.UUID) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryBoyID,
		&i.CourierStationID,
		&i.SupportAgentID,
		&i.ParticipantAvatar,
	)
	return i, err
}

const isThreadMember = `-- name: IsThreadMember :one
SELECT EXISTS (
  SELECT 1 FROM thread_members
  WHERE thread_id = $1 AND user_id = $2
)
`

type IsThreadMemberParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	UserID   string    `json:"user_id"`
}

func (q *Queries) IsThreadMember(ctx context.Context, arg IsThreadMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isThreadMember, arg.ThreadID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBroadcastThreadsForSellers = `-- name: ListBroadcastThreadsForSellers :many
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at, delivery_boy_id, courier_station_id, support_agent_id, participant_avatar FROM threads
WHERE seller_id = ANY($1::varchar[]) AND type = 'THREAD_TYPE_BROADCAST'
ORDER BY updated_at DESC
`

func (q *Queries) ListBroadcastThreadsForSellers(ctx context.Context, dollar_1 []string) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcastThreadsForSellers, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.BuyerID,
			&i.SellerID,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveryBoyID,
			&i.CourierStationID,
			&i.SupportAgentID,
			&i.ParticipantAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectThreadsForBuyer = `-- name: ListDirectThreadsForBuyer :many
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at, delivery_boy_id, courier_station_id, support_agent_id, participant_avatar FROM threads
WHERE buyer_id = $1 AND type = 'THREAD_TYPE_DIRECT'
ORDER BY updated_at DESC
`

func (q *Queries) ListDirectThreadsForBuyer(ctx context.Context, buyerID sql.NullString) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listDirectThreadsForBuyer, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.BuyerID,
			&i.SellerID,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveryBoyID,
			&i.CourierStationID,
			&i.SupportAgentID,
			&i.ParticipantAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, thread_id, sender_id, type, content, media_url, reference_id, is_read, created_at, metadata FROM messages
WHERE thread_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessages(ctx context.Context, threadID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.SenderID,
			&i.Type,
			&i.Content,
			&i.MediaUrl,
			&i.ReferenceID,
			&i.IsRead,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMembers = `-- name: ListThreadMembers :many
SELECT user_id FROM thread_members
WHERE thread_id = $1
`

func (q *Queries) ListThreadMembers(ctx context.Context, threadID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listThreadMembers, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForSeller = `-- name: ListThreadsForSeller :many
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at, delivery_boy_id, courier_station_id, support_agent_id, participant_avatar FROM threads
WHERE seller_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListThreadsForSeller(ctx context.Context, sellerID sql.NullString) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreadsForSeller, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.BuyerID,
			&i.SellerID,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveryBoyID,
			&i.CourierStationID,
			&i.SupportAgentID,
			&i.ParticipantAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForUser = `-- name: ListThreadsForUser :many
SELECT DISTINCT t.id, t.type, t.title, t.buyer_id, t.seller_id, t.order_id, t.created_at, t.updated_at, t.delivery_boy_id, t.courier_station_id, t.support_agent_id, t.participant_avatar FROM threads t
LEFT JOIN thread_members tm ON t.id = tm.thread_id
WHERE t.buyer_id = $1 
   OR t.seller_id = $1 
   OR t.delivery_boy_id = $1 
   OR t.courier_station_id = $1 
   OR t.support_agent_id = $1 
   OR tm.user_id = $1
ORDER BY t.updated_at DESC
`

func (q *Queries) ListThreadsForUser(ctx context.Context, buyerID sql.NullString) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreadsForUser, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.BuyerID,
			&i.SellerID,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveryBoyID,
			&i.CourierStationID,
			&i.SupportAgentID,
			&i.ParticipantAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeThreadMember = `-- name: RemoveThreadMember :exec
DELETE FROM thread_members
WHERE thread_id = $1 AND user_id = $2
`

type RemoveThreadMemberParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	UserID   string    `json:"user_id"`
}

func (q *Queries) RemoveThreadMember(ctx context.Context, arg RemoveThreadMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeThreadMember, arg.ThreadID, arg.UserID)
	return err
}

const updateThreadTimestamp = `-- name: UpdateThreadTimestamp :exec
UPDATE threads
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateThreadTimestamp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateThreadTimestamp, id)
	return err
}
