// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  thread_id, sender_id, type, content, media_url, reference_id
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, thread_id, sender_id, type, content, media_url, reference_id, is_read, created_at
`

type CreateMessageParams struct {
	ThreadID    uuid.UUID   `json:"thread_id"`
	SenderID    string      `json:"sender_id"`
	Type        string      `json:"type"`
	Content     string      `json:"content"`
	MediaUrl    pgtype.Text `json:"media_url"`
	ReferenceID pgtype.Text `json:"reference_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ThreadID,
		arg.SenderID,
		arg.Type,
		arg.Content,
		arg.MediaUrl,
		arg.ReferenceID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.SenderID,
		&i.Type,
		&i.Content,
		&i.MediaUrl,
		&i.ReferenceID,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO threads (
  type, title, buyer_id, seller_id, order_id
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, type, title, buyer_id, seller_id, order_id, created_at, updated_at
`

type CreateThreadParams struct {
	Type     string      `json:"type"`
	Title    pgtype.Text `json:"title"`
	BuyerID  pgtype.Text `json:"buyer_id"`
	SellerID string      `json:"seller_id"`
	OrderID  pgtype.Text `json:"order_id"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.Type,
		arg.Title,
		arg.BuyerID,
		arg.SellerID,
		arg.OrderID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBroadcastThreadForSeller = `-- name: GetBroadcastThreadForSeller :one
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at FROM threads
WHERE seller_id = $1 AND type = 'THREAD_TYPE_BROADCAST'
LIMIT 1
`

func (q *Queries) GetBroadcastThreadForSeller(ctx context.Context, sellerID string) (Thread, error) {
	row := q.db.QueryRow(ctx, getBroadcastThreadForSeller, sellerID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at FROM threads
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetThread(ctx context.Context, id uuid.UUID) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBroadcastThreadsForSellers = `-- name: ListBroadcastThreadsForSellers :many
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at FROM threads
WHERE seller_id = ANY($1::varchar[]) AND type = 'THREAD_TYPE_BROADCAST'
ORDER BY updated_at DESC
`

func (q *Queries) ListBroadcastThreadsForSellers(ctx context.Context, dollar_1 []string) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listBroadcastThreadsForSellers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.BuyerID,
			&i.SellerID,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectThreadsForBuyer = `-- name: ListDirectThreadsForBuyer :many
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at FROM threads
WHERE buyer_id = $1 AND type = 'THREAD_TYPE_DIRECT'
ORDER BY updated_at DESC
`

func (q *Queries) ListDirectThreadsForBuyer(ctx context.Context, buyerID pgtype.Text) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listDirectThreadsForBuyer, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.BuyerID,
			&i.SellerID,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, thread_id, sender_id, type, content, media_url, reference_id, is_read, created_at FROM messages
WHERE thread_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessages(ctx context.Context, threadID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.SenderID,
			&i.Type,
			&i.Content,
			&i.MediaUrl,
			&i.ReferenceID,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForSeller = `-- name: ListThreadsForSeller :many
SELECT id, type, title, buyer_id, seller_id, order_id, created_at, updated_at FROM threads
WHERE seller_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListThreadsForSeller(ctx context.Context, sellerID string) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreadsForSeller, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.BuyerID,
			&i.SellerID,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThreadTimestamp = `-- name: UpdateThreadTimestamp :exec
UPDATE threads
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateThreadTimestamp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateThreadTimestamp, id)
	return err
}
