// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSellerSuspension = `-- name: CreateSellerSuspension :one
INSERT INTO seller_suspensions (seller_id, reason, admin_id)
VALUES ($1, $2, $3)
RETURNING id, seller_id, reason, admin_id, created_at
`

type CreateSellerSuspensionParams struct {
	SellerID uuid.UUID `json:"seller_id"`
	Reason   string    `json:"reason"`
	AdminID  uuid.UUID `json:"admin_id"`
}

// CreateSellerSuspension
//
//	INSERT INTO seller_suspensions (seller_id, reason, admin_id)
//	VALUES ($1, $2, $3)
//	RETURNING id, seller_id, reason, admin_id, created_at
func (q *Queries) CreateSellerSuspension(ctx context.Context, arg CreateSellerSuspensionParams) (SellerSuspension, error) {
	row := q.db.QueryRow(ctx, createSellerSuspension, arg.SellerID, arg.Reason, arg.AdminID)
	var i SellerSuspension
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Reason,
		&i.AdminID,
		&i.CreatedAt,
	)
	return i, err
}

const createUserBan = `-- name: CreateUserBan :one
INSERT INTO user_bans (user_id, reason, admin_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, reason, admin_id, created_at
`

type CreateUserBanParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Reason  string    `json:"reason"`
	AdminID uuid.UUID `json:"admin_id"`
}

// CreateUserBan
//
//	INSERT INTO user_bans (user_id, reason, admin_id)
//	VALUES ($1, $2, $3)
//	RETURNING id, user_id, reason, admin_id, created_at
func (q *Queries) CreateUserBan(ctx context.Context, arg CreateUserBanParams) (UserBan, error) {
	row := q.db.QueryRow(ctx, createUserBan, arg.UserID, arg.Reason, arg.AdminID)
	var i UserBan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reason,
		&i.AdminID,
		&i.CreatedAt,
	)
	return i, err
}
