// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type SellerSuspension struct {
	ID        uuid.UUID `json:"id"`
	SellerID  uuid.UUID `json:"seller_id"`
	Reason    string    `json:"reason"`
	AdminID   uuid.UUID `json:"admin_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserBan struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Reason    string    `json:"reason"`
	AdminID   uuid.UUID `json:"admin_id"`
	CreatedAt time.Time `json:"created_at"`
}
