// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryStatus string

const (
	DeliveryStatusQueued   DeliveryStatus = "queued"
	DeliveryStatusSent     DeliveryStatus = "sent"
	DeliveryStatusFailed   DeliveryStatus = "failed"
	DeliveryStatusRetrying DeliveryStatus = "retrying"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type NotificationCategory string

const (
	NotificationCategoryTransactional NotificationCategory = "transactional"
	NotificationCategorySecurity      NotificationCategory = "security"
	NotificationCategoryLowStock      NotificationCategory = "low_stock"
	NotificationCategoryFollows       NotificationCategory = "follows"
	NotificationCategoryMarketing     NotificationCategory = "marketing"
)

func (e *NotificationCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationCategory(s)
	case string:
		*e = NotificationCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationCategory: %T", src)
	}
	return nil
}

type NullNotificationCategory struct {
	NotificationCategory NotificationCategory `json:"notification_category"`
	Valid                bool                 `json:"valid"` // Valid is true if NotificationCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationCategory) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationCategory), nil
}

type NotificationLog struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Category     string             `json:"category"`
	Channel      string             `json:"channel"`
	Recipient    string             `json:"recipient"`
	Title        string             `json:"title"`
	Content      string             `json:"content"`
	Status       DeliveryStatus     `json:"status"`
	RetryCount   int32              `json:"retry_count"`
	ErrorMessage *string            `json:"error_message"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type PushNotification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Payload   []byte             `json:"payload"`
	IsRead    bool               `json:"is_read"`
	CreatedAt time.Time          `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type UserDeviceToken struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Token      string    `json:"token"`
	Platform   string    `json:"platform"`
	DeviceName *string   `json:"device_name"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type UserNotificationPreference struct {
	ID           uuid.UUID            `json:"id"`
	UserID       uuid.UUID            `json:"user_id"`
	Category     NotificationCategory `json:"category"`
	EmailEnabled bool                 `json:"email_enabled"`
	PushEnabled  bool                 `json:"push_enabled"`
	CreatedAt    time.Time            `json:"created_at"`
	UpdatedAt    time.Time            `json:"updated_at"`
}
