// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationLog = `-- name: CreateNotificationLog :one
INSERT INTO notification_logs (user_id, category, channel, recipient, title, content, status, retry_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, category, channel, recipient, title, content, status, retry_count, error_message, sent_at, created_at, updated_at
`

type CreateNotificationLogParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Category   string         `json:"category"`
	Channel    string         `json:"channel"`
	Recipient  string         `json:"recipient"`
	Title      string         `json:"title"`
	Content    string         `json:"content"`
	Status     DeliveryStatus `json:"status"`
	RetryCount int32          `json:"retry_count"`
}

// CreateNotificationLog
//
//	INSERT INTO notification_logs (user_id, category, channel, recipient, title, content, status, retry_count)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING id, user_id, category, channel, recipient, title, content, status, retry_count, error_message, sent_at, created_at, updated_at
func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, createNotificationLog,
		arg.UserID,
		arg.Category,
		arg.Channel,
		arg.Recipient,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.RetryCount,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Channel,
		&i.Recipient,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPushNotification = `-- name: CreatePushNotification :one
INSERT INTO push_notifications (user_id, token, title, body, payload, is_read)
VALUES ($1, $2, $3, $4, $5, FALSE)
RETURNING id, user_id, token, title, body, payload, is_read, created_at, read_at
`

type CreatePushNotificationParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Token   string    `json:"token"`
	Title   string    `json:"title"`
	Body    string    `json:"body"`
	Payload []byte    `json:"payload"`
}

// CreatePushNotification
//
//	INSERT INTO push_notifications (user_id, token, title, body, payload, is_read)
//	VALUES ($1, $2, $3, $4, $5, FALSE)
//	RETURNING id, user_id, token, title, body, payload, is_read, created_at, read_at
func (q *Queries) CreatePushNotification(ctx context.Context, arg CreatePushNotificationParams) (PushNotification, error) {
	row := q.db.QueryRow(ctx, createPushNotification,
		arg.UserID,
		arg.Token,
		arg.Title,
		arg.Body,
		arg.Payload,
	)
	var i PushNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM user_device_tokens
WHERE user_id = $1 AND token = $2
`

type DeleteDeviceTokenParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

// DeleteDeviceToken
//
//	DELETE FROM user_device_tokens
//	WHERE user_id = $1 AND token = $2
func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.UserID, arg.Token)
	return err
}

const getDeviceTokensByUser = `-- name: GetDeviceTokensByUser :many
SELECT id, user_id, token, platform, device_name, created_at, updated_at FROM user_device_tokens
WHERE user_id = $1
`

// GetDeviceTokensByUser
//
//	SELECT id, user_id, token, platform, device_name, created_at, updated_at FROM user_device_tokens
//	WHERE user_id = $1
func (q *Queries) GetDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]UserDeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDeviceToken
	for rows.Next() {
		var i UserDeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.DeviceName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceTokensByUsers = `-- name: GetDeviceTokensByUsers :many
SELECT id, user_id, token, platform, device_name, created_at, updated_at FROM user_device_tokens
WHERE user_id = ANY($1::uuid[])
`

// GetDeviceTokensByUsers
//
//	SELECT id, user_id, token, platform, device_name, created_at, updated_at FROM user_device_tokens
//	WHERE user_id = ANY($1::uuid[])
func (q *Queries) GetDeviceTokensByUsers(ctx context.Context, dollar_1 []uuid.UUID) ([]UserDeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensByUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDeviceToken
	for rows.Next() {
		var i UserDeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.DeviceName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationPreference = `-- name: GetNotificationPreference :one
SELECT id, user_id, category, email_enabled, push_enabled, created_at, updated_at FROM user_notification_preferences
WHERE user_id = $1 AND category = $2
`

type GetNotificationPreferenceParams struct {
	UserID   uuid.UUID            `json:"user_id"`
	Category NotificationCategory `json:"category"`
}

// GetNotificationPreference
//
//	SELECT id, user_id, category, email_enabled, push_enabled, created_at, updated_at FROM user_notification_preferences
//	WHERE user_id = $1 AND category = $2
func (q *Queries) GetNotificationPreference(ctx context.Context, arg GetNotificationPreferenceParams) (UserNotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreference, arg.UserID, arg.Category)
	var i UserNotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :many
SELECT id, user_id, category, email_enabled, push_enabled, created_at, updated_at FROM user_notification_preferences
WHERE user_id = $1
`

// GetNotificationPreferences
//
//	SELECT id, user_id, category, email_enabled, push_enabled, created_at, updated_at FROM user_notification_preferences
//	WHERE user_id = $1
func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) ([]UserNotificationPreference, error) {
	rows, err := q.db.Query(ctx, getNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserNotificationPreference
	for rows.Next() {
		var i UserNotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.EmailEnabled,
			&i.PushEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLogs = `-- name: ListNotificationLogs :many
SELECT id, user_id, category, channel, recipient, title, content, status, retry_count, error_message, sent_at, created_at, updated_at FROM notification_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationLogsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

// ListNotificationLogs
//
//	SELECT id, user_id, category, channel, recipient, title, content, status, retry_count, error_message, sent_at, created_at, updated_at FROM notification_logs
//	WHERE user_id = $1
//	ORDER BY created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListNotificationLogs(ctx context.Context, arg ListNotificationLogsParams) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotificationLogs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationLog
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Channel,
			&i.Recipient,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.RetryCount,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushNotifications = `-- name: ListPushNotifications :many
SELECT id, user_id, token, title, body, payload, is_read, created_at, read_at FROM push_notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPushNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

// ListPushNotifications
//
//	SELECT id, user_id, token, title, body, payload, is_read, created_at, read_at FROM push_notifications
//	WHERE user_id = $1
//	ORDER BY created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListPushNotifications(ctx context.Context, arg ListPushNotificationsParams) ([]PushNotification, error) {
	rows, err := q.db.Query(ctx, listPushNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushNotification
	for rows.Next() {
		var i PushNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.IsRead,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPushNotificationRead = `-- name: MarkPushNotificationRead :exec
UPDATE push_notifications
SET is_read = TRUE,
    read_at = NOW()
WHERE id = $1 AND user_id = $2
`

type MarkPushNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// MarkPushNotificationRead
//
//	UPDATE push_notifications
//	SET is_read = TRUE,
//	    read_at = NOW()
//	WHERE id = $1 AND user_id = $2
func (q *Queries) MarkPushNotificationRead(ctx context.Context, arg MarkPushNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markPushNotificationRead, arg.ID, arg.UserID)
	return err
}

const updateNotificationLogStatus = `-- name: UpdateNotificationLogStatus :exec
UPDATE notification_logs
SET status = $2,
    retry_count = $3,
    error_message = $4,
    sent_at = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateNotificationLogStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       DeliveryStatus     `json:"status"`
	RetryCount   int32              `json:"retry_count"`
	ErrorMessage *string            `json:"error_message"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
}

// UpdateNotificationLogStatus
//
//	UPDATE notification_logs
//	SET status = $2,
//	    retry_count = $3,
//	    error_message = $4,
//	    sent_at = $5,
//	    updated_at = NOW()
//	WHERE id = $1
func (q *Queries) UpdateNotificationLogStatus(ctx context.Context, arg UpdateNotificationLogStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationLogStatus,
		arg.ID,
		arg.Status,
		arg.RetryCount,
		arg.ErrorMessage,
		arg.SentAt,
	)
	return err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO user_device_tokens (user_id, token, platform, device_name, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    device_name = EXCLUDED.device_name,
    updated_at = NOW()
RETURNING id, user_id, token, platform, device_name, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Token      string    `json:"token"`
	Platform   string    `json:"platform"`
	DeviceName *string   `json:"device_name"`
}

// UpsertDeviceToken
//
//	INSERT INTO user_device_tokens (user_id, token, platform, device_name, updated_at)
//	VALUES ($1, $2, $3, $4, NOW())
//	ON CONFLICT (token) DO UPDATE
//	SET user_id = EXCLUDED.user_id,
//	    platform = EXCLUDED.platform,
//	    device_name = EXCLUDED.device_name,
//	    updated_at = NOW()
//	RETURNING id, user_id, token, platform, device_name, created_at, updated_at
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (UserDeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken,
		arg.UserID,
		arg.Token,
		arg.Platform,
		arg.DeviceName,
	)
	var i UserDeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.DeviceName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :one
INSERT INTO user_notification_preferences (user_id, category, email_enabled, push_enabled, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id, category) DO UPDATE
SET email_enabled = EXCLUDED.email_enabled,
    push_enabled = EXCLUDED.push_enabled,
    updated_at = NOW()
RETURNING id, user_id, category, email_enabled, push_enabled, created_at, updated_at
`

type UpsertNotificationPreferenceParams struct {
	UserID       uuid.UUID            `json:"user_id"`
	Category     NotificationCategory `json:"category"`
	EmailEnabled bool                 `json:"email_enabled"`
	PushEnabled  bool                 `json:"push_enabled"`
}

// UpsertNotificationPreference
//
//	INSERT INTO user_notification_preferences (user_id, category, email_enabled, push_enabled, updated_at)
//	VALUES ($1, $2, $3, $4, NOW())
//	ON CONFLICT (user_id, category) DO UPDATE
//	SET email_enabled = EXCLUDED.email_enabled,
//	    push_enabled = EXCLUDED.push_enabled,
//	    updated_at = NOW()
//	RETURNING id, user_id, category, email_enabled, push_enabled, created_at, updated_at
func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (UserNotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreference,
		arg.UserID,
		arg.Category,
		arg.EmailEnabled,
		arg.PushEnabled,
	)
	var i UserNotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
