// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppendReview struct {
	ID        uuid.UUID          `json:"id"`
	ReviewID  uuid.UUID          `json:"review_id"`
	Content   string             `json:"content"`
	HasMedia  *bool              `json:"has_media"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AppendReviewMedium struct {
	ID             uuid.UUID          `json:"id"`
	AppendReviewID uuid.UUID          `json:"append_review_id"`
	MediaUrl       string             `json:"media_url"`
	MediaType      string             `json:"media_type"`
	SortOrder      *int32             `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OrderDelivery struct {
	OrderID     uuid.UUID `json:"order_id"`
	BuyerID     uuid.UUID `json:"buyer_id"`
	DeliveredAt time.Time `json:"delivered_at"`
	IsProcessed *bool     `json:"is_processed"`
}

type Review struct {
	ID                uuid.UUID          `json:"id"`
	OrderID           uuid.UUID          `json:"order_id"`
	BuyerID           uuid.UUID          `json:"buyer_id"`
	SellerID          uuid.UUID          `json:"seller_id"`
	ProductID         uuid.UUID          `json:"product_id"`
	VariantID         uuid.UUID          `json:"variant_id"`
	RatingDescription int32              `json:"rating_description"`
	RatingService     int32              `json:"rating_service"`
	RatingDelivery    int32              `json:"rating_delivery"`
	ReviewType        *string            `json:"review_type"`
	Content           *string            `json:"content"`
	IsAnonymous       *bool              `json:"is_anonymous"`
	HasMedia          *bool              `json:"has_media"`
	NlpTags           []byte             `json:"nlp_tags"`
	IsSystemGenerated *bool              `json:"is_system_generated"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type ReviewMedium struct {
	ID        uuid.UUID          `json:"id"`
	ReviewID  uuid.UUID          `json:"review_id"`
	MediaUrl  string             `json:"media_url"`
	MediaType string             `json:"media_type"`
	SortOrder *int32             `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SellerReply struct {
	ID        uuid.UUID          `json:"id"`
	ReviewID  uuid.UUID          `json:"review_id"`
	ReplyType string             `json:"reply_type"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
