// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProductReviews = `-- name: CountProductReviews :one
SELECT COUNT(*) FROM reviews r
LEFT JOIN append_reviews ar ON r.id = ar.review_id
WHERE r.product_id = $1 
  AND r.deleted_at IS NULL
  AND (
      $2::text = 'ALL' OR
      ($2::text = 'GOOD' AND r.review_type = 'good') OR
      ($2::text = 'NEUTRAL' AND r.review_type = 'neutral') OR
      ($2::text = 'BAD' AND r.review_type = 'bad') OR
      ($2::text = 'HAS_MEDIA' AND (r.has_media = true OR ar.has_media = true)) OR
      ($2::text = 'APPEND' AND ar.id IS NOT NULL)
  )
`

type CountProductReviewsParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Column2   string    `json:"column_2"`
}

// CountProductReviews
//
//	SELECT COUNT(*) FROM reviews r
//	LEFT JOIN append_reviews ar ON r.id = ar.review_id
//	WHERE r.product_id = $1
//	  AND r.deleted_at IS NULL
//	  AND (
//	      $2::text = 'ALL' OR
//	      ($2::text = 'GOOD' AND r.review_type = 'good') OR
//	      ($2::text = 'NEUTRAL' AND r.review_type = 'neutral') OR
//	      ($2::text = 'BAD' AND r.review_type = 'bad') OR
//	      ($2::text = 'HAS_MEDIA' AND (r.has_media = true OR ar.has_media = true)) OR
//	      ($2::text = 'APPEND' AND ar.id IS NOT NULL)
//	  )
func (q *Queries) CountProductReviews(ctx context.Context, arg CountProductReviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductReviews, arg.ProductID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSellerReviews = `-- name: CountSellerReviews :one
SELECT COUNT(*) FROM reviews
WHERE seller_id = $1 AND deleted_at IS NULL
`

// CountSellerReviews
//
//	SELECT COUNT(*) FROM reviews
//	WHERE seller_id = $1 AND deleted_at IS NULL
func (q *Queries) CountSellerReviews(ctx context.Context, sellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerReviews, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppendReview = `-- name: CreateAppendReview :one
INSERT INTO append_reviews (
    review_id, content, has_media
) VALUES (
    $1, $2, $3
)
RETURNING id, review_id, content, has_media, created_at
`

type CreateAppendReviewParams struct {
	ReviewID uuid.UUID `json:"review_id"`
	Content  string    `json:"content"`
	HasMedia *bool     `json:"has_media"`
}

// CreateAppendReview
//
//	INSERT INTO append_reviews (
//	    review_id, content, has_media
//	) VALUES (
//	    $1, $2, $3
//	)
//	RETURNING id, review_id, content, has_media, created_at
func (q *Queries) CreateAppendReview(ctx context.Context, arg CreateAppendReviewParams) (AppendReview, error) {
	row := q.db.QueryRow(ctx, createAppendReview, arg.ReviewID, arg.Content, arg.HasMedia)
	var i AppendReview
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.Content,
		&i.HasMedia,
		&i.CreatedAt,
	)
	return i, err
}

const createAppendReviewMedia = `-- name: CreateAppendReviewMedia :one
INSERT INTO append_review_media (
    append_review_id, media_url, media_type, sort_order
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, append_review_id, media_url, media_type, sort_order, created_at
`

type CreateAppendReviewMediaParams struct {
	AppendReviewID uuid.UUID `json:"append_review_id"`
	MediaUrl       string    `json:"media_url"`
	MediaType      string    `json:"media_type"`
	SortOrder      *int32    `json:"sort_order"`
}

// CreateAppendReviewMedia
//
//	INSERT INTO append_review_media (
//	    append_review_id, media_url, media_type, sort_order
//	) VALUES (
//	    $1, $2, $3, $4
//	)
//	RETURNING id, append_review_id, media_url, media_type, sort_order, created_at
func (q *Queries) CreateAppendReviewMedia(ctx context.Context, arg CreateAppendReviewMediaParams) (AppendReviewMedium, error) {
	row := q.db.QueryRow(ctx, createAppendReviewMedia,
		arg.AppendReviewID,
		arg.MediaUrl,
		arg.MediaType,
		arg.SortOrder,
	)
	var i AppendReviewMedium
	err := row.Scan(
		&i.ID,
		&i.AppendReviewID,
		&i.MediaUrl,
		&i.MediaType,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
    order_id, buyer_id, seller_id, product_id, variant_id,
    rating_description, rating_service, rating_delivery,
    content, is_anonymous, has_media, nlp_tags, is_system_generated
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at
`

type CreateReviewParams struct {
	OrderID           uuid.UUID `json:"order_id"`
	BuyerID           uuid.UUID `json:"buyer_id"`
	SellerID          uuid.UUID `json:"seller_id"`
	ProductID         uuid.UUID `json:"product_id"`
	VariantID         uuid.UUID `json:"variant_id"`
	RatingDescription int32     `json:"rating_description"`
	RatingService     int32     `json:"rating_service"`
	RatingDelivery    int32     `json:"rating_delivery"`
	Content           *string   `json:"content"`
	IsAnonymous       *bool     `json:"is_anonymous"`
	HasMedia          *bool     `json:"has_media"`
	NlpTags           []byte    `json:"nlp_tags"`
	IsSystemGenerated *bool     `json:"is_system_generated"`
}

// CreateReview
//
//	INSERT INTO reviews (
//	    order_id, buyer_id, seller_id, product_id, variant_id,
//	    rating_description, rating_service, rating_delivery,
//	    content, is_anonymous, has_media, nlp_tags, is_system_generated
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
//	)
//	RETURNING id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at
func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.OrderID,
		arg.BuyerID,
		arg.SellerID,
		arg.ProductID,
		arg.VariantID,
		arg.RatingDescription,
		arg.RatingService,
		arg.RatingDelivery,
		arg.Content,
		arg.IsAnonymous,
		arg.HasMedia,
		arg.NlpTags,
		arg.IsSystemGenerated,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.VariantID,
		&i.RatingDescription,
		&i.RatingService,
		&i.RatingDelivery,
		&i.ReviewType,
		&i.Content,
		&i.IsAnonymous,
		&i.HasMedia,
		&i.NlpTags,
		&i.IsSystemGenerated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createReviewMedia = `-- name: CreateReviewMedia :one
INSERT INTO review_media (
    review_id, media_url, media_type, sort_order
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, review_id, media_url, media_type, sort_order, created_at
`

type CreateReviewMediaParams struct {
	ReviewID  uuid.UUID `json:"review_id"`
	MediaUrl  string    `json:"media_url"`
	MediaType string    `json:"media_type"`
	SortOrder *int32    `json:"sort_order"`
}

// CreateReviewMedia
//
//	INSERT INTO review_media (
//	    review_id, media_url, media_type, sort_order
//	) VALUES (
//	    $1, $2, $3, $4
//	)
//	RETURNING id, review_id, media_url, media_type, sort_order, created_at
func (q *Queries) CreateReviewMedia(ctx context.Context, arg CreateReviewMediaParams) (ReviewMedium, error) {
	row := q.db.QueryRow(ctx, createReviewMedia,
		arg.ReviewID,
		arg.MediaUrl,
		arg.MediaType,
		arg.SortOrder,
	)
	var i ReviewMedium
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.MediaUrl,
		&i.MediaType,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createSellerReply = `-- name: CreateSellerReply :one
INSERT INTO seller_replies (
    review_id, reply_type, content
) VALUES (
    $1, $2, $3
)
RETURNING id, review_id, reply_type, content, created_at
`

type CreateSellerReplyParams struct {
	ReviewID  uuid.UUID `json:"review_id"`
	ReplyType string    `json:"reply_type"`
	Content   string    `json:"content"`
}

// CreateSellerReply
//
//	INSERT INTO seller_replies (
//	    review_id, reply_type, content
//	) VALUES (
//	    $1, $2, $3
//	)
//	RETURNING id, review_id, reply_type, content, created_at
func (q *Queries) CreateSellerReply(ctx context.Context, arg CreateSellerReplyParams) (SellerReply, error) {
	row := q.db.QueryRow(ctx, createSellerReply, arg.ReviewID, arg.ReplyType, arg.Content)
	var i SellerReply
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.ReplyType,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :one
UPDATE reviews
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at
`

// DeleteReview
//
//	UPDATE reviews
//	SET deleted_at = NOW()
//	WHERE id = $1 AND deleted_at IS NULL
//	RETURNING id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at
func (q *Queries) DeleteReview(ctx context.Context, id uuid.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, deleteReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.VariantID,
		&i.RatingDescription,
		&i.RatingService,
		&i.RatingDelivery,
		&i.ReviewType,
		&i.Content,
		&i.IsAnonymous,
		&i.HasMedia,
		&i.NlpTags,
		&i.IsSystemGenerated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppendReview = `-- name: GetAppendReview :one
SELECT id, review_id, content, has_media, created_at FROM append_reviews WHERE review_id = $1 LIMIT 1
`

// GetAppendReview
//
//	SELECT id, review_id, content, has_media, created_at FROM append_reviews WHERE review_id = $1 LIMIT 1
func (q *Queries) GetAppendReview(ctx context.Context, reviewID uuid.UUID) (AppendReview, error) {
	row := q.db.QueryRow(ctx, getAppendReview, reviewID)
	var i AppendReview
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.Content,
		&i.HasMedia,
		&i.CreatedAt,
	)
	return i, err
}

const getAppendReviewMedia = `-- name: GetAppendReviewMedia :many
SELECT id, append_review_id, media_url, media_type, sort_order, created_at FROM append_review_media WHERE append_review_id = $1 ORDER BY sort_order ASC
`

// GetAppendReviewMedia
//
//	SELECT id, append_review_id, media_url, media_type, sort_order, created_at FROM append_review_media WHERE append_review_id = $1 ORDER BY sort_order ASC
func (q *Queries) GetAppendReviewMedia(ctx context.Context, appendReviewID uuid.UUID) ([]AppendReviewMedium, error) {
	rows, err := q.db.Query(ctx, getAppendReviewMedia, appendReviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppendReviewMedium
	for rows.Next() {
		var i AppendReviewMedium
		if err := rows.Scan(
			&i.ID,
			&i.AppendReviewID,
			&i.MediaUrl,
			&i.MediaType,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductAppendCount = `-- name: GetProductAppendCount :one
SELECT COUNT(ar.id)::int FROM append_reviews ar
JOIN reviews r ON ar.review_id = r.id
WHERE r.product_id = $1 AND r.deleted_at IS NULL
`

// GetProductAppendCount
//
//	SELECT COUNT(ar.id)::int FROM append_reviews ar
//	JOIN reviews r ON ar.review_id = r.id
//	WHERE r.product_id = $1 AND r.deleted_at IS NULL
func (q *Queries) GetProductAppendCount(ctx context.Context, productID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getProductAppendCount, productID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getProductRatingStats = `-- name: GetProductRatingStats :one
SELECT 
    COALESCE(AVG(rating_description)::float, 0.0)::float as avg_rating,
    COUNT(*)::int as total_reviews,
    COUNT(CASE WHEN review_type = 'good' THEN 1 END)::int as good_count,
    COUNT(CASE WHEN review_type = 'neutral' THEN 1 END)::int as neutral_count,
    COUNT(CASE WHEN review_type = 'bad' THEN 1 END)::int as bad_count,
    COUNT(CASE WHEN has_media = true THEN 1 END)::int as has_media_count
FROM reviews
WHERE product_id = $1 AND deleted_at IS NULL
`

type GetProductRatingStatsRow struct {
	AvgRating     float64 `json:"avg_rating"`
	TotalReviews  int32   `json:"total_reviews"`
	GoodCount     int32   `json:"good_count"`
	NeutralCount  int32   `json:"neutral_count"`
	BadCount      int32   `json:"bad_count"`
	HasMediaCount int32   `json:"has_media_count"`
}

// GetProductRatingStats
//
//	SELECT
//	    COALESCE(AVG(rating_description)::float, 0.0)::float as avg_rating,
//	    COUNT(*)::int as total_reviews,
//	    COUNT(CASE WHEN review_type = 'good' THEN 1 END)::int as good_count,
//	    COUNT(CASE WHEN review_type = 'neutral' THEN 1 END)::int as neutral_count,
//	    COUNT(CASE WHEN review_type = 'bad' THEN 1 END)::int as bad_count,
//	    COUNT(CASE WHEN has_media = true THEN 1 END)::int as has_media_count
//	FROM reviews
//	WHERE product_id = $1 AND deleted_at IS NULL
func (q *Queries) GetProductRatingStats(ctx context.Context, productID uuid.UUID) (GetProductRatingStatsRow, error) {
	row := q.db.QueryRow(ctx, getProductRatingStats, productID)
	var i GetProductRatingStatsRow
	err := row.Scan(
		&i.AvgRating,
		&i.TotalReviews,
		&i.GoodCount,
		&i.NeutralCount,
		&i.BadCount,
		&i.HasMediaCount,
	)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at FROM reviews WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// GetReview
//
//	SELECT id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at FROM reviews WHERE id = $1 AND deleted_at IS NULL LIMIT 1
func (q *Queries) GetReview(ctx context.Context, id uuid.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.VariantID,
		&i.RatingDescription,
		&i.RatingService,
		&i.RatingDelivery,
		&i.ReviewType,
		&i.Content,
		&i.IsAnonymous,
		&i.HasMedia,
		&i.NlpTags,
		&i.IsSystemGenerated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReviewByOrderAndVariant = `-- name: GetReviewByOrderAndVariant :one
SELECT id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at FROM reviews WHERE order_id = $1 AND variant_id = $2 AND deleted_at IS NULL LIMIT 1
`

type GetReviewByOrderAndVariantParams struct {
	OrderID   uuid.UUID `json:"order_id"`
	VariantID uuid.UUID `json:"variant_id"`
}

// GetReviewByOrderAndVariant
//
//	SELECT id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at FROM reviews WHERE order_id = $1 AND variant_id = $2 AND deleted_at IS NULL LIMIT 1
func (q *Queries) GetReviewByOrderAndVariant(ctx context.Context, arg GetReviewByOrderAndVariantParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByOrderAndVariant, arg.OrderID, arg.VariantID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.VariantID,
		&i.RatingDescription,
		&i.RatingService,
		&i.RatingDelivery,
		&i.ReviewType,
		&i.Content,
		&i.IsAnonymous,
		&i.HasMedia,
		&i.NlpTags,
		&i.IsSystemGenerated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReviewMedia = `-- name: GetReviewMedia :many
SELECT id, review_id, media_url, media_type, sort_order, created_at FROM review_media WHERE review_id = $1 ORDER BY sort_order ASC
`

// GetReviewMedia
//
//	SELECT id, review_id, media_url, media_type, sort_order, created_at FROM review_media WHERE review_id = $1 ORDER BY sort_order ASC
func (q *Queries) GetReviewMedia(ctx context.Context, reviewID uuid.UUID) ([]ReviewMedium, error) {
	rows, err := q.db.Query(ctx, getReviewMedia, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewMedium
	for rows.Next() {
		var i ReviewMedium
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.MediaUrl,
			&i.MediaType,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSellerDSR = `-- name: GetSellerDSR :one
SELECT 
    COALESCE(AVG(rating_description)::float, 0.0)::float as avg_description,
    COALESCE(AVG(rating_service)::float, 0.0)::float as avg_service,
    COALESCE(AVG(rating_delivery)::float, 0.0)::float as avg_delivery,
    -- Reputation Score: Good (+1), Neutral (0), Bad (-1)
    COALESCE(SUM(
        CASE 
            WHEN review_type = 'good' THEN 1 
            WHEN review_type = 'bad' THEN -1 
            ELSE 0 
        END
    ), 0)::int as reputation_score
FROM reviews
WHERE seller_id = $1 
  AND deleted_at IS NULL 
  AND created_at >= NOW() - INTERVAL '180 days'
`

type GetSellerDSRRow struct {
	AvgDescription  float64 `json:"avg_description"`
	AvgService      float64 `json:"avg_service"`
	AvgDelivery     float64 `json:"avg_delivery"`
	ReputationScore int32   `json:"reputation_score"`
}

// GetSellerDSR
//
//	SELECT
//	    COALESCE(AVG(rating_description)::float, 0.0)::float as avg_description,
//	    COALESCE(AVG(rating_service)::float, 0.0)::float as avg_service,
//	    COALESCE(AVG(rating_delivery)::float, 0.0)::float as avg_delivery,
//	    -- Reputation Score: Good (+1), Neutral (0), Bad (-1)
//	    COALESCE(SUM(
//	        CASE
//	            WHEN review_type = 'good' THEN 1
//	            WHEN review_type = 'bad' THEN -1
//	            ELSE 0
//	        END
//	    ), 0)::int as reputation_score
//	FROM reviews
//	WHERE seller_id = $1
//	  AND deleted_at IS NULL
//	  AND created_at >= NOW() - INTERVAL '180 days'
func (q *Queries) GetSellerDSR(ctx context.Context, sellerID uuid.UUID) (GetSellerDSRRow, error) {
	row := q.db.QueryRow(ctx, getSellerDSR, sellerID)
	var i GetSellerDSRRow
	err := row.Scan(
		&i.AvgDescription,
		&i.AvgService,
		&i.AvgDelivery,
		&i.ReputationScore,
	)
	return i, err
}

const getSellerReplies = `-- name: GetSellerReplies :many
SELECT id, review_id, reply_type, content, created_at FROM seller_replies WHERE review_id = $1 ORDER BY created_at ASC
`

// GetSellerReplies
//
//	SELECT id, review_id, reply_type, content, created_at FROM seller_replies WHERE review_id = $1 ORDER BY created_at ASC
func (q *Queries) GetSellerReplies(ctx context.Context, reviewID uuid.UUID) ([]SellerReply, error) {
	rows, err := q.db.Query(ctx, getSellerReplies, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerReply
	for rows.Next() {
		var i SellerReply
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.ReplyType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnprocessedDeliveries = `-- name: GetUnprocessedDeliveries :many
SELECT order_id, buyer_id, delivered_at, is_processed FROM order_deliveries
WHERE is_processed = FALSE AND delivered_at <= $1::timestamptz
`

// GetUnprocessedDeliveries
//
//	SELECT order_id, buyer_id, delivered_at, is_processed FROM order_deliveries
//	WHERE is_processed = FALSE AND delivered_at <= $1::timestamptz
func (q *Queries) GetUnprocessedDeliveries(ctx context.Context, dollar_1 time.Time) ([]OrderDelivery, error) {
	rows, err := q.db.Query(ctx, getUnprocessedDeliveries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderDelivery
	for rows.Next() {
		var i OrderDelivery
		if err := rows.Scan(
			&i.OrderID,
			&i.BuyerID,
			&i.DeliveredAt,
			&i.IsProcessed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrderDelivery = `-- name: InsertOrderDelivery :one
INSERT INTO order_deliveries (order_id, buyer_id, delivered_at)
VALUES ($1, $2, $3)
ON CONFLICT (order_id) DO NOTHING
RETURNING order_id, buyer_id, delivered_at, is_processed
`

type InsertOrderDeliveryParams struct {
	OrderID     uuid.UUID `json:"order_id"`
	BuyerID     uuid.UUID `json:"buyer_id"`
	DeliveredAt time.Time `json:"delivered_at"`
}

// InsertOrderDelivery
//
//	INSERT INTO order_deliveries (order_id, buyer_id, delivered_at)
//	VALUES ($1, $2, $3)
//	ON CONFLICT (order_id) DO NOTHING
//	RETURNING order_id, buyer_id, delivered_at, is_processed
func (q *Queries) InsertOrderDelivery(ctx context.Context, arg InsertOrderDeliveryParams) (OrderDelivery, error) {
	row := q.db.QueryRow(ctx, insertOrderDelivery, arg.OrderID, arg.BuyerID, arg.DeliveredAt)
	var i OrderDelivery
	err := row.Scan(
		&i.OrderID,
		&i.BuyerID,
		&i.DeliveredAt,
		&i.IsProcessed,
	)
	return i, err
}

const listProductReviews = `-- name: ListProductReviews :many
SELECT r.id, r.order_id, r.buyer_id, r.seller_id, r.product_id, r.variant_id, r.rating_description, r.rating_service, r.rating_delivery, r.review_type, r.content, r.is_anonymous, r.has_media, r.nlp_tags, r.is_system_generated, r.created_at, r.updated_at, r.deleted_at FROM reviews r
LEFT JOIN append_reviews ar ON r.id = ar.review_id
WHERE r.product_id = $1 
  AND r.deleted_at IS NULL
  AND (
      $2::text = 'ALL' OR
      ($2::text = 'GOOD' AND r.review_type = 'good') OR
      ($2::text = 'NEUTRAL' AND r.review_type = 'neutral') OR
      ($2::text = 'BAD' AND r.review_type = 'bad') OR
      ($2::text = 'HAS_MEDIA' AND (r.has_media = true OR ar.has_media = true)) OR
      ($2::text = 'APPEND' AND ar.id IS NOT NULL)
  )
ORDER BY r.created_at DESC
LIMIT $4 OFFSET $3
`

type ListProductReviewsParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Column2   string    `json:"column_2"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
}

// ListProductReviews
//
//	SELECT r.id, r.order_id, r.buyer_id, r.seller_id, r.product_id, r.variant_id, r.rating_description, r.rating_service, r.rating_delivery, r.review_type, r.content, r.is_anonymous, r.has_media, r.nlp_tags, r.is_system_generated, r.created_at, r.updated_at, r.deleted_at FROM reviews r
//	LEFT JOIN append_reviews ar ON r.id = ar.review_id
//	WHERE r.product_id = $1
//	  AND r.deleted_at IS NULL
//	  AND (
//	      $2::text = 'ALL' OR
//	      ($2::text = 'GOOD' AND r.review_type = 'good') OR
//	      ($2::text = 'NEUTRAL' AND r.review_type = 'neutral') OR
//	      ($2::text = 'BAD' AND r.review_type = 'bad') OR
//	      ($2::text = 'HAS_MEDIA' AND (r.has_media = true OR ar.has_media = true)) OR
//	      ($2::text = 'APPEND' AND ar.id IS NOT NULL)
//	  )
//	ORDER BY r.created_at DESC
//	LIMIT $4 OFFSET $3
func (q *Queries) ListProductReviews(ctx context.Context, arg ListProductReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listProductReviews,
		arg.ProductID,
		arg.Column2,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.VariantID,
			&i.RatingDescription,
			&i.RatingService,
			&i.RatingDelivery,
			&i.ReviewType,
			&i.Content,
			&i.IsAnonymous,
			&i.HasMedia,
			&i.NlpTags,
			&i.IsSystemGenerated,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerReviews = `-- name: ListSellerReviews :many
SELECT id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at FROM reviews
WHERE seller_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListSellerReviewsParams struct {
	SellerID uuid.UUID `json:"seller_id"`
	Offset   int32     `json:"offset"`
	Limit    int32     `json:"limit"`
}

// ListSellerReviews
//
//	SELECT id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at FROM reviews
//	WHERE seller_id = $1 AND deleted_at IS NULL
//	ORDER BY created_at DESC
//	LIMIT $3 OFFSET $2
func (q *Queries) ListSellerReviews(ctx context.Context, arg ListSellerReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listSellerReviews, arg.SellerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.VariantID,
			&i.RatingDescription,
			&i.RatingService,
			&i.RatingDelivery,
			&i.ReviewType,
			&i.Content,
			&i.IsAnonymous,
			&i.HasMedia,
			&i.NlpTags,
			&i.IsSystemGenerated,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryProcessed = `-- name: MarkDeliveryProcessed :exec
UPDATE order_deliveries
SET is_processed = TRUE
WHERE order_id = $1
`

// MarkDeliveryProcessed
//
//	UPDATE order_deliveries
//	SET is_processed = TRUE
//	WHERE order_id = $1
func (q *Queries) MarkDeliveryProcessed(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDeliveryProcessed, orderID)
	return err
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET rating_description = $2,
    rating_service = $3,
    rating_delivery = $4,
    content = $5,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at
`

type UpdateReviewParams struct {
	ID                uuid.UUID `json:"id"`
	RatingDescription int32     `json:"rating_description"`
	RatingService     int32     `json:"rating_service"`
	RatingDelivery    int32     `json:"rating_delivery"`
	Content           *string   `json:"content"`
}

// UpdateReview
//
//	UPDATE reviews
//	SET rating_description = $2,
//	    rating_service = $3,
//	    rating_delivery = $4,
//	    content = $5,
//	    updated_at = NOW()
//	WHERE id = $1 AND deleted_at IS NULL
//	RETURNING id, order_id, buyer_id, seller_id, product_id, variant_id, rating_description, rating_service, rating_delivery, review_type, content, is_anonymous, has_media, nlp_tags, is_system_generated, created_at, updated_at, deleted_at
func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.ID,
		arg.RatingDescription,
		arg.RatingService,
		arg.RatingDelivery,
		arg.Content,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.VariantID,
		&i.RatingDescription,
		&i.RatingService,
		&i.RatingDelivery,
		&i.ReviewType,
		&i.Content,
		&i.IsAnonymous,
		&i.HasMedia,
		&i.NlpTags,
		&i.IsSystemGenerated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
