// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (parent_id, slug, icon_url, banner_url, level, attribute_schema, sort_order, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, parent_id, slug, icon_url, banner_url, level, attribute_schema, sort_order, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	ParentID        *uuid.UUID `json:"parent_id"`
	Slug            string     `json:"slug"`
	IconUrl         *string    `json:"icon_url"`
	BannerUrl       *string    `json:"banner_url"`
	Level           int32      `json:"level"`
	AttributeSchema []byte     `json:"attribute_schema"`
	SortOrder       int32      `json:"sort_order"`
	IsActive        bool       `json:"is_active"`
}

// CreateCategory
//
//	INSERT INTO categories (parent_id, slug, icon_url, banner_url, level, attribute_schema, sort_order, is_active)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING id, parent_id, slug, icon_url, banner_url, level, attribute_schema, sort_order, is_active, created_at, updated_at
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ParentID,
		arg.Slug,
		arg.IconUrl,
		arg.BannerUrl,
		arg.Level,
		arg.AttributeSchema,
		arg.SortOrder,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.IconUrl,
		&i.BannerUrl,
		&i.Level,
		&i.AttributeSchema,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategoryTranslation = `-- name: CreateCategoryTranslation :exec
INSERT INTO category_translations (category_id, language, name)
VALUES ($1, $2, $3)
ON CONFLICT (category_id, language) DO UPDATE SET name = EXCLUDED.name
`

type CreateCategoryTranslationParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Language   string    `json:"language"`
	Name       string    `json:"name"`
}

// CreateCategoryTranslation
//
//	INSERT INTO category_translations (category_id, language, name)
//	VALUES ($1, $2, $3)
//	ON CONFLICT (category_id, language) DO UPDATE SET name = EXCLUDED.name
func (q *Queries) CreateCategoryTranslation(ctx context.Context, arg CreateCategoryTranslationParams) error {
	_, err := q.db.Exec(ctx, createCategoryTranslation, arg.CategoryID, arg.Language, arg.Name)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
    c.id, c.parent_id, c.slug, c.icon_url, c.banner_url,
    c.level, c.attribute_schema, c.sort_order, c.is_active,
    c.created_at, c.updated_at,
    COALESCE(t.name, t_en.name, '') AS name
FROM categories c
LEFT JOIN category_translations t    ON t.category_id = c.id AND t.language = $1
LEFT JOIN category_translations t_en ON t_en.category_id = c.id AND t_en.language = 'en'
WHERE c.id = $2 AND c.is_active = TRUE
`

type GetCategoryByIDParams struct {
	Language string    `json:"language"`
	ID       uuid.UUID `json:"id"`
}

type GetCategoryByIDRow struct {
	ID              uuid.UUID  `json:"id"`
	ParentID        *uuid.UUID `json:"parent_id"`
	Slug            string     `json:"slug"`
	IconUrl         *string    `json:"icon_url"`
	BannerUrl       *string    `json:"banner_url"`
	Level           int32      `json:"level"`
	AttributeSchema []byte     `json:"attribute_schema"`
	SortOrder       int32      `json:"sort_order"`
	IsActive        bool       `json:"is_active"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	Name            string     `json:"name"`
}

// GetCategoryByID
//
//	SELECT
//	    c.id, c.parent_id, c.slug, c.icon_url, c.banner_url,
//	    c.level, c.attribute_schema, c.sort_order, c.is_active,
//	    c.created_at, c.updated_at,
//	    COALESCE(t.name, t_en.name, '') AS name
//	FROM categories c
//	LEFT JOIN category_translations t    ON t.category_id = c.id AND t.language = $1
//	LEFT JOIN category_translations t_en ON t_en.category_id = c.id AND t_en.language = 'en'
//	WHERE c.id = $2 AND c.is_active = TRUE
func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.Language, arg.ID)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.IconUrl,
		&i.BannerUrl,
		&i.Level,
		&i.AttributeSchema,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT
    c.id, c.parent_id, c.slug, c.icon_url, c.banner_url,
    c.level, c.attribute_schema, c.sort_order, c.is_active,
    c.created_at, c.updated_at,
    COALESCE(t.name, t_en.name, '') AS name
FROM categories c
LEFT JOIN category_translations t    ON t.category_id = c.id AND t.language = $1
LEFT JOIN category_translations t_en ON t_en.category_id = c.id AND t_en.language = 'en'
WHERE c.slug = $2 AND c.is_active = TRUE
`

type GetCategoryBySlugParams struct {
	Language string `json:"language"`
	Slug     string `json:"slug"`
}

type GetCategoryBySlugRow struct {
	ID              uuid.UUID  `json:"id"`
	ParentID        *uuid.UUID `json:"parent_id"`
	Slug            string     `json:"slug"`
	IconUrl         *string    `json:"icon_url"`
	BannerUrl       *string    `json:"banner_url"`
	Level           int32      `json:"level"`
	AttributeSchema []byte     `json:"attribute_schema"`
	SortOrder       int32      `json:"sort_order"`
	IsActive        bool       `json:"is_active"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	Name            string     `json:"name"`
}

// GetCategoryBySlug
//
//	SELECT
//	    c.id, c.parent_id, c.slug, c.icon_url, c.banner_url,
//	    c.level, c.attribute_schema, c.sort_order, c.is_active,
//	    c.created_at, c.updated_at,
//	    COALESCE(t.name, t_en.name, '') AS name
//	FROM categories c
//	LEFT JOIN category_translations t    ON t.category_id = c.id AND t.language = $1
//	LEFT JOIN category_translations t_en ON t_en.category_id = c.id AND t_en.language = 'en'
//	WHERE c.slug = $2 AND c.is_active = TRUE
func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (GetCategoryBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, arg.Language, arg.Slug)
	var i GetCategoryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.IconUrl,
		&i.BannerUrl,
		&i.Level,
		&i.AttributeSchema,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    c.id, c.parent_id, c.slug, c.icon_url, c.banner_url,
    c.level, c.attribute_schema, c.sort_order, c.is_active,
    c.created_at, c.updated_at,
    COALESCE(t.name, t_en.name, '') AS name
FROM categories c
LEFT JOIN category_translations t    ON t.category_id = c.id AND t.language = $1
LEFT JOIN category_translations t_en ON t_en.category_id = c.id AND t_en.language = 'en'
WHERE c.is_active = TRUE
ORDER BY c.level ASC, c.sort_order ASC
`

type ListCategoriesRow struct {
	ID              uuid.UUID  `json:"id"`
	ParentID        *uuid.UUID `json:"parent_id"`
	Slug            string     `json:"slug"`
	IconUrl         *string    `json:"icon_url"`
	BannerUrl       *string    `json:"banner_url"`
	Level           int32      `json:"level"`
	AttributeSchema []byte     `json:"attribute_schema"`
	SortOrder       int32      `json:"sort_order"`
	IsActive        bool       `json:"is_active"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	Name            string     `json:"name"`
}

// Returns all active categories with translated name (falls back to 'en').
//
//	SELECT
//	    c.id, c.parent_id, c.slug, c.icon_url, c.banner_url,
//	    c.level, c.attribute_schema, c.sort_order, c.is_active,
//	    c.created_at, c.updated_at,
//	    COALESCE(t.name, t_en.name, '') AS name
//	FROM categories c
//	LEFT JOIN category_translations t    ON t.category_id = c.id AND t.language = $1
//	LEFT JOIN category_translations t_en ON t_en.category_id = c.id AND t_en.language = 'en'
//	WHERE c.is_active = TRUE
//	ORDER BY c.level ASC, c.sort_order ASC
func (q *Queries) ListCategories(ctx context.Context, language string) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Slug,
			&i.IconUrl,
			&i.BannerUrl,
			&i.Level,
			&i.AttributeSchema,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
