// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getStock = `-- name: GetStock :one
SELECT variant_id, quantity, created_at, updated_at
FROM variant_stock
WHERE variant_id = $1
`

// GetStock
//
//	SELECT variant_id, quantity, created_at, updated_at
//	FROM variant_stock
//	WHERE variant_id = $1
func (q *Queries) GetStock(ctx context.Context, variantID uuid.UUID) (VariantStock, error) {
	row := q.db.QueryRow(ctx, getStock, variantID)
	var i VariantStock
	err := row.Scan(
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockBatch = `-- name: GetStockBatch :many
SELECT variant_id, quantity, created_at, updated_at
FROM variant_stock
WHERE variant_id = ANY($1::uuid[])
`

// GetStockBatch
//
//	SELECT variant_id, quantity, created_at, updated_at
//	FROM variant_stock
//	WHERE variant_id = ANY($1::uuid[])
func (q *Queries) GetStockBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]VariantStock, error) {
	rows, err := q.db.Query(ctx, getStockBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariantStock
	for rows.Next() {
		var i VariantStock
		if err := rows.Scan(
			&i.VariantID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStock = `-- name: UpsertStock :one
INSERT INTO variant_stock (variant_id, quantity)
VALUES ($1, $2)
ON CONFLICT (variant_id) DO UPDATE SET
    quantity = EXCLUDED.quantity,
    updated_at = NOW()
RETURNING variant_id, quantity, created_at, updated_at
`

type UpsertStockParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Quantity  int32     `json:"quantity"`
}

// UpsertStock
//
//	INSERT INTO variant_stock (variant_id, quantity)
//	VALUES ($1, $2)
//	ON CONFLICT (variant_id) DO UPDATE SET
//	    quantity = EXCLUDED.quantity,
//	    updated_at = NOW()
//	RETURNING variant_id, quantity, created_at, updated_at
func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) (VariantStock, error) {
	row := q.db.QueryRow(ctx, upsertStock, arg.VariantID, arg.Quantity)
	var i VariantStock
	err := row.Scan(
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
