// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ProductStatus string

const (
	ProductStatusDraft  ProductStatus = "draft"
	ProductStatusActive ProductStatus = "active"
	ProductStatusPaused ProductStatus = "paused"
	ProductStatusBanned ProductStatus = "banned"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"product_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type ProductType string

const (
	ProductTypeElectronics             ProductType = "Electronics"
	ProductTypeMobilePhonesAccessories ProductType = "Mobile Phones & Accessories"
	ProductTypeFashion                 ProductType = "Fashion"
	ProductTypeHomeFurniture           ProductType = "Home & Furniture"
	ProductTypeBeautyHealth            ProductType = "Beauty & Health"
	ProductTypeAppliances              ProductType = "Appliances"
	ProductTypeAutomotive              ProductType = "Automotive"
	ProductTypeHardwareConstruction    ProductType = "Hardware & Construction"
	ProductTypeAgriculture             ProductType = "Agriculture"
	ProductTypeSportsOutdoors          ProductType = "Sports & Outdoors"
	ProductTypeBabyKids                ProductType = "Baby & Kids"
	ProductTypeOfficeSupplies          ProductType = "Office Supplies"
	ProductTypeBooksEducation          ProductType = "Books & Education"
	ProductTypePetSupplies             ProductType = "Pet Supplies"
	ProductTypeDigitalProducts         ProductType = "Digital Products"
	ProductTypeServices                ProductType = "Services"
	ProductTypeLiquids                 ProductType = "Liquids"
	ProductTypeBeverages               ProductType = "Beverages"
)

func (e *ProductType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductType(s)
	case string:
		*e = ProductType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductType: %T", src)
	}
	return nil
}

type NullProductType struct {
	ProductType ProductType `json:"product_type"`
	Valid       bool        `json:"valid"` // Valid is true if ProductType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductType) Scan(value interface{}) error {
	if value == nil {
		ns.ProductType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductType), nil
}

type Category struct {
	ID              uuid.UUID  `json:"id"`
	ParentID        *uuid.UUID `json:"parent_id"`
	Slug            string     `json:"slug"`
	IconUrl         *string    `json:"icon_url"`
	BannerUrl       *string    `json:"banner_url"`
	Level           int32      `json:"level"`
	AttributeSchema []byte     `json:"attribute_schema"`
	SortOrder       int32      `json:"sort_order"`
	IsActive        bool       `json:"is_active"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type CategoryTranslation struct {
	CategoryID uuid.UUID `json:"category_id"`
	Language   string    `json:"language"`
	Name       string    `json:"name"`
}

type Product struct {
	ID            uuid.UUID      `json:"id"`
	SellerID      uuid.UUID      `json:"seller_id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Slug          string         `json:"slug"`
	Attributes    []byte         `json:"attributes"`
	Brand         *string        `json:"brand"`
	OriginCountry *string        `json:"origin_country"`
	Status        string         `json:"status"`
	Rating        pgtype.Numeric `json:"rating"`
	ReviewCount   int32          `json:"review_count"`
	SoldCount     int32          `json:"sold_count"`
	ViewCount     int32          `json:"view_count"`
	MinPrice      pgtype.Numeric `json:"min_price"`
	MaxPrice      pgtype.Numeric `json:"max_price"`
	ImageUrl      *string        `json:"image_url"`
	ThumbnailUrl  *string        `json:"thumbnail_url"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     *time.Time     `json:"deleted_at"`
	Location      interface{}    `json:"location"`
	ProductType   string         `json:"product_type"`
}

type ProductImage struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	Url       string    `json:"url"`
	AltText   *string   `json:"alt_text"`
	SortOrder int32     `json:"sort_order"`
	IsPrimary bool      `json:"is_primary"`
	CreatedAt time.Time `json:"created_at"`
}

type ProductTag struct {
	ProductID uuid.UUID `json:"product_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

type ProductTranslation struct {
	ProductID   uuid.UUID `json:"product_id"`
	Language    string    `json:"language"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
}

type ProductVariant struct {
	ID           uuid.UUID      `json:"id"`
	ProductID    uuid.UUID      `json:"product_id"`
	Sku          string         `json:"sku"`
	Options      []byte         `json:"options"`
	Price        pgtype.Numeric `json:"price"`
	ComparePrice pgtype.Numeric `json:"compare_price"`
	WeightGrams  *int32         `json:"weight_grams"`
	ImageUrl     *string        `json:"image_url"`
	IsDefault    bool           `json:"is_default"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Tag struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

type VariantStock struct {
	VariantID uuid.UUID `json:"variant_id"`
	Quantity  int32     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
