// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProductTag = `-- name: AddProductTag :exec
INSERT INTO product_tags (product_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProductTagParams struct {
	ProductID uuid.UUID `json:"product_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

// AddProductTag
//
//	INSERT INTO product_tags (product_id, tag_id)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) AddProductTag(ctx context.Context, arg AddProductTagParams) error {
	_, err := q.db.Exec(ctx, addProductTag, arg.ProductID, arg.TagID)
	return err
}

const countNearbyProducts = `-- name: CountNearbyProducts :one
SELECT COUNT(*) FROM products p
WHERE p.deleted_at IS NULL
  AND p.status = 'active'
  AND ST_DWithin(p.location, ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography, $3::float)
`

type CountNearbyProductsParams struct {
	Longitude    float64 `json:"longitude"`
	Latitude     float64 `json:"latitude"`
	RadiusMeters float64 `json:"radius_meters"`
}

// CountNearbyProducts
//
//	SELECT COUNT(*) FROM products p
//	WHERE p.deleted_at IS NULL
//	  AND p.status = 'active'
//	  AND ST_DWithin(p.location, ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography, $3::float)
func (q *Queries) CountNearbyProducts(ctx context.Context, arg CountNearbyProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNearbyProducts, arg.Longitude, arg.Latitude, arg.RadiusMeters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (seller_id, category_id, slug, attributes, brand, origin_country, status, min_price, max_price, location, product_type, image_url, thumbnail_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, ST_SetSRID(ST_MakePoint($11::float, $10::float), 4326)::geography, $12::product_type, $13, $14)
RETURNING id, seller_id, category_id, slug, attributes, brand, origin_country, status, rating, review_count, sold_count, view_count, min_price, max_price, image_url, thumbnail_url, created_at, updated_at, deleted_at, product_type, ST_Y(location::geometry)::float AS latitude, ST_X(location::geometry)::float AS longitude
`

type CreateProductParams struct {
	SellerID      uuid.UUID      `json:"seller_id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Slug          string         `json:"slug"`
	Attributes    []byte         `json:"attributes"`
	Brand         *string        `json:"brand"`
	OriginCountry *string        `json:"origin_country"`
	Status        string         `json:"status"`
	MinPrice      pgtype.Numeric `json:"min_price"`
	MaxPrice      pgtype.Numeric `json:"max_price"`
	Column10      float64        `json:"column_10"`
	Column11      float64        `json:"column_11"`
	Column12      string         `json:"column_12"`
	ImageUrl      *string        `json:"image_url"`
	ThumbnailUrl  *string        `json:"thumbnail_url"`
}

type CreateProductRow struct {
	ID            uuid.UUID      `json:"id"`
	SellerID      uuid.UUID      `json:"seller_id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Slug          string         `json:"slug"`
	Attributes    []byte         `json:"attributes"`
	Brand         *string        `json:"brand"`
	OriginCountry *string        `json:"origin_country"`
	Status        string         `json:"status"`
	Rating        pgtype.Numeric `json:"rating"`
	ReviewCount   int32          `json:"review_count"`
	SoldCount     int32          `json:"sold_count"`
	ViewCount     int32          `json:"view_count"`
	MinPrice      pgtype.Numeric `json:"min_price"`
	MaxPrice      pgtype.Numeric `json:"max_price"`
	ImageUrl      *string        `json:"image_url"`
	ThumbnailUrl  *string        `json:"thumbnail_url"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     *time.Time     `json:"deleted_at"`
	ProductType   string         `json:"product_type"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
}

// CreateProduct
//
//	INSERT INTO products (seller_id, category_id, slug, attributes, brand, origin_country, status, min_price, max_price, location, product_type, image_url, thumbnail_url)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, ST_SetSRID(ST_MakePoint($11::float, $10::float), 4326)::geography, $12::product_type, $13, $14)
//	RETURNING id, seller_id, category_id, slug, attributes, brand, origin_country, status, rating, review_count, sold_count, view_count, min_price, max_price, image_url, thumbnail_url, created_at, updated_at, deleted_at, product_type, ST_Y(location::geometry)::float AS latitude, ST_X(location::geometry)::float AS longitude
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.SellerID,
		arg.CategoryID,
		arg.Slug,
		arg.Attributes,
		arg.Brand,
		arg.OriginCountry,
		arg.Status,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.ImageUrl,
		arg.ThumbnailUrl,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Slug,
		&i.Attributes,
		&i.Brand,
		&i.OriginCountry,
		&i.Status,
		&i.Rating,
		&i.ReviewCount,
		&i.SoldCount,
		&i.ViewCount,
		&i.MinPrice,
		&i.MaxPrice,
		&i.ImageUrl,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductType,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, url, alt_text, sort_order, is_primary)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, url, alt_text, sort_order, is_primary, created_at
`

type CreateProductImageParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Url       string    `json:"url"`
	AltText   *string   `json:"alt_text"`
	SortOrder int32     `json:"sort_order"`
	IsPrimary bool      `json:"is_primary"`
}

// CreateProductImage
//
//	INSERT INTO product_images (product_id, url, alt_text, sort_order, is_primary)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, product_id, url, alt_text, sort_order, is_primary, created_at
func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.ProductID,
		arg.Url,
		arg.AltText,
		arg.SortOrder,
		arg.IsPrimary,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const createProductTranslation = `-- name: CreateProductTranslation :exec
INSERT INTO product_translations (product_id, language, title, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id, language) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
`

type CreateProductTranslationParams struct {
	ProductID   uuid.UUID `json:"product_id"`
	Language    string    `json:"language"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
}

// CreateProductTranslation
//
//	INSERT INTO product_translations (product_id, language, title, description)
//	VALUES ($1, $2, $3, $4)
//	ON CONFLICT (product_id, language) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
func (q *Queries) CreateProductTranslation(ctx context.Context, arg CreateProductTranslationParams) error {
	_, err := q.db.Exec(ctx, createProductTranslation,
		arg.ProductID,
		arg.Language,
		arg.Title,
		arg.Description,
	)
	return err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (product_id, sku, options, price, compare_price, weight_grams, image_url, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, product_id, sku, options, price, compare_price, weight_grams, image_url, is_default, created_at, updated_at
`

type CreateProductVariantParams struct {
	ProductID    uuid.UUID      `json:"product_id"`
	Sku          string         `json:"sku"`
	Options      []byte         `json:"options"`
	Price        pgtype.Numeric `json:"price"`
	ComparePrice pgtype.Numeric `json:"compare_price"`
	WeightGrams  *int32         `json:"weight_grams"`
	ImageUrl     *string        `json:"image_url"`
	IsDefault    bool           `json:"is_default"`
}

// CreateProductVariant
//
//	INSERT INTO product_variants (product_id, sku, options, price, compare_price, weight_grams, image_url, is_default)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING id, product_id, sku, options, price, compare_price, weight_grams, image_url, is_default, created_at, updated_at
func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ProductID,
		arg.Sku,
		arg.Options,
		arg.Price,
		arg.ComparePrice,
		arg.WeightGrams,
		arg.ImageUrl,
		arg.IsDefault,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Options,
		&i.Price,
		&i.ComparePrice,
		&i.WeightGrams,
		&i.ImageUrl,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, slug)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, slug
`

type CreateTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateTag
//
//	INSERT INTO tags (name, slug)
//	VALUES ($1, $2)
//	ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
//	RETURNING id, name, slug
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products SET deleted_at = NOW()
WHERE id = $1 AND seller_id = $2
`

type DeleteProductParams struct {
	ID       uuid.UUID `json:"id"`
	SellerID uuid.UUID `json:"seller_id"`
}

// DeleteProduct
//
//	UPDATE products SET deleted_at = NOW()
//	WHERE id = $1 AND seller_id = $2
func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.SellerID)
	return err
}

const deleteProductImages = `-- name: DeleteProductImages :exec
DELETE FROM product_images
WHERE product_id = $1
`

// DeleteProductImages
//
//	DELETE FROM product_images
//	WHERE product_id = $1
func (q *Queries) DeleteProductImages(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImages, productID)
	return err
}

const getProductBatch = `-- name: GetProductBatch :many
SELECT
    p.id, p.seller_id, p.category_id, p.slug, p.attributes, p.brand, p.origin_country,
    p.status, p.rating, p.review_count, p.sold_count, p.view_count, p.min_price, p.max_price,
    p.image_url, p.thumbnail_url,
    p.created_at, p.updated_at, p.deleted_at, p.product_type,
    ST_Y(p.location::geometry)::float AS latitude,
    ST_X(p.location::geometry)::float AS longitude,
    COALESCE(t.title, t_en.title, '')       AS title,
    COALESCE(t.description, t_en.description) AS description
FROM products p
LEFT JOIN product_translations t    ON t.product_id = p.id AND t.language = $1
LEFT JOIN product_translations t_en ON t_en.product_id = p.id AND t_en.language = 'en'
WHERE p.id = ANY($2::uuid[]) AND p.deleted_at IS NULL
`

type GetProductBatchParams struct {
	Language string      `json:"language"`
	Column2  []uuid.UUID `json:"column_2"`
}

type GetProductBatchRow struct {
	ID            uuid.UUID      `json:"id"`
	SellerID      uuid.UUID      `json:"seller_id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Slug          string         `json:"slug"`
	Attributes    []byte         `json:"attributes"`
	Brand         *string        `json:"brand"`
	OriginCountry *string        `json:"origin_country"`
	Status        string         `json:"status"`
	Rating        pgtype.Numeric `json:"rating"`
	ReviewCount   int32          `json:"review_count"`
	SoldCount     int32          `json:"sold_count"`
	ViewCount     int32          `json:"view_count"`
	MinPrice      pgtype.Numeric `json:"min_price"`
	MaxPrice      pgtype.Numeric `json:"max_price"`
	ImageUrl      *string        `json:"image_url"`
	ThumbnailUrl  *string        `json:"thumbnail_url"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     *time.Time     `json:"deleted_at"`
	ProductType   string         `json:"product_type"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	Title         string         `json:"title"`
	Description   *string        `json:"description"`
}

// GetProductBatch
//
//	SELECT
//	    p.id, p.seller_id, p.category_id, p.slug, p.attributes, p.brand, p.origin_country,
//	    p.status, p.rating, p.review_count, p.sold_count, p.view_count, p.min_price, p.max_price,
//	    p.image_url, p.thumbnail_url,
//	    p.created_at, p.updated_at, p.deleted_at, p.product_type,
//	    ST_Y(p.location::geometry)::float AS latitude,
//	    ST_X(p.location::geometry)::float AS longitude,
//	    COALESCE(t.title, t_en.title, '')       AS title,
//	    COALESCE(t.description, t_en.description) AS description
//	FROM products p
//	LEFT JOIN product_translations t    ON t.product_id = p.id AND t.language = $1
//	LEFT JOIN product_translations t_en ON t_en.product_id = p.id AND t_en.language = 'en'
//	WHERE p.id = ANY($2::uuid[]) AND p.deleted_at IS NULL
func (q *Queries) GetProductBatch(ctx context.Context, arg GetProductBatchParams) ([]GetProductBatchRow, error) {
	rows, err := q.db.Query(ctx, getProductBatch, arg.Language, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductBatchRow
	for rows.Next() {
		var i GetProductBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Slug,
			&i.Attributes,
			&i.Brand,
			&i.OriginCountry,
			&i.Status,
			&i.Rating,
			&i.ReviewCount,
			&i.SoldCount,
			&i.ViewCount,
			&i.MinPrice,
			&i.MaxPrice,
			&i.ImageUrl,
			&i.ThumbnailUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductType,
			&i.Latitude,
			&i.Longitude,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id, p.seller_id, p.category_id, p.slug, p.attributes, p.brand, p.origin_country,
    p.status, p.rating, p.review_count, p.sold_count, p.view_count, p.min_price, p.max_price,
    p.image_url, p.thumbnail_url,
    p.created_at, p.updated_at, p.deleted_at, p.product_type,
    ST_Y(p.location::geometry)::float AS latitude,
    ST_X(p.location::geometry)::float AS longitude,
    COALESCE(t.title, t_en.title, '')       AS title,
    COALESCE(t.description, t_en.description) AS description
FROM products p
LEFT JOIN product_translations t    ON t.product_id = p.id AND t.language = $1
LEFT JOIN product_translations t_en ON t_en.product_id = p.id AND t_en.language = 'en'
WHERE p.id = $2 AND p.deleted_at IS NULL
`

type GetProductByIDParams struct {
	Language string    `json:"language"`
	ID       uuid.UUID `json:"id"`
}

type GetProductByIDRow struct {
	ID            uuid.UUID      `json:"id"`
	SellerID      uuid.UUID      `json:"seller_id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Slug          string         `json:"slug"`
	Attributes    []byte         `json:"attributes"`
	Brand         *string        `json:"brand"`
	OriginCountry *string        `json:"origin_country"`
	Status        string         `json:"status"`
	Rating        pgtype.Numeric `json:"rating"`
	ReviewCount   int32          `json:"review_count"`
	SoldCount     int32          `json:"sold_count"`
	ViewCount     int32          `json:"view_count"`
	MinPrice      pgtype.Numeric `json:"min_price"`
	MaxPrice      pgtype.Numeric `json:"max_price"`
	ImageUrl      *string        `json:"image_url"`
	ThumbnailUrl  *string        `json:"thumbnail_url"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     *time.Time     `json:"deleted_at"`
	ProductType   string         `json:"product_type"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	Title         string         `json:"title"`
	Description   *string        `json:"description"`
}

// GetProductByID
//
//	SELECT
//	    p.id, p.seller_id, p.category_id, p.slug, p.attributes, p.brand, p.origin_country,
//	    p.status, p.rating, p.review_count, p.sold_count, p.view_count, p.min_price, p.max_price,
//	    p.image_url, p.thumbnail_url,
//	    p.created_at, p.updated_at, p.deleted_at, p.product_type,
//	    ST_Y(p.location::geometry)::float AS latitude,
//	    ST_X(p.location::geometry)::float AS longitude,
//	    COALESCE(t.title, t_en.title, '')       AS title,
//	    COALESCE(t.description, t_en.description) AS description
//	FROM products p
//	LEFT JOIN product_translations t    ON t.product_id = p.id AND t.language = $1
//	LEFT JOIN product_translations t_en ON t_en.product_id = p.id AND t_en.language = 'en'
//	WHERE p.id = $2 AND p.deleted_at IS NULL
func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.Language, arg.ID)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Slug,
		&i.Attributes,
		&i.Brand,
		&i.OriginCountry,
		&i.Status,
		&i.Rating,
		&i.ReviewCount,
		&i.SoldCount,
		&i.ViewCount,
		&i.MinPrice,
		&i.MaxPrice,
		&i.ImageUrl,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductType,
		&i.Latitude,
		&i.Longitude,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT
    p.id, p.seller_id, p.category_id, p.slug, p.attributes, p.brand, p.origin_country,
    p.status, p.rating, p.review_count, p.sold_count, p.view_count, p.min_price, p.max_price,
    p.image_url, p.thumbnail_url,
    p.created_at, p.updated_at, p.deleted_at, p.product_type,
    ST_Y(p.location::geometry)::float AS latitude,
    ST_X(p.location::geometry)::float AS longitude,
    COALESCE(t.title, t_en.title, '')       AS title,
    COALESCE(t.description, t_en.description) AS description
FROM products p
LEFT JOIN product_translations t    ON t.product_id = p.id AND t.language = $1
LEFT JOIN product_translations t_en ON t_en.product_id = p.id AND t_en.language = 'en'
WHERE p.slug = $2 AND p.deleted_at IS NULL
`

type GetProductBySlugParams struct {
	Language string `json:"language"`
	Slug     string `json:"slug"`
}

type GetProductBySlugRow struct {
	ID            uuid.UUID      `json:"id"`
	SellerID      uuid.UUID      `json:"seller_id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Slug          string         `json:"slug"`
	Attributes    []byte         `json:"attributes"`
	Brand         *string        `json:"brand"`
	OriginCountry *string        `json:"origin_country"`
	Status        string         `json:"status"`
	Rating        pgtype.Numeric `json:"rating"`
	ReviewCount   int32          `json:"review_count"`
	SoldCount     int32          `json:"sold_count"`
	ViewCount     int32          `json:"view_count"`
	MinPrice      pgtype.Numeric `json:"min_price"`
	MaxPrice      pgtype.Numeric `json:"max_price"`
	ImageUrl      *string        `json:"image_url"`
	ThumbnailUrl  *string        `json:"thumbnail_url"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     *time.Time     `json:"deleted_at"`
	ProductType   string         `json:"product_type"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	Title         string         `json:"title"`
	Description   *string        `json:"description"`
}

// GetProductBySlug
//
//	SELECT
//	    p.id, p.seller_id, p.category_id, p.slug, p.attributes, p.brand, p.origin_country,
//	    p.status, p.rating, p.review_count, p.sold_count, p.view_count, p.min_price, p.max_price,
//	    p.image_url, p.thumbnail_url,
//	    p.created_at, p.updated_at, p.deleted_at, p.product_type,
//	    ST_Y(p.location::geometry)::float AS latitude,
//	    ST_X(p.location::geometry)::float AS longitude,
//	    COALESCE(t.title, t_en.title, '')       AS title,
//	    COALESCE(t.description, t_en.description) AS description
//	FROM products p
//	LEFT JOIN product_translations t    ON t.product_id = p.id AND t.language = $1
//	LEFT JOIN product_translations t_en ON t_en.product_id = p.id AND t_en.language = 'en'
//	WHERE p.slug = $2 AND p.deleted_at IS NULL
func (q *Queries) GetProductBySlug(ctx context.Context, arg GetProductBySlugParams) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, arg.Language, arg.Slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Slug,
		&i.Attributes,
		&i.Brand,
		&i.OriginCountry,
		&i.Status,
		&i.Rating,
		&i.ReviewCount,
		&i.SoldCount,
		&i.ViewCount,
		&i.MinPrice,
		&i.MaxPrice,
		&i.ImageUrl,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductType,
		&i.Latitude,
		&i.Longitude,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getProductImages = `-- name: GetProductImages :many
SELECT id, product_id, url, alt_text, sort_order, is_primary, created_at
FROM product_images
WHERE product_id = $1
ORDER BY is_primary DESC, sort_order ASC
`

// GetProductImages
//
//	SELECT id, product_id, url, alt_text, sort_order, is_primary, created_at
//	FROM product_images
//	WHERE product_id = $1
//	ORDER BY is_primary DESC, sort_order ASC
func (q *Queries) GetProductImages(ctx context.Context, productID uuid.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, getProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.AltText,
			&i.SortOrder,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductTags = `-- name: GetProductTags :many
SELECT t.id, t.name, t.slug
FROM tags t
JOIN product_tags pt ON pt.tag_id = t.id
WHERE pt.product_id = $1
`

// GetProductTags
//
//	SELECT t.id, t.name, t.slug
//	FROM tags t
//	JOIN product_tags pt ON pt.tag_id = t.id
//	WHERE pt.product_id = $1
func (q *Queries) GetProductTags(ctx context.Context, productID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getProductTags, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductVariants = `-- name: GetProductVariants :many
SELECT id, product_id, sku, options, price, compare_price, weight_grams, image_url, is_default, created_at, updated_at
FROM product_variants
WHERE product_id = $1
ORDER BY is_default DESC, price ASC
`

// GetProductVariants
//
//	SELECT id, product_id, sku, options, price, compare_price, weight_grams, image_url, is_default, created_at, updated_at
//	FROM product_variants
//	WHERE product_id = $1
//	ORDER BY is_default DESC, price ASC
func (q *Queries) GetProductVariants(ctx context.Context, productID uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, getProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Options,
			&i.Price,
			&i.ComparePrice,
			&i.WeightGrams,
			&i.ImageUrl,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariantBatch = `-- name: GetVariantBatch :many
SELECT id, product_id, sku, options, price, compare_price, weight_grams, image_url, is_default, created_at, updated_at
FROM product_variants
WHERE id = ANY($1::uuid[])
`

// GetVariantBatch
//
//	SELECT id, product_id, sku, options, price, compare_price, weight_grams, image_url, is_default, created_at, updated_at
//	FROM product_variants
//	WHERE id = ANY($1::uuid[])
func (q *Queries) GetVariantBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, getVariantBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Options,
			&i.Price,
			&i.ComparePrice,
			&i.WeightGrams,
			&i.ImageUrl,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearbyProducts = `-- name: ListNearbyProducts :many
SELECT 
    p.id, p.seller_id, p.category_id, p.slug, p.attributes, p.brand, p.origin_country,
    p.status, p.rating, p.review_count, p.sold_count, p.view_count, p.min_price, p.max_price,
    p.image_url, p.thumbnail_url,
    p.created_at, p.updated_at, p.deleted_at, p.product_type,
    ST_Y(p.location::geometry)::float AS latitude,
    ST_X(p.location::geometry)::float AS longitude,
    ST_Distance(p.location, ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography)::float AS distance_meters,
    COALESCE(t.title, t_en.title, '')       AS title,
    COALESCE(t.description, t_en.description) AS description
FROM products p
LEFT JOIN product_translations t    ON t.product_id = p.id AND $3::text = t.language
LEFT JOIN product_translations t_en ON t_en.product_id = p.id AND t_en.language = 'en'
WHERE p.deleted_at IS NULL
  AND p.status = 'active'
  AND ST_DWithin(p.location, ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography, $4::float)
ORDER BY distance_meters ASC
LIMIT $6::int OFFSET $5::int
`

type ListNearbyProductsParams struct {
	Longitude    float64 `json:"longitude"`
	Latitude     float64 `json:"latitude"`
	Language     string  `json:"language"`
	RadiusMeters float64 `json:"radius_meters"`
	OffsetVal    int32   `json:"offset_val"`
	LimitVal     int32   `json:"limit_val"`
}

type ListNearbyProductsRow struct {
	ID             uuid.UUID      `json:"id"`
	SellerID       uuid.UUID      `json:"seller_id"`
	CategoryID     uuid.UUID      `json:"category_id"`
	Slug           string         `json:"slug"`
	Attributes     []byte         `json:"attributes"`
	Brand          *string        `json:"brand"`
	OriginCountry  *string        `json:"origin_country"`
	Status         string         `json:"status"`
	Rating         pgtype.Numeric `json:"rating"`
	ReviewCount    int32          `json:"review_count"`
	SoldCount      int32          `json:"sold_count"`
	ViewCount      int32          `json:"view_count"`
	MinPrice       pgtype.Numeric `json:"min_price"`
	MaxPrice       pgtype.Numeric `json:"max_price"`
	ImageUrl       *string        `json:"image_url"`
	ThumbnailUrl   *string        `json:"thumbnail_url"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      *time.Time     `json:"deleted_at"`
	ProductType    string         `json:"product_type"`
	Latitude       float64        `json:"latitude"`
	Longitude      float64        `json:"longitude"`
	DistanceMeters float64        `json:"distance_meters"`
	Title          string         `json:"title"`
	Description    *string        `json:"description"`
}

// ListNearbyProducts
//
//	SELECT
//	    p.id, p.seller_id, p.category_id, p.slug, p.attributes, p.brand, p.origin_country,
//	    p.status, p.rating, p.review_count, p.sold_count, p.view_count, p.min_price, p.max_price,
//	    p.image_url, p.thumbnail_url,
//	    p.created_at, p.updated_at, p.deleted_at, p.product_type,
//	    ST_Y(p.location::geometry)::float AS latitude,
//	    ST_X(p.location::geometry)::float AS longitude,
//	    ST_Distance(p.location, ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography)::float AS distance_meters,
//	    COALESCE(t.title, t_en.title, '')       AS title,
//	    COALESCE(t.description, t_en.description) AS description
//	FROM products p
//	LEFT JOIN product_translations t    ON t.product_id = p.id AND $3::text = t.language
//	LEFT JOIN product_translations t_en ON t_en.product_id = p.id AND t_en.language = 'en'
//	WHERE p.deleted_at IS NULL
//	  AND p.status = 'active'
//	  AND ST_DWithin(p.location, ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography, $4::float)
//	ORDER BY distance_meters ASC
//	LIMIT $6::int OFFSET $5::int
func (q *Queries) ListNearbyProducts(ctx context.Context, arg ListNearbyProductsParams) ([]ListNearbyProductsRow, error) {
	rows, err := q.db.Query(ctx, listNearbyProducts,
		arg.Longitude,
		arg.Latitude,
		arg.Language,
		arg.RadiusMeters,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearbyProductsRow
	for rows.Next() {
		var i ListNearbyProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Slug,
			&i.Attributes,
			&i.Brand,
			&i.OriginCountry,
			&i.Status,
			&i.Rating,
			&i.ReviewCount,
			&i.SoldCount,
			&i.ViewCount,
			&i.MinPrice,
			&i.MaxPrice,
			&i.ImageUrl,
			&i.ThumbnailUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductType,
			&i.Latitude,
			&i.Longitude,
			&i.DistanceMeters,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products SET
    brand         = COALESCE(NULLIF($1::text, ''), brand),
    status        = COALESCE(NULLIF($2::text, '')::product_status, status),
    image_url     = COALESCE(NULLIF($3::text, ''), image_url),
    thumbnail_url = COALESCE(NULLIF($4::text, ''), thumbnail_url),
    updated_at    = NOW()
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateProductParams struct {
	Brand        string    `json:"brand"`
	Status       string    `json:"status"`
	ImageUrl     string    `json:"image_url"`
	ThumbnailUrl string    `json:"thumbnail_url"`
	ID           uuid.UUID `json:"id"`
}

// UpdateProduct
//
//	UPDATE products SET
//	    brand         = COALESCE(NULLIF($1::text, ''), brand),
//	    status        = COALESCE(NULLIF($2::text, '')::product_status, status),
//	    image_url     = COALESCE(NULLIF($3::text, ''), image_url),
//	    thumbnail_url = COALESCE(NULLIF($4::text, ''), thumbnail_url),
//	    updated_at    = NOW()
//	WHERE id = $5 AND deleted_at IS NULL
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.Brand,
		arg.Status,
		arg.ImageUrl,
		arg.ThumbnailUrl,
		arg.ID,
	)
	return err
}
