// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Coupon struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	SellerID      pgtype.Text        `json:"seller_id"`
	DiscountType  string             `json:"discount_type"`
	DiscountValue pgtype.Numeric     `json:"discount_value"`
	MinOrderValue pgtype.Numeric     `json:"min_order_value"`
	MaxDiscount   pgtype.Numeric     `json:"max_discount"`
	StartDate     pgtype.Timestamptz `json:"start_date"`
	EndDate       pgtype.Timestamptz `json:"end_date"`
	UsageLimit    pgtype.Int4        `json:"usage_limit"`
	UsageCount    pgtype.Int4        `json:"usage_count"`
	IsActive      pgtype.Bool        `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type FlashSale struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type FlashSaleItem struct {
	ID            uuid.UUID          `json:"id"`
	FlashSaleID   uuid.UUID          `json:"flash_sale_id"`
	ProductID     string             `json:"product_id"`
	DiscountPrice pgtype.Numeric     `json:"discount_price"`
	StockLimit    int32              `json:"stock_limit"`
	SoldCount     int32              `json:"sold_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
