// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFlashSaleItem = `-- name: AddFlashSaleItem :one
INSERT INTO flash_sale_items (
  flash_sale_id, product_id, discount_price, stock_limit
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, flash_sale_id, product_id, discount_price, stock_limit, sold_count, created_at
`

type AddFlashSaleItemParams struct {
	FlashSaleID   uuid.UUID      `json:"flash_sale_id"`
	ProductID     string         `json:"product_id"`
	DiscountPrice pgtype.Numeric `json:"discount_price"`
	StockLimit    int32          `json:"stock_limit"`
}

func (q *Queries) AddFlashSaleItem(ctx context.Context, arg AddFlashSaleItemParams) (FlashSaleItem, error) {
	row := q.db.QueryRow(ctx, addFlashSaleItem,
		arg.FlashSaleID,
		arg.ProductID,
		arg.DiscountPrice,
		arg.StockLimit,
	)
	var i FlashSaleItem
	err := row.Scan(
		&i.ID,
		&i.FlashSaleID,
		&i.ProductID,
		&i.DiscountPrice,
		&i.StockLimit,
		&i.SoldCount,
		&i.CreatedAt,
	)
	return i, err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
  code, seller_id, discount_type, discount_value, min_order_value, max_discount, start_date, end_date, usage_limit
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, code, seller_id, discount_type, discount_value, min_order_value, max_discount, start_date, end_date, usage_limit, usage_count, is_active, created_at, updated_at
`

type CreateCouponParams struct {
	Code          string             `json:"code"`
	SellerID      pgtype.Text        `json:"seller_id"`
	DiscountType  string             `json:"discount_type"`
	DiscountValue pgtype.Numeric     `json:"discount_value"`
	MinOrderValue pgtype.Numeric     `json:"min_order_value"`
	MaxDiscount   pgtype.Numeric     `json:"max_discount"`
	StartDate     pgtype.Timestamptz `json:"start_date"`
	EndDate       pgtype.Timestamptz `json:"end_date"`
	UsageLimit    pgtype.Int4        `json:"usage_limit"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.Code,
		arg.SellerID,
		arg.DiscountType,
		arg.DiscountValue,
		arg.MinOrderValue,
		arg.MaxDiscount,
		arg.StartDate,
		arg.EndDate,
		arg.UsageLimit,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SellerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinOrderValue,
		&i.MaxDiscount,
		&i.StartDate,
		&i.EndDate,
		&i.UsageLimit,
		&i.UsageCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlashSale = `-- name: CreateFlashSale :one
INSERT INTO flash_sales (
  name, start_time, end_time, status
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, start_time, end_time, status, created_at, updated_at
`

type CreateFlashSaleParams struct {
	Name      string             `json:"name"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Status    string             `json:"status"`
}

func (q *Queries) CreateFlashSale(ctx context.Context, arg CreateFlashSaleParams) (FlashSale, error) {
	row := q.db.QueryRow(ctx, createFlashSale,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i FlashSale
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, seller_id, discount_type, discount_value, min_order_value, max_discount, start_date, end_date, usage_limit, usage_count, is_active, created_at, updated_at FROM coupons
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SellerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinOrderValue,
		&i.MaxDiscount,
		&i.StartDate,
		&i.EndDate,
		&i.UsageLimit,
		&i.UsageCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlashSaleItems = `-- name: GetFlashSaleItems :many
SELECT id, flash_sale_id, product_id, discount_price, stock_limit, sold_count, created_at FROM flash_sale_items
WHERE flash_sale_id = $1
`

func (q *Queries) GetFlashSaleItems(ctx context.Context, flashSaleID uuid.UUID) ([]FlashSaleItem, error) {
	rows, err := q.db.Query(ctx, getFlashSaleItems, flashSaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlashSaleItem
	for rows.Next() {
		var i FlashSaleItem
		if err := rows.Scan(
			&i.ID,
			&i.FlashSaleID,
			&i.ProductID,
			&i.DiscountPrice,
			&i.StockLimit,
			&i.SoldCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCouponUsage = `-- name: IncrementCouponUsage :exec
UPDATE coupons
SET usage_count = usage_count + 1
WHERE id = $1 AND (usage_limit = 0 OR usage_count < usage_limit)
`

func (q *Queries) IncrementCouponUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCouponUsage, id)
	return err
}

const listActiveFlashSales = `-- name: ListActiveFlashSales :many
SELECT id, name, start_time, end_time, status, created_at, updated_at FROM flash_sales
WHERE NOW() >= start_time AND NOW() <= end_time AND status = 'FLASH_SALE_STATUS_ACTIVE'
ORDER BY end_time ASC
`

func (q *Queries) ListActiveFlashSales(ctx context.Context) ([]FlashSale, error) {
	rows, err := q.db.Query(ctx, listActiveFlashSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlashSale
	for rows.Next() {
		var i FlashSale
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCouponsBySeller = `-- name: ListCouponsBySeller :many
SELECT id, code, seller_id, discount_type, discount_value, min_order_value, max_discount, start_date, end_date, usage_limit, usage_count, is_active, created_at, updated_at FROM coupons
WHERE seller_id = $1 OR seller_id = ''
ORDER BY created_at DESC
`

func (q *Queries) ListCouponsBySeller(ctx context.Context, sellerID pgtype.Text) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCouponsBySeller, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.SellerID,
			&i.DiscountType,
			&i.DiscountValue,
			&i.MinOrderValue,
			&i.MaxDiscount,
			&i.StartDate,
			&i.EndDate,
			&i.UsageLimit,
			&i.UsageCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
