// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Dispute struct {
	ID        uuid.UUID `json:"id"`
	OrderID   string    `json:"order_id"`
	BuyerID   string    `json:"buyer_id"`
	SellerID  string    `json:"seller_id"`
	Reason    string    `json:"reason"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DisputeMessage struct {
	ID           uuid.UUID `json:"id"`
	DisputeID    uuid.UUID `json:"dispute_id"`
	SenderID     string    `json:"sender_id"`
	Content      string    `json:"content"`
	EvidenceUrls []string  `json:"evidence_urls"`
	CreatedAt    time.Time `json:"created_at"`
}
