// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDispute = `-- name: CreateDispute :one
INSERT INTO disputes (
  order_id, buyer_id, seller_id, reason, status
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, order_id, buyer_id, seller_id, reason, status, created_at, updated_at
`

type CreateDisputeParams struct {
	OrderID  string `json:"order_id"`
	BuyerID  string `json:"buyer_id"`
	SellerID string `json:"seller_id"`
	Reason   string `json:"reason"`
	Status   string `json:"status"`
}

func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, createDispute,
		arg.OrderID,
		arg.BuyerID,
		arg.SellerID,
		arg.Reason,
		arg.Status,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDisputeMessage = `-- name: CreateDisputeMessage :one
INSERT INTO dispute_messages (
  dispute_id, sender_id, content, evidence_urls
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, dispute_id, sender_id, content, evidence_urls, created_at
`

type CreateDisputeMessageParams struct {
	DisputeID    uuid.UUID `json:"dispute_id"`
	SenderID     string    `json:"sender_id"`
	Content      string    `json:"content"`
	EvidenceUrls []string  `json:"evidence_urls"`
}

func (q *Queries) CreateDisputeMessage(ctx context.Context, arg CreateDisputeMessageParams) (DisputeMessage, error) {
	row := q.db.QueryRow(ctx, createDisputeMessage,
		arg.DisputeID,
		arg.SenderID,
		arg.Content,
		arg.EvidenceUrls,
	)
	var i DisputeMessage
	err := row.Scan(
		&i.ID,
		&i.DisputeID,
		&i.SenderID,
		&i.Content,
		&i.EvidenceUrls,
		&i.CreatedAt,
	)
	return i, err
}

const getDispute = `-- name: GetDispute :one
SELECT id, order_id, buyer_id, seller_id, reason, status, created_at, updated_at FROM disputes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDispute(ctx context.Context, id uuid.UUID) (Dispute, error) {
	row := q.db.QueryRow(ctx, getDispute, id)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllDisputes = `-- name: ListAllDisputes :many
SELECT id, order_id, buyer_id, seller_id, reason, status, created_at, updated_at FROM disputes
ORDER BY created_at DESC
`

func (q *Queries) ListAllDisputes(ctx context.Context) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, listAllDisputes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispute
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BuyerID,
			&i.SellerID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputeMessages = `-- name: ListDisputeMessages :many
SELECT id, dispute_id, sender_id, content, evidence_urls, created_at FROM dispute_messages
WHERE dispute_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListDisputeMessages(ctx context.Context, disputeID uuid.UUID) ([]DisputeMessage, error) {
	rows, err := q.db.Query(ctx, listDisputeMessages, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DisputeMessage
	for rows.Next() {
		var i DisputeMessage
		if err := rows.Scan(
			&i.ID,
			&i.DisputeID,
			&i.SenderID,
			&i.Content,
			&i.EvidenceUrls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputesByBuyer = `-- name: ListDisputesByBuyer :many
SELECT id, order_id, buyer_id, seller_id, reason, status, created_at, updated_at FROM disputes
WHERE buyer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDisputesByBuyer(ctx context.Context, buyerID string) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, listDisputesByBuyer, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispute
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BuyerID,
			&i.SellerID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputesBySeller = `-- name: ListDisputesBySeller :many
SELECT id, order_id, buyer_id, seller_id, reason, status, created_at, updated_at FROM disputes
WHERE seller_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDisputesBySeller(ctx context.Context, sellerID string) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, listDisputesBySeller, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispute
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BuyerID,
			&i.SellerID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisputeStatus = `-- name: UpdateDisputeStatus :one
UPDATE disputes
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, buyer_id, seller_id, reason, status, created_at, updated_at
`

type UpdateDisputeStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDisputeStatus(ctx context.Context, arg UpdateDisputeStatusParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, updateDisputeStatus, arg.ID, arg.Status)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
