// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: earnings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkLinkPayoutToEarnings = `-- name: BulkLinkPayoutToEarnings :exec
UPDATE seller_earnings
SET status = 'payout_released', payout_id = $2
WHERE seller_id = $1 AND status = 'earned'
`

type BulkLinkPayoutToEarningsParams struct {
	SellerID uuid.UUID   `json:"seller_id"`
	PayoutID pgtype.UUID `json:"payout_id"`
}

// BulkLinkPayoutToEarnings
//
//	UPDATE seller_earnings
//	SET status = 'payout_released', payout_id = $2
//	WHERE seller_id = $1 AND status = 'earned'
func (q *Queries) BulkLinkPayoutToEarnings(ctx context.Context, arg BulkLinkPayoutToEarningsParams) error {
	_, err := q.db.Exec(ctx, bulkLinkPayoutToEarnings, arg.SellerID, arg.PayoutID)
	return err
}

const countEarningsLedger = `-- name: CountEarningsLedger :one
SELECT COUNT(*)::int AS total FROM seller_earnings
WHERE seller_id = $1 AND ($2::text = '' OR status = $2)
`

type CountEarningsLedgerParams struct {
	SellerID uuid.UUID `json:"seller_id"`
	Column2  string    `json:"column_2"`
}

// CountEarningsLedger
//
//	SELECT COUNT(*)::int AS total FROM seller_earnings
//	WHERE seller_id = $1 AND ($2::text = '' OR status = $2)
func (q *Queries) CountEarningsLedger(ctx context.Context, arg CountEarningsLedgerParams) (int32, error) {
	row := q.db.QueryRow(ctx, countEarningsLedger, arg.SellerID, arg.Column2)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createEarningEntry = `-- name: CreateEarningEntry :one
INSERT INTO seller_earnings (seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id
`

type CreateEarningEntryParams struct {
	SellerID      uuid.UUID `json:"seller_id"`
	OrderID       uuid.UUID `json:"order_id"`
	OrderItemID   uuid.UUID `json:"order_item_id"`
	GrossAmount   float64   `json:"gross_amount"`
	CommissionFee float64   `json:"commission_fee"`
	NetAmount     float64   `json:"net_amount"`
	Status        string    `json:"status"`
}

// CreateEarningEntry
//
//	INSERT INTO seller_earnings (seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id
func (q *Queries) CreateEarningEntry(ctx context.Context, arg CreateEarningEntryParams) (SellerEarning, error) {
	row := q.db.QueryRow(ctx, createEarningEntry,
		arg.SellerID,
		arg.OrderID,
		arg.OrderItemID,
		arg.GrossAmount,
		arg.CommissionFee,
		arg.NetAmount,
		arg.Status,
	)
	var i SellerEarning
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.OrderID,
		&i.OrderItemID,
		&i.GrossAmount,
		&i.CommissionFee,
		&i.NetAmount,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.PayoutID,
	)
	return i, err
}

const createEarningEntryWithDetails = `-- name: CreateEarningEntryWithDetails :one
INSERT INTO seller_earnings (seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id
`

type CreateEarningEntryWithDetailsParams struct {
	SellerID      uuid.UUID          `json:"seller_id"`
	OrderID       uuid.UUID          `json:"order_id"`
	OrderItemID   uuid.UUID          `json:"order_item_id"`
	GrossAmount   float64            `json:"gross_amount"`
	CommissionFee float64            `json:"commission_fee"`
	NetAmount     float64            `json:"net_amount"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	SettledAt     pgtype.Timestamptz `json:"settled_at"`
}

// CreateEarningEntryWithDetails
//
//	INSERT INTO seller_earnings (seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
//	RETURNING id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id
func (q *Queries) CreateEarningEntryWithDetails(ctx context.Context, arg CreateEarningEntryWithDetailsParams) (SellerEarning, error) {
	row := q.db.QueryRow(ctx, createEarningEntryWithDetails,
		arg.SellerID,
		arg.OrderID,
		arg.OrderItemID,
		arg.GrossAmount,
		arg.CommissionFee,
		arg.NetAmount,
		arg.Status,
		arg.CreatedAt,
		arg.SettledAt,
	)
	var i SellerEarning
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.OrderID,
		&i.OrderItemID,
		&i.GrossAmount,
		&i.CommissionFee,
		&i.NetAmount,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.PayoutID,
	)
	return i, err
}

const getEarnedEarnings = `-- name: GetEarnedEarnings :many
SELECT id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id FROM seller_earnings
WHERE seller_id = $1 AND status = 'earned'
ORDER BY created_at ASC
`

// GetEarnedEarnings
//
//	SELECT id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id FROM seller_earnings
//	WHERE seller_id = $1 AND status = 'earned'
//	ORDER BY created_at ASC
func (q *Queries) GetEarnedEarnings(ctx context.Context, sellerID uuid.UUID) ([]SellerEarning, error) {
	rows, err := q.db.Query(ctx, getEarnedEarnings, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerEarning
	for rows.Next() {
		var i SellerEarning
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.OrderID,
			&i.OrderItemID,
			&i.GrossAmount,
			&i.CommissionFee,
			&i.NetAmount,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.PayoutID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEarnedSumBySeller = `-- name: GetEarnedSumBySeller :one
SELECT 
    COALESCE(SUM(gross_amount), 0)::numeric AS gross_sum,
    COALESCE(SUM(commission_fee), 0)::numeric AS fee_sum,
    COALESCE(SUM(net_amount), 0)::numeric AS net_sum
FROM seller_earnings
WHERE seller_id = $1 AND status = 'earned'
`

type GetEarnedSumBySellerRow struct {
	GrossSum float64 `json:"gross_sum"`
	FeeSum   float64 `json:"fee_sum"`
	NetSum   float64 `json:"net_sum"`
}

// GetEarnedSumBySeller
//
//	SELECT
//	    COALESCE(SUM(gross_amount), 0)::numeric AS gross_sum,
//	    COALESCE(SUM(commission_fee), 0)::numeric AS fee_sum,
//	    COALESCE(SUM(net_amount), 0)::numeric AS net_sum
//	FROM seller_earnings
//	WHERE seller_id = $1 AND status = 'earned'
func (q *Queries) GetEarnedSumBySeller(ctx context.Context, sellerID uuid.UUID) (GetEarnedSumBySellerRow, error) {
	row := q.db.QueryRow(ctx, getEarnedSumBySeller, sellerID)
	var i GetEarnedSumBySellerRow
	err := row.Scan(&i.GrossSum, &i.FeeSum, &i.NetSum)
	return i, err
}

const getSellerBalances = `-- name: GetSellerBalances :one
SELECT 
    COALESCE(SUM(CASE WHEN status = 'escrowed' THEN net_amount ELSE 0 END), 0)::numeric AS escrowed_balance,
    COALESCE(SUM(CASE WHEN status = 'earned' THEN net_amount ELSE 0 END), 0)::numeric AS withdrawable_balance
FROM seller_earnings
WHERE seller_id = $1
`

type GetSellerBalancesRow struct {
	EscrowedBalance     float64 `json:"escrowed_balance"`
	WithdrawableBalance float64 `json:"withdrawable_balance"`
}

// GetSellerBalances
//
//	SELECT
//	    COALESCE(SUM(CASE WHEN status = 'escrowed' THEN net_amount ELSE 0 END), 0)::numeric AS escrowed_balance,
//	    COALESCE(SUM(CASE WHEN status = 'earned' THEN net_amount ELSE 0 END), 0)::numeric AS withdrawable_balance
//	FROM seller_earnings
//	WHERE seller_id = $1
func (q *Queries) GetSellerBalances(ctx context.Context, sellerID uuid.UUID) (GetSellerBalancesRow, error) {
	row := q.db.QueryRow(ctx, getSellerBalances, sellerID)
	var i GetSellerBalancesRow
	err := row.Scan(&i.EscrowedBalance, &i.WithdrawableBalance)
	return i, err
}

const listEarningsLedger = `-- name: ListEarningsLedger :many
SELECT id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id FROM seller_earnings
WHERE seller_id = $1 AND ($4::text = '' OR status = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEarningsLedgerParams struct {
	SellerID uuid.UUID `json:"seller_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Column4  string    `json:"column_4"`
}

// ListEarningsLedger
//
//	SELECT id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id FROM seller_earnings
//	WHERE seller_id = $1 AND ($4::text = '' OR status = $4)
//	ORDER BY created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListEarningsLedger(ctx context.Context, arg ListEarningsLedgerParams) ([]SellerEarning, error) {
	rows, err := q.db.Query(ctx, listEarningsLedger,
		arg.SellerID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerEarning
	for rows.Next() {
		var i SellerEarning
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.OrderID,
			&i.OrderItemID,
			&i.GrossAmount,
			&i.CommissionFee,
			&i.NetAmount,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.PayoutID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEarningAmountsAndStatus = `-- name: UpdateEarningAmountsAndStatus :one
UPDATE seller_earnings
SET status = $2,
    payout_id = $3,
    gross_amount = $4,
    commission_fee = $5,
    net_amount = $6
WHERE id = $1
RETURNING id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id
`

type UpdateEarningAmountsAndStatusParams struct {
	ID            uuid.UUID   `json:"id"`
	Status        string      `json:"status"`
	PayoutID      pgtype.UUID `json:"payout_id"`
	GrossAmount   float64     `json:"gross_amount"`
	CommissionFee float64     `json:"commission_fee"`
	NetAmount     float64     `json:"net_amount"`
}

// UpdateEarningAmountsAndStatus
//
//	UPDATE seller_earnings
//	SET status = $2,
//	    payout_id = $3,
//	    gross_amount = $4,
//	    commission_fee = $5,
//	    net_amount = $6
//	WHERE id = $1
//	RETURNING id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id
func (q *Queries) UpdateEarningAmountsAndStatus(ctx context.Context, arg UpdateEarningAmountsAndStatusParams) (SellerEarning, error) {
	row := q.db.QueryRow(ctx, updateEarningAmountsAndStatus,
		arg.ID,
		arg.Status,
		arg.PayoutID,
		arg.GrossAmount,
		arg.CommissionFee,
		arg.NetAmount,
	)
	var i SellerEarning
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.OrderID,
		&i.OrderItemID,
		&i.GrossAmount,
		&i.CommissionFee,
		&i.NetAmount,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.PayoutID,
	)
	return i, err
}

const updateEarningStatusByOrderAndSeller = `-- name: UpdateEarningStatusByOrderAndSeller :exec
UPDATE seller_earnings
SET status = $3, settled_at = CASE WHEN $3 = 'earned' THEN NOW() ELSE settled_at END
WHERE order_id = $1 AND seller_id = $2
`

type UpdateEarningStatusByOrderAndSellerParams struct {
	OrderID  uuid.UUID `json:"order_id"`
	SellerID uuid.UUID `json:"seller_id"`
	Status   string    `json:"status"`
}

// UpdateEarningStatusByOrderAndSeller
//
//	UPDATE seller_earnings
//	SET status = $3, settled_at = CASE WHEN $3 = 'earned' THEN NOW() ELSE settled_at END
//	WHERE order_id = $1 AND seller_id = $2
func (q *Queries) UpdateEarningStatusByOrderAndSeller(ctx context.Context, arg UpdateEarningStatusByOrderAndSellerParams) error {
	_, err := q.db.Exec(ctx, updateEarningStatusByOrderAndSeller, arg.OrderID, arg.SellerID, arg.Status)
	return err
}

const updateEarningStatusByOrderItem = `-- name: UpdateEarningStatusByOrderItem :one
UPDATE seller_earnings
SET status = $2, settled_at = CASE WHEN $2 = 'earned' THEN NOW() ELSE settled_at END
WHERE order_item_id = $1
RETURNING id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id
`

type UpdateEarningStatusByOrderItemParams struct {
	OrderItemID uuid.UUID `json:"order_item_id"`
	Status      string    `json:"status"`
}

// UpdateEarningStatusByOrderItem
//
//	UPDATE seller_earnings
//	SET status = $2, settled_at = CASE WHEN $2 = 'earned' THEN NOW() ELSE settled_at END
//	WHERE order_item_id = $1
//	RETURNING id, seller_id, order_id, order_item_id, gross_amount, commission_fee, net_amount, status, created_at, settled_at, payout_id
func (q *Queries) UpdateEarningStatusByOrderItem(ctx context.Context, arg UpdateEarningStatusByOrderItemParams) (SellerEarning, error) {
	row := q.db.QueryRow(ctx, updateEarningStatusByOrderItem, arg.OrderItemID, arg.Status)
	var i SellerEarning
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.OrderID,
		&i.OrderItemID,
		&i.GrossAmount,
		&i.CommissionFee,
		&i.NetAmount,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.PayoutID,
	)
	return i, err
}
