// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countFollowedStores = `-- name: CountFollowedStores :one
SELECT COUNT(*) FROM store_follows WHERE user_id = $1
`

// CountFollowedStores
//
//	SELECT COUNT(*) FROM store_follows WHERE user_id = $1
func (q *Queries) CountFollowedStores(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowedStores, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStoreFollowers = `-- name: CountStoreFollowers :one
SELECT COUNT(*) FROM store_follows WHERE seller_id = $1
`

// CountStoreFollowers
//
//	SELECT COUNT(*) FROM store_follows WHERE seller_id = $1
func (q *Queries) CountStoreFollowers(ctx context.Context, sellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStoreFollowers, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const followStore = `-- name: FollowStore :exec
INSERT INTO store_follows (user_id, seller_id)
VALUES ($1, $2)
ON CONFLICT (user_id, seller_id) DO NOTHING
`

type FollowStoreParams struct {
	UserID   uuid.UUID `json:"user_id"`
	SellerID uuid.UUID `json:"seller_id"`
}

// FollowStore
//
//	INSERT INTO store_follows (user_id, seller_id)
//	VALUES ($1, $2)
//	ON CONFLICT (user_id, seller_id) DO NOTHING
func (q *Queries) FollowStore(ctx context.Context, arg FollowStoreParams) error {
	_, err := q.db.Exec(ctx, followStore, arg.UserID, arg.SellerID)
	return err
}

const isFollowingStore = `-- name: IsFollowingStore :one
SELECT EXISTS(
    SELECT 1 FROM store_follows
    WHERE user_id = $1 AND seller_id = $2
) AS is_following
`

type IsFollowingStoreParams struct {
	UserID   uuid.UUID `json:"user_id"`
	SellerID uuid.UUID `json:"seller_id"`
}

// IsFollowingStore
//
//	SELECT EXISTS(
//	    SELECT 1 FROM store_follows
//	    WHERE user_id = $1 AND seller_id = $2
//	) AS is_following
func (q *Queries) IsFollowingStore(ctx context.Context, arg IsFollowingStoreParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingStore, arg.UserID, arg.SellerID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const listFollowedStores = `-- name: ListFollowedStores :many
SELECT s.id, s.user_id, s.store_name, s.store_slug, s.logo_url, s.banner_url, s.description, s.rating, s.total_sales, s.is_verified, s.created_at, s.updated_at, s.latitude, s.longitude, s.status
FROM sellers s
INNER JOIN store_follows f ON f.seller_id = s.id
WHERE f.user_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowedStoresParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

// ListFollowedStores
//
//	SELECT s.id, s.user_id, s.store_name, s.store_slug, s.logo_url, s.banner_url, s.description, s.rating, s.total_sales, s.is_verified, s.created_at, s.updated_at, s.latitude, s.longitude, s.status
//	FROM sellers s
//	INNER JOIN store_follows f ON f.seller_id = s.id
//	WHERE f.user_id = $1
//	ORDER BY f.created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListFollowedStores(ctx context.Context, arg ListFollowedStoresParams) ([]Seller, error) {
	rows, err := q.db.Query(ctx, listFollowedStores, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seller
	for rows.Next() {
		var i Seller
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.StoreSlug,
			&i.LogoUrl,
			&i.BannerUrl,
			&i.Description,
			&i.Rating,
			&i.TotalSales,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreFollowers = `-- name: ListStoreFollowers :many
SELECT user_id FROM store_follows WHERE seller_id = $1
`

// ListStoreFollowers
//
//	SELECT user_id FROM store_follows WHERE seller_id = $1
func (q *Queries) ListStoreFollowers(ctx context.Context, sellerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStoreFollowers, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowStore = `-- name: UnfollowStore :exec
DELETE FROM store_follows
WHERE user_id = $1 AND seller_id = $2
`

type UnfollowStoreParams struct {
	UserID   uuid.UUID `json:"user_id"`
	SellerID uuid.UUID `json:"seller_id"`
}

// UnfollowStore
//
//	DELETE FROM store_follows
//	WHERE user_id = $1 AND seller_id = $2
func (q *Queries) UnfollowStore(ctx context.Context, arg UnfollowStoreParams) error {
	_, err := q.db.Exec(ctx, unfollowStore, arg.UserID, arg.SellerID)
	return err
}
