// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SellerStatus string

const (
	SellerStatusPending    SellerStatus = "pending"
	SellerStatusProcessing SellerStatus = "processing"
	SellerStatusVerified   SellerStatus = "verified"
	SellerStatusSuspended  SellerStatus = "suspended"
)

func (e *SellerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SellerStatus(s)
	case string:
		*e = SellerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SellerStatus: %T", src)
	}
	return nil
}

type NullSellerStatus struct {
	SellerStatus SellerStatus `json:"seller_status"`
	Valid        bool         `json:"valid"` // Valid is true if SellerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSellerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SellerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SellerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSellerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SellerStatus), nil
}

type Seller struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	StoreName   string    `json:"store_name"`
	StoreSlug   string    `json:"store_slug"`
	LogoUrl     *string   `json:"logo_url"`
	BannerUrl   *string   `json:"banner_url"`
	Description *string   `json:"description"`
	Rating      float64   `json:"rating"`
	TotalSales  int32     `json:"total_sales"`
	IsVerified  bool      `json:"is_verified"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	// Latitude coordinate for seller location (-90 to 90)
	Latitude *float64 `json:"latitude"`
	// Longitude coordinate for seller location (-180 to 180)
	Longitude *float64 `json:"longitude"`
	// Review status: pending → processing → verified | suspended
	Status SellerStatus `json:"status"`
	// Human-readable address string for the store location, derived from latitude/longitude coordinates
	StoreLocation            *string `json:"store_location"`
	CommissionRate           float64 `json:"commission_rate"`
	AdCreditBalance          float64 `json:"ad_credit_balance"`
	ShippingZones            string  `json:"shipping_zones"`
	BankName                 string  `json:"bank_name"`
	BankAccountNumber        string  `json:"bank_account_number"`
	EcocashNumber            string  `json:"ecocash_number"`
	ReturnWindowDays         int32   `json:"return_window_days"`
	ReturnPolicyText         string  `json:"return_policy_text"`
	PushNotificationsEnabled bool    `json:"push_notifications_enabled"`
	EmailAlertsEnabled       bool    `json:"email_alerts_enabled"`
	SmsAlertsEnabled         bool    `json:"sms_alerts_enabled"`
	AutoAcceptOrders         bool    `json:"auto_accept_orders"`
	InventoryAlertsEnabled   bool    `json:"inventory_alerts_enabled"`
	ProfileVisibility        bool    `json:"profile_visibility"`
	SearchIndexingEnabled    bool    `json:"search_indexing_enabled"`
	DataSharingEnabled       bool    `json:"data_sharing_enabled"`
	TwoFactorEnabled         bool    `json:"two_factor_enabled"`
	DeactivationReason       string  `json:"deactivation_reason"`
}

type SellerEarning struct {
	ID            uuid.UUID          `json:"id"`
	SellerID      uuid.UUID          `json:"seller_id"`
	OrderID       uuid.UUID          `json:"order_id"`
	OrderItemID   uuid.UUID          `json:"order_item_id"`
	GrossAmount   float64            `json:"gross_amount"`
	CommissionFee float64            `json:"commission_fee"`
	NetAmount     float64            `json:"net_amount"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	SettledAt     pgtype.Timestamptz `json:"settled_at"`
	PayoutID      pgtype.UUID        `json:"payout_id"`
}

type SellerPayout struct {
	ID          uuid.UUID          `json:"id"`
	SellerID    uuid.UUID          `json:"seller_id"`
	Amount      float64            `json:"amount"`
	Currency    string             `json:"currency"`
	Status      string             `json:"status"`
	ProviderRef *string            `json:"provider_ref"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   time.Time          `json:"created_at"`
	GrossAmount float64            `json:"gross_amount"`
	PlatformFee float64            `json:"platform_fee"`
	NetAmount   float64            `json:"net_amount"`
}

// Tracks which users follow which seller stores
type StoreFollow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	SellerID  uuid.UUID `json:"seller_id"`
	CreatedAt time.Time `json:"created_at"`
}
