// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countPayoutsBySeller = `-- name: CountPayoutsBySeller :one
SELECT COUNT(*)::int AS total FROM seller_payouts WHERE seller_id = $1
`

// CountPayoutsBySeller
//
//	SELECT COUNT(*)::int AS total FROM seller_payouts WHERE seller_id = $1
func (q *Queries) CountPayoutsBySeller(ctx context.Context, sellerID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPayoutsBySeller, sellerID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createPayout = `-- name: CreatePayout :one
INSERT INTO seller_payouts (seller_id, amount, currency, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, seller_id, amount, currency, status, provider_ref, paid_at, created_at
`

type CreatePayoutParams struct {
	SellerID uuid.UUID `json:"seller_id"`
	Amount   float64   `json:"amount"`
	Currency string    `json:"currency"`
}

// CreatePayout
//
//	INSERT INTO seller_payouts (seller_id, amount, currency, status)
//	VALUES ($1, $2, $3, 'pending')
//	RETURNING id, seller_id, amount, currency, status, provider_ref, paid_at, created_at
func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (SellerPayout, error) {
	row := q.db.QueryRow(ctx, createPayout, arg.SellerID, arg.Amount, arg.Currency)
	var i SellerPayout
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ProviderRef,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPayoutByID = `-- name: GetPayoutByID :one
SELECT id, seller_id, amount, currency, status, provider_ref, paid_at, created_at FROM seller_payouts WHERE id = $1
`

// GetPayoutByID
//
//	SELECT id, seller_id, amount, currency, status, provider_ref, paid_at, created_at FROM seller_payouts WHERE id = $1
func (q *Queries) GetPayoutByID(ctx context.Context, id uuid.UUID) (SellerPayout, error) {
	row := q.db.QueryRow(ctx, getPayoutByID, id)
	var i SellerPayout
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ProviderRef,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPayoutByIDForSeller = `-- name: GetPayoutByIDForSeller :one
SELECT id, seller_id, amount, currency, status, provider_ref, paid_at, created_at FROM seller_payouts WHERE id = $1 AND seller_id = $2
`

type GetPayoutByIDForSellerParams struct {
	ID       uuid.UUID `json:"id"`
	SellerID uuid.UUID `json:"seller_id"`
}

// GetPayoutByIDForSeller
//
//	SELECT id, seller_id, amount, currency, status, provider_ref, paid_at, created_at FROM seller_payouts WHERE id = $1 AND seller_id = $2
func (q *Queries) GetPayoutByIDForSeller(ctx context.Context, arg GetPayoutByIDForSellerParams) (SellerPayout, error) {
	row := q.db.QueryRow(ctx, getPayoutByIDForSeller, arg.ID, arg.SellerID)
	var i SellerPayout
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ProviderRef,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPayoutsBySeller = `-- name: ListPayoutsBySeller :many
SELECT id, seller_id, amount, currency, status, provider_ref, paid_at, created_at FROM seller_payouts
WHERE seller_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPayoutsBySellerParams struct {
	SellerID uuid.UUID `json:"seller_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

// ListPayoutsBySeller
//
//	SELECT id, seller_id, amount, currency, status, provider_ref, paid_at, created_at FROM seller_payouts
//	WHERE seller_id = $1
//	ORDER BY created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListPayoutsBySeller(ctx context.Context, arg ListPayoutsBySellerParams) ([]SellerPayout, error) {
	rows, err := q.db.Query(ctx, listPayoutsBySeller, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerPayout
	for rows.Next() {
		var i SellerPayout
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.ProviderRef,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
