// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sellers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO sellers (user_id, store_name, store_slug, logo_url, banner_url, description, latitude, longitude)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
`

type CreateSellerParams struct {
	UserID      uuid.UUID `json:"user_id"`
	StoreName   string    `json:"store_name"`
	StoreSlug   string    `json:"store_slug"`
	LogoUrl     *string   `json:"logo_url"`
	BannerUrl   *string   `json:"banner_url"`
	Description *string   `json:"description"`
	Latitude    *float64  `json:"latitude"`
	Longitude   *float64  `json:"longitude"`
}

// CreateSeller
//
//	INSERT INTO sellers (user_id, store_name, store_slug, logo_url, banner_url, description, latitude, longitude)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createSeller,
		arg.UserID,
		arg.StoreName,
		arg.StoreSlug,
		arg.LogoUrl,
		arg.BannerUrl,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.StoreSlug,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Description,
		&i.Rating,
		&i.TotalSales,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
	)
	return i, err
}

const getSellerByID = `-- name: GetSellerByID :one
SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status FROM sellers WHERE id = $1
`

// GetSellerByID
//
//	SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status FROM sellers WHERE id = $1
func (q *Queries) GetSellerByID(ctx context.Context, id uuid.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByID, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.StoreSlug,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Description,
		&i.Rating,
		&i.TotalSales,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
	)
	return i, err
}

const getSellerByStoreSlug = `-- name: GetSellerByStoreSlug :one
SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status FROM sellers WHERE store_slug = $1
`

// GetSellerByStoreSlug
//
//	SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status FROM sellers WHERE store_slug = $1
func (q *Queries) GetSellerByStoreSlug(ctx context.Context, storeSlug string) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByStoreSlug, storeSlug)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.StoreSlug,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Description,
		&i.Rating,
		&i.TotalSales,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
	)
	return i, err
}

const getSellerByUserID = `-- name: GetSellerByUserID :one
SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status FROM sellers WHERE user_id = $1
`

// GetSellerByUserID
//
//	SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status FROM sellers WHERE user_id = $1
func (q *Queries) GetSellerByUserID(ctx context.Context, userID uuid.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByUserID, userID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.StoreSlug,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Description,
		&i.Rating,
		&i.TotalSales,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
	)
	return i, err
}

const getSellersByIDs = `-- name: GetSellersByIDs :many
SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status FROM sellers WHERE id = ANY($1::uuid[])
`

// GetSellersByIDs
//
//	SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status FROM sellers WHERE id = ANY($1::uuid[])
func (q *Queries) GetSellersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Seller, error) {
	rows, err := q.db.Query(ctx, getSellersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seller
	for rows.Next() {
		var i Seller
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.StoreSlug,
			&i.LogoUrl,
			&i.BannerUrl,
			&i.Description,
			&i.Rating,
			&i.TotalSales,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSellersNearLocation = `-- name: GetSellersNearLocation :many
SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status, 
    (6371 * acos(cos(radians($2)) * cos(radians(latitude)) * cos(radians(longitude) - radians($3)) + sin(radians($2)) * sin(radians(latitude)))) AS distance_km
FROM sellers 
WHERE latitude IS NOT NULL AND longitude IS NOT NULL
    AND latitude BETWEEN $2 - ($4 / 111.32) AND $2 + ($4 / 111.32)
    AND longitude BETWEEN $3 - ($4 / (111.32 * cos(radians($2)))) AND $3 + ($4 / (111.32 * cos(radians($2))))
    AND (6371 * acos(cos(radians($2)) * cos(radians(latitude)) * cos(radians(longitude) - radians($3)) + sin(radians($2)) * sin(radians(latitude)))) <= $4
ORDER BY (6371 * acos(cos(radians($2)) * cos(radians(latitude)) * cos(radians(longitude) - radians($3)) + sin(radians($2)) * sin(radians(latitude))))
LIMIT $1
`

type GetSellersNearLocationParams struct {
	Limit     int32       `json:"limit"`
	Radians   float64     `json:"radians"`
	Radians_2 float64     `json:"radians_2"`
	Column4   interface{} `json:"column_4"`
}

type GetSellersNearLocationRow struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	StoreName   string       `json:"store_name"`
	StoreSlug   string       `json:"store_slug"`
	LogoUrl     *string      `json:"logo_url"`
	BannerUrl   *string      `json:"banner_url"`
	Description *string      `json:"description"`
	Rating      float64      `json:"rating"`
	TotalSales  int32        `json:"total_sales"`
	IsVerified  bool         `json:"is_verified"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Latitude    *float64     `json:"latitude"`
	Longitude   *float64     `json:"longitude"`
	Status      SellerStatus `json:"status"`
	DistanceKm  int32        `json:"distance_km"`
}

// GetSellersNearLocation
//
//	SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status,
//	    (6371 * acos(cos(radians($2)) * cos(radians(latitude)) * cos(radians(longitude) - radians($3)) + sin(radians($2)) * sin(radians(latitude)))) AS distance_km
//	FROM sellers
//	WHERE latitude IS NOT NULL AND longitude IS NOT NULL
//	    AND latitude BETWEEN $2 - ($4 / 111.32) AND $2 + ($4 / 111.32)
//	    AND longitude BETWEEN $3 - ($4 / (111.32 * cos(radians($2)))) AND $3 + ($4 / (111.32 * cos(radians($2))))
//	    AND (6371 * acos(cos(radians($2)) * cos(radians(latitude)) * cos(radians(longitude) - radians($3)) + sin(radians($2)) * sin(radians(latitude)))) <= $4
//	ORDER BY (6371 * acos(cos(radians($2)) * cos(radians(latitude)) * cos(radians(longitude) - radians($3)) + sin(radians($2)) * sin(radians(latitude))))
//	LIMIT $1
func (q *Queries) GetSellersNearLocation(ctx context.Context, arg GetSellersNearLocationParams) ([]GetSellersNearLocationRow, error) {
	rows, err := q.db.Query(ctx, getSellersNearLocation,
		arg.Limit,
		arg.Radians,
		arg.Radians_2,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSellersNearLocationRow
	for rows.Next() {
		var i GetSellersNearLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.StoreSlug,
			&i.LogoUrl,
			&i.BannerUrl,
			&i.Description,
			&i.Rating,
			&i.TotalSales,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.DistanceKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSellersWithinRadius = `-- name: GetSellersWithinRadius :many
SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status,
    (6371 * acos(cos(radians($1)) * cos(radians(latitude)) * cos(radians(longitude) - radians($2)) + sin(radians($1)) * sin(radians(latitude)))) AS distance_km
FROM sellers 
WHERE latitude IS NOT NULL AND longitude IS NOT NULL
    AND (6371 * acos(cos(radians($1)) * cos(radians(latitude)) * cos(radians(longitude) - radians($2)) + sin(radians($1)) * sin(radians(latitude)))) <= $3
ORDER BY (6371 * acos(cos(radians($1)) * cos(radians(latitude)) * cos(radians(longitude) - radians($2)) + sin(radians($1)) * sin(radians(latitude))))
`

type GetSellersWithinRadiusParams struct {
	Radians   float64  `json:"radians"`
	Radians_2 float64  `json:"radians_2"`
	Latitude  *float64 `json:"latitude"`
}

type GetSellersWithinRadiusRow struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	StoreName   string       `json:"store_name"`
	StoreSlug   string       `json:"store_slug"`
	LogoUrl     *string      `json:"logo_url"`
	BannerUrl   *string      `json:"banner_url"`
	Description *string      `json:"description"`
	Rating      float64      `json:"rating"`
	TotalSales  int32        `json:"total_sales"`
	IsVerified  bool         `json:"is_verified"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Latitude    *float64     `json:"latitude"`
	Longitude   *float64     `json:"longitude"`
	Status      SellerStatus `json:"status"`
	DistanceKm  int32        `json:"distance_km"`
}

// GetSellersWithinRadius
//
//	SELECT id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status,
//	    (6371 * acos(cos(radians($1)) * cos(radians(latitude)) * cos(radians(longitude) - radians($2)) + sin(radians($1)) * sin(radians(latitude)))) AS distance_km
//	FROM sellers
//	WHERE latitude IS NOT NULL AND longitude IS NOT NULL
//	    AND (6371 * acos(cos(radians($1)) * cos(radians(latitude)) * cos(radians(longitude) - radians($2)) + sin(radians($1)) * sin(radians(latitude)))) <= $3
//	ORDER BY (6371 * acos(cos(radians($1)) * cos(radians(latitude)) * cos(radians(longitude) - radians($2)) + sin(radians($1)) * sin(radians(latitude))))
func (q *Queries) GetSellersWithinRadius(ctx context.Context, arg GetSellersWithinRadiusParams) ([]GetSellersWithinRadiusRow, error) {
	rows, err := q.db.Query(ctx, getSellersWithinRadius, arg.Radians, arg.Radians_2, arg.Latitude)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSellersWithinRadiusRow
	for rows.Next() {
		var i GetSellersWithinRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.StoreSlug,
			&i.LogoUrl,
			&i.BannerUrl,
			&i.Description,
			&i.Rating,
			&i.TotalSales,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.DistanceKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementSellerTotalSales = `-- name: IncrementSellerTotalSales :one
UPDATE sellers SET
    total_sales = total_sales + $2,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
`

type IncrementSellerTotalSalesParams struct {
	ID         uuid.UUID `json:"id"`
	TotalSales int32     `json:"total_sales"`
}

// IncrementSellerTotalSales
//
//	UPDATE sellers SET
//	    total_sales = total_sales + $2,
//	    updated_at  = NOW()
//	WHERE id = $1
//	RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
func (q *Queries) IncrementSellerTotalSales(ctx context.Context, arg IncrementSellerTotalSalesParams) (Seller, error) {
	row := q.db.QueryRow(ctx, incrementSellerTotalSales, arg.ID, arg.TotalSales)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.StoreSlug,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Description,
		&i.Rating,
		&i.TotalSales,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
	)
	return i, err
}

const updateSeller = `-- name: UpdateSeller :one
UPDATE sellers SET
    store_name  = COALESCE(NULLIF($1::text, ''), store_name),
    store_slug  = COALESCE(NULLIF($2::text, ''), store_slug),
    logo_url    = COALESCE($3, logo_url),
    banner_url  = COALESCE($4, banner_url),
    description = COALESCE($5, description),
    latitude    = COALESCE($6, latitude),
    longitude   = COALESCE($7, longitude),
    updated_at  = NOW()
WHERE user_id = $8
RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
`

type UpdateSellerParams struct {
	StoreName   string    `json:"store_name"`
	StoreSlug   string    `json:"store_slug"`
	LogoUrl     *string   `json:"logo_url"`
	BannerUrl   *string   `json:"banner_url"`
	Description *string   `json:"description"`
	Latitude    *float64  `json:"latitude"`
	Longitude   *float64  `json:"longitude"`
	UserID      uuid.UUID `json:"user_id"`
}

// UpdateSeller
//
//	UPDATE sellers SET
//	    store_name  = COALESCE(NULLIF($1::text, ''), store_name),
//	    store_slug  = COALESCE(NULLIF($2::text, ''), store_slug),
//	    logo_url    = COALESCE($3, logo_url),
//	    banner_url  = COALESCE($4, banner_url),
//	    description = COALESCE($5, description),
//	    latitude    = COALESCE($6, latitude),
//	    longitude   = COALESCE($7, longitude),
//	    updated_at  = NOW()
//	WHERE user_id = $8
//	RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
func (q *Queries) UpdateSeller(ctx context.Context, arg UpdateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, updateSeller,
		arg.StoreName,
		arg.StoreSlug,
		arg.LogoUrl,
		arg.BannerUrl,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
		arg.UserID,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.StoreSlug,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Description,
		&i.Rating,
		&i.TotalSales,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
	)
	return i, err
}

const updateSellerStatus = `-- name: UpdateSellerStatus :one
UPDATE sellers SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
`

type UpdateSellerStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status SellerStatus `json:"status"`
}

// UpdateSellerStatus
//
//	UPDATE sellers SET
//	    status     = $2,
//	    updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
func (q *Queries) UpdateSellerStatus(ctx context.Context, arg UpdateSellerStatusParams) (Seller, error) {
	row := q.db.QueryRow(ctx, updateSellerStatus, arg.ID, arg.Status)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.StoreSlug,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Description,
		&i.Rating,
		&i.TotalSales,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
	)
	return i, err
}

const verifySeller = `-- name: VerifySeller :one
UPDATE sellers SET
    is_verified = $2,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
`

type VerifySellerParams struct {
	ID         uuid.UUID `json:"id"`
	IsVerified bool      `json:"is_verified"`
}

// VerifySeller
//
//	UPDATE sellers SET
//	    is_verified = $2,
//	    updated_at  = NOW()
//	WHERE id = $1
//	RETURNING id, user_id, store_name, store_slug, logo_url, banner_url, description, rating, total_sales, is_verified, created_at, updated_at, latitude, longitude, status
func (q *Queries) VerifySeller(ctx context.Context, arg VerifySellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, verifySeller, arg.ID, arg.IsVerified)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.StoreSlug,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.Description,
		&i.Rating,
		&i.TotalSales,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
	)
	return i, err
}
